// templates/admin-pro/vue/src/components/notifications-drawer.vue
<script setup lang="ts">
// src/components/notifications-drawer.vue —— 通知中心抽屉
// 对齐 vanilla app-shell.ts 通知段：抽屉右出、列表项点击已读、底部「全部已读」
// 数据状态由 AppShell 经 useNotifications() 持有一份（badge 与抽屉共享），本组件纯展示 + 事件上抛
// Vue 化差异（天然优势）：@click 直绑 panel 内元素本身（Vue 不用根委托），
// oas-drawer panel 对原生事件的 stopPropagation 不影响本组件内监听
import { computed } from 'vue'
import { useT } from '../composables/use-t'
import type { Notification } from '../data/notifications'

const props = defineProps<{
  open: boolean
  items: Notification[]
}>()
const emit = defineEmits<{
  close: []
  'read-one': [id: string]
  'read-all': []
}>()

const { t: tt, locale } = useT()
/** 模板文案函数：读 locale.value 建立响应式依赖，切语言时重渲 */
function t(key: string, params?: Record<string, string | number>): string {
  void locale.value
  return tt(key, params)
}

const allRead = computed(() => props.items.every((n) => n.read))

// 组件侧关闭（遮罩/Esc/✕）→ 回写父级状态，保持 visible 属性单一事实来源
function onDrawerClose(): void {
  emit('close')
}

// 列表项点击已读（vanilla notifList.addEventListener('click') 同款事件委托）
function onListClick(e: Event): void {
  const item = (e.target as HTMLElement).closest('oas-list-item')
  const id = item?.getAttribute('data-id')
  if (id) emit('read-one', id)
}
</script>

<template>
  <oas-drawer
    id="notif-drawer"
    :title="t('header.notification')"
    placement="right"
    size="medium"
    no-footer
    :visible="open ? '' : null"
    @oas-close="onDrawerClose"
  >
    <div class="notif-content">
      <div id="notif-list" class="notif-list">
        <oas-list split @click="onListClick">
          <oas-list-item
            v-for="n in items"
            :key="n.id"
            class="notif-item"
            :class="{ 'is-unread': !n.read }"
            :title="n.title"
            :data-id="n.id"
          >
            <span slot="description" class="notif-desc">{{ n.desc }}</span>
            <span slot="extra" class="notif-meta">
              <span class="notif-time">{{ n.time }}</span>
            </span>
          </oas-list-item>
        </oas-list>
      </div>
      <div class="notif-foot">
        <button
          id="notif-readall"
          class="link-btn"
          type="button"
          :disabled="allRead"
          @click="emit('read-all')"
        >
          {{ allRead ? t('header.allReadDone') : t('header.allRead') }}
        </button>
      </div>
    </div>
  </oas-drawer>
</template>

// templates/admin-pro/react/src/components/notifications-drawer.tsx
// src/components/notifications-drawer.tsx —— 通知中心抽屉 + 通知数据状态 hook
// 对齐 vanilla app-shell.ts 通知段：抽屉右出、列表项点击已读、底部「全部已读」、徽标数同步
// 状态由 AppShell 经 useNotifications() 持有一份，badge（header-bar）与抽屉共享
// 注意：oas-drawer 内部 panel 对 click stopPropagation（mask 点击关闭的配套），
// 抽屉内按钮/列表的 click 无法冒泡到 React 根委托——必须像 vanilla 一样在元素上直接 addEventListener
import { useCallback, useEffect, useRef, useState } from 'react'
import {
  listNotifications,
  markAllRead,
  markRead,
  type Notification,
} from '../data/notifications'
import { useOasEvent } from '../hooks/use-oas-event'
import { useT } from '../hooks/use-t'

/** 通知数据状态：list/markRead/markAllRead 是裸数据模块（无订阅），动作后重读列表驱动重渲染 */
export function useNotifications() {
  const [items, setItems] = useState<Notification[]>(listNotifications)
  const refresh = useCallback(() => setItems(listNotifications()), [])
  const readOne = useCallback(
    (id: string) => {
      markRead(id)
      refresh()
    },
    [refresh],
  )
  const readAll = useCallback(() => {
    markAllRead()
    refresh()
  }, [refresh])
  const unread = items.filter((n) => !n.read).length
  return { items, unread, readOne, readAll }
}

export interface NotificationsDrawerProps {
  open: boolean
  onClose: () => void
  items: Notification[]
  onReadOne: (id: string) => void
  onReadAll: () => void
}

export function NotificationsDrawer({
  open,
  onClose,
  items,
  onReadOne,
  onReadAll,
}: NotificationsDrawerProps) {
  const { t } = useT()
  const drawerRef = useRef<HTMLElement>(null)
  const listRef = useRef<HTMLElement>(null)
  const readAllRef = useRef<HTMLButtonElement>(null)
  const allRead = items.every((n) => n.read)

  // 组件侧关闭（遮罩/Esc/✕）→ 回写 React 状态，保持 visible 属性单一事实来源
  useOasEvent(drawerRef, 'oas-close', () => onClose())

  // 回调最新化：原生监听只在挂载时绑一次，避免 items 变化反复解绑
  const onReadOneRef = useRef(onReadOne)
  onReadOneRef.current = onReadOne
  const onReadAllRef = useRef(onReadAll)
  onReadAllRef.current = onReadAll

  // 列表项点击已读（vanilla notifList.addEventListener('click') 同款事件委托）
  useEffect(() => {
    const el = listRef.current
    if (!el) return
    const onClick = (e: Event) => {
      const item = (e.target as HTMLElement).closest('oas-list-item')
      const id = item?.getAttribute('data-id')
      if (id) onReadOneRef.current(id)
    }
    el.addEventListener('click', onClick)
    return () => el.removeEventListener('click', onClick)
  }, [])

  // 底部「全部已读」按钮（vanilla notifReadall 直绑）
  useEffect(() => {
    const el = readAllRef.current
    if (!el) return
    const onClick = () => onReadAllRef.current()
    el.addEventListener('click', onClick)
    return () => el.removeEventListener('click', onClick)
  }, [])

  return (
    <oas-drawer
      id="notif-drawer"
      ref={drawerRef as React.Ref<HTMLElement>}
      title={t('header.notification')}
      placement="right"
      size="medium"
      no-footer
      visible={open}
    >
      <div className="notif-content">
        <div id="notif-list" className="notif-list">
          <oas-list split ref={listRef as React.Ref<HTMLElement>}>
            {items.map((n) => (
              <oas-list-item
                key={n.id}
                className={`notif-item${n.read ? '' : ' is-unread'}`}
                title={n.title}
                data-id={n.id}
              >
                <span slot="description" className="notif-desc">
                  {n.desc}
                </span>
                <span slot="extra" className="notif-meta">
                  <span className="notif-time">{n.time}</span>
                </span>
              </oas-list-item>
            ))}
          </oas-list>
        </div>
        <div className="notif-foot">
          <button
            id="notif-readall"
            ref={readAllRef}
            className="link-btn"
            type="button"
            disabled={allRead}
          >
            {allRead ? t('header.allReadDone') : t('header.allRead')}
          </button>
        </div>
      </div>
    </oas-drawer>
  )
}
