// templates/admin-pro/vue/src/pages/data-board.vue
<script setup lang="ts">
// src/pages/data-board.vue —— 数据看板：统计卡 + 柱状/饼图/堆叠柱状图 + 进度条 + 水印层
//    boardData() 静态数据取一次，图表 data/卡片标题/月份标签全部 computed（依赖 locale），
//    本模版 v-if/v-else 同分支，data-testid 命名（anim-*/stat-*）逐字一致
import { computed } from 'vue'
import '../styles/pages/data-board.css'
import { boardData } from '../data/board'
import type { CategorySlice, ChannelSeries } from '../data/board'
import { useT } from '../composables/use-t'

const { t: tt, locale } = useT()
/** 模板文案函数：读 locale.value 建立响应式依赖，切语言时重渲 */
function t(key: string, params?: Record<string, string | number>): string {
  void locale.value
  return tt(key, params)
}

const STAT_KEYS = ['board.gmv', 'board.orders', 'board.users', 'board.conversion'] as const
const PROGRESS_KEYS = ['board.targetOrder', 'board.targetRevenue', 'board.targetUsers'] as const

const data = boardData()
const targets = data.quarterTargets
const progressValues = [targets.order, targets.revenue, targets.users]

const barData = computed(() =>
  JSON.stringify(data.monthRevenue.map((v, i) => ({ label: t(`board.month${i + 1}`), value: v }))),
)
const pieData = computed(() =>
  JSON.stringify(data.categoryShare.map((c: CategorySlice) => ({ label: c.name, value: c.value }))),
)
const stackedData = computed(() =>
  JSON.stringify({
    labels: data.channel.series[0]?.data.map((_, i) => t(`board.month${i + 1}`)) ?? [],
    series: data.channel.series.map((s: ChannelSeries) => ({ name: s.name, data: s.data })),
  }),
)
const stackedOptions = JSON.stringify({ showLegend: true })
</script>

<template>
  <div class="page">
    <div class="page-head">
      <div>
        <h1 class="page-title">{{ t('board.title') }}</h1>
        <p class="page-subtitle">{{ t('board.subtitle') }}</p>
      </div>
    </div>
    <oas-watermark text="OAS Admin Pro" repeat opacity="0.12">
      <div class="board-grid" id="board-grid">
        <oas-card v-for="(s, i) in data.stats" :key="s.key" class="stat-card">
          <div class="stat-label">{{ t(STAT_KEYS[i] ?? '') }}</div>
          <div class="stat-value">
            <span v-if="s.prefix" class="stat-prefix">{{ s.prefix }}</span>
            <oas-number-animation
              v-if="s.anim"
              :data-testid="`anim-${s.key}`"
              :value="s.value"
            />
            <oas-statistic v-else :data-testid="`stat-${s.key}`" :value="s.value">
              <span v-if="s.suffix" slot="suffix">{{ s.suffix }}</span>
            </oas-statistic>
          </div>
        </oas-card>
      </div>
      <div class="board-charts">
        <oas-card class="chart-card" :title="t('board.monthRevenue')">
          <oas-chart type="bar" :data="barData" :aria-label="t('board.monthRevenue')" />
        </oas-card>
        <oas-card class="chart-card" :title="t('board.categoryShare')">
          <oas-chart type="pie" :data="pieData" :aria-label="t('board.categoryShare')" />
        </oas-card>
        <oas-card class="chart-card chart-card--wide" :title="t('board.channelTrend')">
          <oas-chart
            type="stacked-bar"
            :options="stackedOptions"
            :data="stackedData"
            :aria-label="t('board.channelTrend')"
          />
        </oas-card>
      </div>
      <oas-card class="board-progress" :title="t('board.targetTitle')">
        <div class="progress-list">
          <div v-for="(key, i) in PROGRESS_KEYS" :key="key" class="progress-row">
            <span class="progress-label">{{ t(key) }}</span>
            <oas-progress :value="progressValues[i]" :data-testid="`board-progress-${['order', 'revenue', 'users'][i]}`" />
          </div>
        </div>
      </oas-card>
    </oas-watermark>
  </div>
</template>

// templates/admin-pro/react/src/pages/data-board.tsx
// src/pages/data-board.tsx —— 数据看板（水印 + 数字动画统计卡 + 三图表 + 季度目标进度）
//    本模版声明式 JSX，useT() 订阅 locale 后整页重渲染，图表 data/aria-label/progress
//    value 等 attribute 随之重算（数据全部来自 boardData() 纯函数，无异步）
import '../styles/pages/data-board.css'
import { boardData } from '../data/board'
import { useT } from '../hooks/use-t'

const STAT_KEYS = ['board.gmv', 'board.orders', 'board.users', 'board.conversion']
const PROGRESS_KEYS = ['board.targetOrder', 'board.targetRevenue', 'board.targetUsers']
const PROGRESS_TESTIDS = ['board-progress-order', 'board-progress-revenue', 'board-progress-users']

type TFunc = (key: string, params?: Record<string, string | number>) => string

function barData(data: number[], t: TFunc): string {
  return JSON.stringify(data.map((v, i) => ({ label: t(`board.month${i + 1}`), value: v })))
}

export default function DataBoardPage() {
  const { t } = useT()
  const data = boardData()

  const monthBar = barData(data.monthRevenue, t)
  const pie = JSON.stringify(data.categoryShare.map((c) => ({ label: c.name, value: c.value })))
  const stacked = JSON.stringify({
    labels: data.channel.series[0]?.data.map((_, i) => t(`board.month${i + 1}`)) ?? [],
    series: data.channel.series.map((s) => ({ name: s.name, data: s.data })),
  })
  const targets = data.quarterTargets
  const progressValues = [targets.order, targets.revenue, targets.users]

  return (
    <div className="page">
      <div className="page-head">
        <div>
          <h1 className="page-title">{t('board.title')}</h1>
          <p className="page-subtitle">{t('board.subtitle')}</p>
        </div>
      </div>
      <oas-watermark text="OAS Admin Pro" repeat opacity="0.12">
        <div className="board-grid" id="board-grid">
          {data.stats.map((s, i) => (
            <oas-card className="stat-card" key={s.key}>
              <div className="stat-label">{t(STAT_KEYS[i] ?? '')}</div>
              <div className="stat-value">
                {s.prefix ? <span className="stat-prefix">{s.prefix}</span> : null}
                {s.anim ? (
                  <oas-number-animation data-testid={`anim-${s.key}`} value={s.value} />
                ) : (
                  <oas-statistic data-testid={`stat-${s.key}`} value={s.value}>
                    {s.suffix ? <span slot="suffix">{s.suffix}</span> : null}
                  </oas-statistic>
                )}
              </div>
            </oas-card>
          ))}
        </div>
        <div className="board-charts">
          <oas-card className="chart-card" title={t('board.monthRevenue')}>
            <oas-chart type="bar" data={monthBar} aria-label={t('board.monthRevenue')} />
          </oas-card>
          <oas-card className="chart-card" title={t('board.categoryShare')}>
            <oas-chart type="pie" data={pie} aria-label={t('board.categoryShare')} />
          </oas-card>
          <oas-card className="chart-card chart-card--wide" title={t('board.channelTrend')}>
            <oas-chart
              type="stacked-bar"
              options='{"showLegend":true}'
              data={stacked}
              aria-label={t('board.channelTrend')}
            />
          </oas-card>
        </div>
        <oas-card className="board-progress" title={t('board.targetTitle')}>
          <div className="progress-list">
            {PROGRESS_KEYS.map((key, i) => (
              <div className="progress-row" key={key}>
                <span className="progress-label">{t(key)}</span>
                <oas-progress value={progressValues[i]} data-testid={PROGRESS_TESTIDS[i]} />
              </div>
            ))}
          </div>
        </oas-card>
      </oas-watermark>
    </div>
  )
}
