// templates/admin-pro/svelte/src/pages/logs.svelte
<script lang="ts">
  // src/pages/logs.svelte —— 日志中心（虚拟列表 + 日期锚点 + 统计卡 + 多条件过滤 + CSV 导出）
  // 对齐 react 版 logs.tsx：全量（统计卡）与过滤集（虚拟列表）拆两组数据；过滤条件变化即重取；
  // 统计/锚点分组/空态全部由 state 派生；数据变化回顶、语言切换锚点标题/表头/选项重算而
  // 过滤条件与滚动位置不动。
  // 1. 事件绑定：level/keyword/date 的 oas-change/oas-input/oas-clear、虚拟列表 oas-item/
  //    oas-scroll、锚点 oas-click、modal oas-cancel 模板直绑；导出按钮为原生 click 直绑
  // 2. 子组件拆分（单文件 ≤400 行纪律）：纯函数助手与行模板 ./logs-shared.ts、
  //    虚拟列表 ./logs-vlist.svelte（items 注入/buffer/行回填/滚动索引）
  import { onMount } from 'svelte'
  import '../styles/pages/logs.css'
  type LogEntry = import('../data/logs').LogEntry
  type LogLevel = import('../data/logs').LogLevel
  import { listLogs } from '../data/logs'
  import { appMessage } from '../lib/app-message'
  import { useT } from '../lib/use-t.svelte'
  import {
    buildDateGroups,
    dateKey,
    LEVEL_TAG,
    levelLabel,
    levelOptions,
  } from './logs-shared'
  import LogsVList from './logs-vlist.svelte'

  const { t, locale } = useT()
  /** 模板文案函数：读 $locale 建立响应式依赖，切语言时重渲 */
  const tt = $derived.by(() => {
    void $locale
    return t
  })

  let rows = $state<LogEntry[]>([])
  let filtered = $state<LogEntry[]>([])
  let level = $state<LogLevel | 'all'>('all')
  let keyword = $state('')
  let dateRange = $state<[string, string] | null>(null)
  let selected = $state<LogEntry | null>(null)
  let detailOpen = $state(false)
  let activeHref = $state<string | undefined>(undefined)
  let compact = $state(false)

  let vlistComp: ReturnType<typeof LogsVList> | null = $state(null)
  let logsCardEl: HTMLElement | null = $state(null)
  let detailModalEl: HTMLElement | null = $state(null)

  // title 命中 HTMLElement.prototype.title（property 通道会把未升级元素的 attribute 遮蔽掉），
  // oas-* 元素上的 title 必须走 setAttribute 通道
  $effect(() => {
    logsCardEl?.setAttribute('title', tt('logs.cardTitle'))
    detailModalEl?.setAttribute('title', tt('logs.detailTitle'))
  })

  onMount(() => {
    void (async () => {
      rows = await listLogs()
      await applyFilter()
    })()
    const mq = window.matchMedia('(max-width: 768px)')
    const sync = () => (compact = mq.matches)
    sync()
    mq.addEventListener('change', sync)
    return () => mq.removeEventListener('change', sync)
  })

  /** 过滤条件变化即重取（清条件回落全量语义由 listLogs 自己保证） */
  async function applyFilter(): Promise<void> {
    filtered = await listLogs({
      level,
      keyword,
      dateRange: dateRange ?? undefined,
    })
  }

  const stats = $derived.by(() => {
    const today = dateKey(new Date().toISOString())
    return {
      today,
      todayCount: rows.filter((r) => dateKey(r.time) === today).length,
      errorCount: rows.filter((r) => r.level === 'error').length,
      warnCount: rows.filter((r) => r.level === 'warn').length,
    }
  })

  const levelOptionsJson = $derived.by(() => {
    void $locale
    return JSON.stringify(levelOptions(tt))
  })

  /** 锚点分组：按日期切分过滤结果（随 locale 重算标题，index 不变） */
  const groups = $derived.by(() => {
    void $locale
    return buildDateGroups(filtered, tt)
  })

  const anchorItemsJson = $derived(
    JSON.stringify(
      groups.map((g) => ({
        href: `#logs-day-${g.date}`,
        title: `${g.label} (${g.date.slice(5)})`,
      })),
    ),
  )

  /** href → 该日首行行号（锚点点击定位用反查表） */
  const hrefIndexMap = $derived(
    new Map<string, number>(groups.map((g) => [`#logs-day-${g.date}`, g.index])),
  )

  function updateAnchorActive(): void {
    const index = Math.min(
      filtered.length - 1,
      vlistComp?.currentScrollIndex() ?? 0,
    )
    const row = filtered[index]
    if (!row) return
    activeHref = `#logs-day-${dateKey(row.time)}`
  }

  function onAnchorClick(e: Event): void {
    const href = (e as CustomEvent<{ href: string }>).detail.href
    const index = hrefIndexMap.get(href)
    if (index === undefined) return
    vlistComp?.scrollToIndex(index)
    activeHref = href
  }

  function onLevelChange(e: Event): void {
    const value = (e as CustomEvent<{ value: string }>).detail.value
    level = (value || 'all') as LogLevel | 'all'
    void applyFilter()
  }
  function onKeywordInput(e: Event): void {
    keyword = (e as CustomEvent<{ value: string }>).detail.value
    void applyFilter()
  }
  function onKeywordClear(): void {
    keyword = ''
    void applyFilter()
  }
  function onDateChange(e: Event): void {
    const value = (e as CustomEvent<{ value: string[] | string }>).detail.value
    if (Array.isArray(value) && value.length === 2 && value[0] && value[1]) {
      dateRange = [value[0], value[1]]
    } else {
      dateRange = null
    }
    void applyFilter()
  }

  function onDetailCancel(): void {
    detailOpen = false
    selected = null
  }

  function onExport(): void {
    if (filtered.length === 0) {
      appMessage.info(tt('logs.noExportable'))
      return
    }
    const header = tt('logs.exportHeader')
    const body = filtered.map((r) =>
      [r.time, levelLabel(r.level, tt), r.operator, r.action, r.IP].join(','),
    )
    const csv = `\ufeff${[header, ...body].join('\n')}`
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `logs-${Date.now()}.csv`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    setTimeout(() => URL.revokeObjectURL(url), 1000)
    appMessage.success(tt('logs.exported', { count: filtered.length }))
  }

  const empty = $derived(filtered.length === 0)
</script>

<div class="page">
  <div class="page-head">
    <div>
      <h1 class="page-title">{tt('nav.logs')}</h1>
      <p class="page-subtitle">{tt('logs.subtitle')}</p>
    </div>
  </div>
  <div class="logs-stats" id="logs-stats">
    <oas-card class="stat-card">
      <div class="stat-label">{tt('logs.stat.today')}</div>
      <div class="stat-value mono">{stats.todayCount}</div>
      <div class="stat-foot">{stats.today}</div>
    </oas-card>
    <oas-card class="stat-card">
      <div class="stat-label">{tt('logs.stat.errors')}</div>
      <div class="stat-value mono" style="color: var(--oas-color-danger)">{stats.errorCount}</div>
      <div class="stat-foot">{tt('logs.stat.errorLevel')}</div>
    </oas-card>
    <oas-card class="stat-card">
      <div class="stat-label">{tt('logs.stat.warns')}</div>
      <div class="stat-value mono" style="color: var(--oas-color-warning)">{stats.warnCount}</div>
      <div class="stat-foot">{tt('logs.stat.warnLevel')}</div>
    </oas-card>
  </div>
  <oas-card bind:this={logsCardEl} class="logs-card">
    <div class="logs-toolbar" slot="extra">
      <oas-select
        data-testid="logs-level"
        placeholder={tt('logs.toolbar.level')}
        clearable
        value={level}
        options={levelOptionsJson}
        onoas-change={onLevelChange}
      ></oas-select>
      <oas-input
        data-testid="logs-keyword"
        placeholder={tt('logs.toolbar.keyword')}
        clearable
        prefix-icon="search"
        onoas-input={onKeywordInput}
        onoas-clear={onKeywordClear}
      ></oas-input>
      <oas-date-picker
        data-testid="logs-date"
        type="daterange"
        placeholder={tt('logs.toolbar.dateRange')}
        onoas-change={onDateChange}
      ></oas-date-picker>
      
      <oas-button data-testid="logs-export" type="primary" icon="download" onclick={onExport}>
        {tt('logs.export')}
      </oas-button>
    </div>
    <div class="logs-main">
      <div class="logs-list-wrap">
        <div class="logs-header">
          <span class="logs-h-time">{tt('logs.th.time')}</span>
          <span class="logs-h-level">{tt('logs.th.level')}</span>
          <span class="logs-h-operator">{tt('logs.th.operator')}</span>
          <span class="logs-h-action">{tt('logs.th.action')}</span>
          <span class="logs-h-ip">{tt('logs.th.ip')}</span>
        </div>
        <div class="logs-list-body">
          <LogsVList
            bind:this={vlistComp}
            rows={filtered}
            {empty}
            onOpenDetail={(entry) => {
              selected = entry
              detailOpen = true
            }}
            onScroll={updateAnchorActive}
          />
          <div class="logs-empty" id="logs-empty" hidden={!empty}>
            <oas-empty description={tt('logs.empty')}></oas-empty>
          </div>
        </div>
      </div>
      <div class="logs-anchor-wrap">
        <oas-anchor
          data-testid="logs-anchor"
          id="logs-anchor"
          direction={compact ? 'horizontal' : 'vertical'}
          hash="false"
          items={anchorItemsJson}
          active={activeHref}
          onoas-click={onAnchorClick}
        ></oas-anchor>
      </div>
    </div>
  </oas-card>
  <oas-modal
    bind:this={detailModalEl}
    data-testid="logs-detail"
    id="logs-detail"
    no-footer
    visible={detailOpen ? '' : null}
    onoas-cancel={onDetailCancel}
  >
    <div class="logs-detail-body" id="logs-detail-body">
      <oas-descriptions column="1">
        <oas-descriptions-item label={tt('logs.dl.id')}>
          <span class="mono">{selected?.id ?? ''}</span>
        </oas-descriptions-item>
        <oas-descriptions-item label={tt('logs.th.time')}>
          <span class="mono">{selected?.time ?? ''}</span>
        </oas-descriptions-item>
        <oas-descriptions-item label={tt('logs.th.level')}>
          {#if selected}
            <oas-tag type={LEVEL_TAG[selected.level]}>
              {levelLabel(selected.level, tt)}
            </oas-tag>
          {/if}
        </oas-descriptions-item>
        <oas-descriptions-item label={tt('logs.th.operator')}>
          {selected?.operator ?? ''}
        </oas-descriptions-item>
        <oas-descriptions-item label={tt('logs.th.action')}>
          {selected?.action ?? ''}
        </oas-descriptions-item>
        <oas-descriptions-item label={tt('logs.th.ip')}>
          <span class="mono">{selected?.IP ?? ''}</span>
        </oas-descriptions-item>
      </oas-descriptions>
    </div>
  </oas-modal>
</div>

// templates/admin-pro/react/src/pages/logs.tsx
// src/pages/logs.tsx —— 日志中心（虚拟列表 + 日期锚点 + 统计卡 + 多条件过滤 + CSV 导出）
//    统计/锚点分组/空态全部由 state 派生
// 2. 事件绑定：level/keyword/date 的 oas-change/oas-input/oas-clear、虚拟列表 oas-item/oas-scroll、
//    锚点 oas-click、modal oas-cancel 走 useOasEvent导出按钮为 light DOM
//    原生 click 直绑 onClick；虚拟列表行 click 在 oas-item 回调里对 element 直绑（element 为
//    filtered/locale 变化时赋同一 property（setter 内部 slice + update，同引用也会重渲，
//    dangerouslySetInnerHTML 注入同款内容（见 ./logs-shared.ts）
//    锚点标题/表头/选项随 locale 重算，过滤条件与滚动位置不动
// 7. 子组件拆分（单文件 ≤400 行纪律）：纯函数助手与行模板 ./logs-shared.ts
// 8. oas-virtual-list 的 buffer 属性必须走 setAttribute：React 19 的 property 通道会覆写
//    组件原型方法 buffer()（字符串赋值），实测崩溃；详见挂载 effect 处注释
import { useEffect, useMemo, useRef, useState } from 'react'
import './logs.css'
import type { LogEntry, LogLevel } from '../data/logs'
import { useOasEvent } from '../hooks/use-oas-event'
import { useLogsAll, useLogsFiltered } from '../hooks/use-logs'
import { useT } from '../hooks/use-t'
import { appMessage } from '../lib/app-message'
import {
  ITEM_HEIGHT,
  ITEM_TEMPLATE_HTML,
  LEVEL_TAG,
  buildDateGroups,
  dateKey,
  formatTime,
  levelLabel,
  levelOptions,
} from './logs-shared'

export default function LogsPage() {
  const { t, locale } = useT()
  const [level, setLevel] = useState<LogLevel | 'all'>('all')
  const [keyword, setKeyword] = useState('')
  const [dateRange, setDateRange] = useState<[string, string] | null>(null)
  const [selected, setSelected] = useState<LogEntry | null>(null)
  const [detailOpen, setDetailOpen] = useState(false)
  const [compact, setCompact] = useState(() => window.matchMedia('(max-width: 768px)').matches)

  const vlistRef = useRef<HTMLElement | null>(null)
  const levelRef = useRef<HTMLElement | null>(null)
  const keywordRef = useRef<HTMLElement | null>(null)
  const dateRef = useRef<HTMLElement | null>(null)
  const anchorRef = useRef<HTMLElement | null>(null)
  const modalRef = useRef<HTMLElement | null>(null)

  // 全量（统计卡）与过滤集（虚拟列表）拆两个查询：过滤条件进 key，变化即换 key 重查
  const { data: allRows } = useLogsAll()
  const { data: filteredData } = useLogsFiltered({
    level,
    keyword,
    dateRange: dateRange ?? undefined,
  })
  const rows = allRows ?? []
  const filtered = filteredData ?? []

  useEffect(() => {
    const vlist = vlistRef.current as (HTMLElement & { items?: LogEntry[] }) | null
    if (vlist) vlist.items = filtered
  }, [filtered, locale])

  // buffer 必须走 attribute 通道：React 19 对 custom element 上 `in` 命中的键一律 property
  // 赋值，而 oas-virtual-list 原型上的 buffer() 是方法（virtual-list.js 内 this.buffer()），
  // buffer="8" 字面量属性会把它覆写成字符串致页面崩溃（dev 走查实测踩中），故挂载时
  useEffect(() => {
    vlistRef.current?.setAttribute('buffer', '8')
  }, [])

  const scrollToIndex = (index: number) => {
    const viewport = (
      vlistRef.current as unknown as { shadowRoot: ShadowRoot } | null
    )?.shadowRoot.querySelector<HTMLElement>('.viewport')
    if (!viewport) return
    viewport.scrollTop = Math.max(0, index * ITEM_HEIGHT)
  }

  const stats = useMemo(() => {
    const today = dateKey(new Date().toISOString())
    return {
      today,
      todayCount: rows.filter((r) => dateKey(r.time) === today).length,
      errorCount: rows.filter((r) => r.level === 'error').length,
      warnCount: rows.filter((r) => r.level === 'warn').length,
    }
  }, [rows])

  // eslint-disable-next-line react-hooks/exhaustive-deps
  const groups = useMemo(() => buildDateGroups(filtered, t), [filtered, locale])
  const anchorItemsJson = useMemo(
    () =>
      JSON.stringify(
        groups.map((g) => ({
          href: `#logs-day-${g.date}`,
          title: `${g.label} (${g.date.slice(5)})`,
        })),
      ),
    [groups],
  )

  useOasEvent<{ item: LogEntry; element: HTMLElement }>(vlistRef, 'oas-item', (detail) => {
    const { item, element } = detail
    element.querySelector<HTMLElement>('[data-col="time"]')!.textContent = formatTime(item.time)
    const tag = element.querySelector('oas-tag')!
    tag.textContent = levelLabel(item.level, t)
    tag.setAttribute('type', LEVEL_TAG[item.level])
    element.querySelector<HTMLElement>('[data-col="operator"]')!.textContent = item.operator
    element.querySelector<HTMLElement>('[data-col="action"]')!.textContent = item.action
    element.querySelector<HTMLElement>('[data-col="ip"]')!.textContent = item.IP
    element.addEventListener('click', () => {
      setSelected(item)
      setDetailOpen(true)
    })
  })

  useOasEvent(vlistRef, 'oas-scroll', () => {
    const viewport = (
      vlistRef.current as unknown as { shadowRoot: ShadowRoot } | null
    )?.shadowRoot.querySelector<HTMLElement>('.viewport')
    if (!viewport) return
    const index = Math.min(filtered.length - 1, Math.floor(viewport.scrollTop / ITEM_HEIGHT))
    const row = filtered[index]
    if (!row) return
    anchorRef.current?.setAttribute('active', `#logs-day-${dateKey(row.time)}`)
  })

  useOasEvent<{ href: string }>(anchorRef, 'oas-click', (detail) => {
    const group = groups.find((g) => `#logs-day-${g.date}` === detail.href)
    if (!group) return
    scrollToIndex(group.index)
    anchorRef.current?.setAttribute('active', detail.href)
  })

  useEffect(() => {
    const mq = window.matchMedia('(max-width: 768px)')
    const sync = () => setCompact(mq.matches)
    sync()
    mq.addEventListener('change', sync)
    return () => mq.removeEventListener('change', sync)
  }, [])

  useOasEvent<{ value: string }>(levelRef, 'oas-change', (d) => {
    setLevel((d.value || 'all') as LogLevel | 'all')
  })
  useOasEvent<{ value: string }>(keywordRef, 'oas-input', (d) => {
    setKeyword(d.value)
  })
  useOasEvent(keywordRef, 'oas-clear', () => {
    setKeyword('')
  })
  useOasEvent<{ value: string[] | string }>(dateRef, 'oas-change', (d) => {
    if (Array.isArray(d.value) && d.value.length === 2 && d.value[0] && d.value[1]) {
      setDateRange([d.value[0], d.value[1]])
    } else {
      setDateRange(null)
    }
  })

  useOasEvent(modalRef, 'oas-cancel', () => {
    setDetailOpen(false)
    setSelected(null)
  })

  const onExport = () => {
    if (filtered.length === 0) {
      appMessage.info(t('logs.noExportable'))
      return
    }
    const header = t('logs.exportHeader')
    const body = filtered.map((r) =>
      [r.time, levelLabel(r.level, t), r.operator, r.action, r.IP].join(','),
    )
    const csv = `\ufeff${[header, ...body].join('\n')}`
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `logs-${Date.now()}.csv`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    setTimeout(() => URL.revokeObjectURL(url), 1000)
    appMessage.success(t('logs.exported', { count: filtered.length }))
  }

  const empty = filtered.length === 0

  return (
    <div className="page">
      <div className="page-head">
        <div>
          <h1 className="page-title">{t('nav.logs')}</h1>
          <p className="page-subtitle">{t('logs.subtitle')}</p>
        </div>
      </div>
      <div className="logs-stats" id="logs-stats">
        <oas-card className="stat-card">
          <div className="stat-label">{t('logs.stat.today')}</div>
          <div className="stat-value mono">{stats.todayCount}</div>
          <div className="stat-foot">{stats.today}</div>
        </oas-card>
        <oas-card className="stat-card">
          <div className="stat-label">{t('logs.stat.errors')}</div>
          <div className="stat-value mono" style={{ color: 'var(--oas-color-danger)' }}>
            {stats.errorCount}
          </div>
          <div className="stat-foot">{t('logs.stat.errorLevel')}</div>
        </oas-card>
        <oas-card className="stat-card">
          <div className="stat-label">{t('logs.stat.warns')}</div>
          <div className="stat-value mono" style={{ color: 'var(--oas-color-warning)' }}>
            {stats.warnCount}
          </div>
          <div className="stat-foot">{t('logs.stat.warnLevel')}</div>
        </oas-card>
      </div>
      <oas-card className="logs-card" title={t('logs.cardTitle')}>
        <div className="logs-toolbar" slot="extra">
          <oas-select
            ref={levelRef}
            data-testid="logs-level"
            placeholder={t('logs.toolbar.level')}
            clearable
            value={level}
            options={JSON.stringify(levelOptions(t))}
          />
          <oas-input
            ref={keywordRef}
            data-testid="logs-keyword"
            placeholder={t('logs.toolbar.keyword')}
            clearable
            prefix-icon="search"
          />
          <oas-date-picker
            ref={dateRef}
            data-testid="logs-date"
            type="daterange"
            placeholder={t('logs.toolbar.dateRange')}
          />
          <oas-button data-testid="logs-export" type="primary" icon="download" onClick={onExport}>
            {t('logs.export')}
          </oas-button>
        </div>
        <div className="logs-main">
          <div className="logs-list-wrap">
            <div className="logs-header">
              <span className="logs-h-time">{t('logs.th.time')}</span>
              <span className="logs-h-level">{t('logs.th.level')}</span>
              <span className="logs-h-operator">{t('logs.th.operator')}</span>
              <span className="logs-h-action">{t('logs.th.action')}</span>
              <span className="logs-h-ip">{t('logs.th.ip')}</span>
            </div>
            <div className="logs-list-body">
              <oas-virtual-list
                ref={vlistRef}
                data-testid="logs-list"
                id="logs-list"
                height="480"
                item-height={ITEM_HEIGHT}
                hidden={empty || undefined}
              >
                <template slot="item" dangerouslySetInnerHTML={{ __html: ITEM_TEMPLATE_HTML }} />
              </oas-virtual-list>
              <div className="logs-empty" id="logs-empty" hidden={!empty || undefined}>
                <oas-empty description={t('logs.empty')} />
              </div>
            </div>
          </div>
          <div className="logs-anchor-wrap">
            <oas-anchor
              ref={anchorRef}
              data-testid="logs-anchor"
              id="logs-anchor"
              direction={compact ? 'horizontal' : 'vertical'}
              hash="false"
              items={anchorItemsJson}
            />
          </div>
        </div>
      </oas-card>
      <oas-modal
        ref={modalRef}
        data-testid="logs-detail"
        id="logs-detail"
        title={t('logs.detailTitle')}
        no-footer
        visible={detailOpen}
      >
        <div className="logs-detail-body" id="logs-detail-body">
          <oas-descriptions column="1">
            <oas-descriptions-item label={t('logs.dl.id')}>
              <span className="mono">{selected?.id ?? ''}</span>
            </oas-descriptions-item>
            <oas-descriptions-item label={t('logs.th.time')}>
              <span className="mono">{selected?.time ?? ''}</span>
            </oas-descriptions-item>
            <oas-descriptions-item label={t('logs.th.level')}>
              <oas-tag type={selected ? LEVEL_TAG[selected.level] : 'default'}>
                {selected ? levelLabel(selected.level, t) : ''}
              </oas-tag>
            </oas-descriptions-item>
            <oas-descriptions-item label={t('logs.th.operator')}>
              {selected?.operator ?? ''}
            </oas-descriptions-item>
            <oas-descriptions-item label={t('logs.th.action')}>
              {selected?.action ?? ''}
            </oas-descriptions-item>
            <oas-descriptions-item label={t('logs.th.ip')}>
              <span className="mono">{selected?.IP ?? ''}</span>
            </oas-descriptions-item>
          </oas-descriptions>
        </div>
      </oas-modal>
    </div>
  )
}
