// templates/admin-pro/svelte/src/pages/menus-detail.svelte
<script lang="ts">
  // src/pages/menus-detail.svelte —— 权限详情卡（选中节点描述/操作按钮）
  // 1. 数据与状态、删除编排都在父组件 menus.svelte；本组件纯展示 + 事件转发
  // 2. 事件绑定：详情区位于 oas-card 的 light DOM（非 drawer/modal panel），编辑/新增子菜单
  //    按钮直接 onclick（Svelte 对 custom element 不走根委托）；删除 popconfirm 的 oas-ok
  //    （kebab 自定义事件）经 bind:this + $effect 容器委托（div 上不能模板直绑）
  import type { MenuTree, MenuType } from '../data/system'
  import { useT } from '../lib/use-t.svelte'

  /** vanilla TYPE_TAG：菜单类型 → 标签色 */
  const TYPE_TAG: Record<MenuType, string> = { M: 'default', C: 'primary', F: 'warning' }

  interface MenusDetailProps {
    /** 当前选中节点（null → 空态） */
    node: MenuTree | null
    onEdit: (node: MenuTree) => void
    onAddChild: (node: MenuTree) => void
    onDelete: (node: MenuTree) => void
  }

  let { node, onEdit, onAddChild, onDelete }: MenusDetailProps = $props()

  const { t, locale } = useT()
  /** 模板文案函数：读 $locale 建立响应式依赖，切语言时重算 */
  const tt = $derived.by(() => {
    void $locale
    return t
  })

  let wrapEl: HTMLDivElement | null = $state(null)

  // 删除 popconfirm：oas-ok 容器委托（kebab 自定义事件不能在 div 上模板直绑）
  $effect(() => {
    const el = wrapEl
    if (!el) return
    el.addEventListener('oas-ok', onDeleteOk)
    return () => el.removeEventListener('oas-ok', onDeleteOk)
  })

  function onDeleteOk(): void {
    if (node) onDelete(node)
  }
</script>

{#if node}
  <div bind:this={wrapEl} class="menu-detail">
    <div class="menu-detail-head">
      <div class="menu-detail-title">{node.title}</div>
      <oas-tag type={TYPE_TAG[node.type]}>{tt(`menus.type.${node.type}`)}</oas-tag>
    </div>
    <oas-descriptions {...{ column: '1' }}>
      <oas-descriptions-item {...{ label: tt('menus.form.type') }}>
        <span class="mono">{node.type}</span>
      </oas-descriptions-item>
      <oas-descriptions-item {...{ label: tt('menus.form.perms') }}>
        <span class="mono" data-testid="menu-detail-perms">{node.perms ?? '—'}</span>
      </oas-descriptions-item>
      <oas-descriptions-item {...{ label: tt('menus.form.path') }}>
        <span class="mono">{node.path ?? '—'}</span>
      </oas-descriptions-item>
      <oas-descriptions-item {...{ label: tt('menus.detail.childCount') }}>
        <span class="mono">{(node.children ?? []).length}</span>
      </oas-descriptions-item>
    </oas-descriptions>
    <div class="menu-detail-actions">
      <oas-button type="primary" onclick={() => onEdit(node)}>{tt('common.edit')}</oas-button>
      <oas-button onclick={() => onAddChild(node)}>{tt('menus.addChild')}</oas-button>
      <oas-popconfirm {...{ title: tt('menus.confirmDelete'), id: 'md-del-pop' }}>
        <oas-button type="danger">{tt('common.delete')}</oas-button>
      </oas-popconfirm>
    </div>
  </div>
{:else}
  <oas-empty {...{ description: tt('menus.empty.selectNode') }}></oas-empty>
{/if}

<style>
  /* 权限详情域样式（自 react 版 menus.css 迁入，作用域限本文件） */
  .menu-detail {
    display: flex;
    flex-direction: column;
    gap: var(--oas-space-4);
  }
  .menu-detail-head {
    display: flex;
    align-items: center;
    gap: var(--oas-space-2);
  }
  .menu-detail-title {
    font-size: 16px;
    font-weight: 650;
    color: var(--oas-color-text-primary);
  }
  .menu-detail-actions {
    display: flex;
    gap: var(--oas-space-2);
    align-items: center;
  }
</style>

// templates/admin-pro/react/src/pages/menus-detail.tsx
// src/pages/menus-detail.tsx —— 权限详情卡（选中节点描述/操作按钮）
// 1. 数据与状态、删除编排都在父组件 menus.tsx；本组件纯展示 + 事件转发
// 2. 事件绑定：详情区位于 oas-card 的 light DOM（非 drawer/modal panel），原生 click 可达
//    React 根委托——编辑/新增子菜单按钮直接 onClick；删除 popconfirm 的 oas-ok 自定义
//    事件走 useOasEvent
// 3. oas-ok 监听绑定在仅 node 非空时才挂载的内层组件上：若挂在条件渲染的外层，
//    首挂载（node 为空）时 ref 为 null 且 effect 不再重跑，监听永远不会附上
import { useRef } from 'react'
import type { MenuTree, MenuType } from '../data/system'
import { useOasEvent } from '../hooks/use-oas-event'
import { useT } from '../hooks/use-t'

/** vanilla TYPE_TAG：菜单类型 → 标签色 */
const TYPE_TAG: Record<MenuType, string> = { M: 'default', C: 'primary', F: 'warning' }

export interface MenusDetailProps {
  /** 当前选中节点（null → 空态） */
  node: MenuTree | null
  onEdit: (node: MenuTree) => void
  onAddChild: (node: MenuTree) => void
  onDelete: (node: MenuTree) => void
}

export function MenusDetail(props: MenusDetailProps) {
  const { t } = useT()
  if (!props.node) return <oas-empty description={t('menus.empty.selectNode')} />
  // 内层组件仅在 node 非空时挂载，保证 useOasEvent 的 effect 首跑时 ref 已就绪
  return <MenusDetailInner {...props} node={props.node} />
}

function MenusDetailInner({
  node,
  onEdit,
  onAddChild,
  onDelete,
}: MenusDetailProps & { node: MenuTree }) {
  const { t } = useT()
  const wrapRef = useRef<HTMLDivElement | null>(null)

  useOasEvent(wrapRef, 'oas-ok', () => {
    onDelete(node)
  })

  return (
    <div ref={wrapRef} className="menu-detail">
      <div className="menu-detail-head">
        <div className="menu-detail-title">{node.title}</div>
        <oas-tag type={TYPE_TAG[node.type]}>{t(`menus.type.${node.type}`)}</oas-tag>
      </div>
      <oas-descriptions column="1">
        <oas-descriptions-item label={t('menus.form.type')}>
          <span className="mono">{node.type}</span>
        </oas-descriptions-item>
        <oas-descriptions-item label={t('menus.form.perms')}>
          <span className="mono" data-testid="menu-detail-perms">
            {node.perms ?? '—'}
          </span>
        </oas-descriptions-item>
        <oas-descriptions-item label={t('menus.form.path')}>
          <span className="mono">{node.path ?? '—'}</span>
        </oas-descriptions-item>
        <oas-descriptions-item label={t('menus.detail.childCount')}>
          <span className="mono">{(node.children ?? []).length}</span>
        </oas-descriptions-item>
      </oas-descriptions>
      <div className="menu-detail-actions">
        <oas-button data-md-action="edit" type="primary" onClick={() => onEdit(node)}>
          {t('common.edit')}
        </oas-button>
        <oas-button data-md-action="child" onClick={() => onAddChild(node)}>
          {t('menus.addChild')}
        </oas-button>
        <oas-popconfirm title={t('menus.confirmDelete')} id="md-del-pop">
          <oas-button data-md-action="delete" type="danger">
            {t('common.delete')}
          </oas-button>
        </oas-popconfirm>
      </div>
    </div>
  )
}
