// templates/admin-pro/svelte/src/pages/order-detail.svelte
<script lang="ts">
  // src/pages/order-detail.svelte —— 订单详情页（步骤条 + 描述列表 + 时间线 + 状态流转）
  // 对齐 react 版 order-detail.tsx：订单号经 sessionStorage('order-detail-id') 传入（orders-drawer
  // 以同键同时机写入，URL 不带 id 参数；隐藏路由经 meta.parent 归入订单父页签，仅用于面包屑）。
  // 数据挂载时经 getOrder(id) 拉取（react 版 query 缓存同语义），查无 id 显示空态；
  // 流程成功后 setOrder(updated)（react 版失效重取的可观察结果）即最新状态驱动全部动态区。
  import { onMount } from 'svelte'
  import '../styles/pages/orders.css'
  type OrderRow = import('../data/orders').OrderRow
  type OrderStatus = import('../data/orders').OrderStatus
  import { getOrder, updateOrderStatus } from '../data/orders'
  import { appMessage } from '../lib/app-message'
  import { useT } from '../lib/use-t.svelte'
  import { navigate } from '../router'
  import { statusLabel, tagTypeFor } from './orders-shared'

  const { t, locale } = useT()
  /** 模板文案函数：读 $locale 建立响应式依赖，切语言时重渲 */
  const tt = $derived.by(() => {
    void $locale
    return t
  })

  /** vanilla FLOW_STEPS / FLOW_TO：流转顺序与下一步映射 */
  const FLOW_STEPS: OrderStatus[] = ['pending', 'paid', 'shipping', 'done']
  const FLOW_TO: Partial<Record<OrderStatus, OrderStatus>> = {
    pending: 'paid',
    paid: 'shipping',
    shipping: 'done',
  }

  function flowFor(
    status: OrderStatus,
  ): { label: string; to: OrderStatus } | undefined {
    const to = FLOW_TO[status]
    return to ? { label: tt(`orders.flow.${status}`), to } : undefined
  }

  /** vanilla formatMoney（详情页版本：两位小数、无空格——与列表页金额格式刻意不同，逐字对齐） */
  function formatMoney(n: number): string {
    return `¥${n.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
  }

  /** vanilla addDays：yyyy-MM-dd 加 n 天 */
  function addDays(dateStr: string, n: number): string {
    const [y, m, d] = dateStr.split('-').map(Number)
    const date = new Date(y, m - 1, d)
    date.setDate(date.getDate() + n)
    const mm = String(date.getMonth() + 1).padStart(2, '0')
    const dd = String(date.getDate()).padStart(2, '0')
    return `${date.getFullYear()}-${mm}-${dd}`
  }

  interface TimelineNode {
    time: string
    title: string
    color?: string
  }

  /** vanilla buildTimeline：创建 → 已按状态推进的各节点（取消态只有取消节点） */
  function buildTimeline(order: OrderRow): TimelineNode[] {
    const nodes: TimelineNode[] = [
      { time: order.created, title: tt('orderDetail.timeline.created') },
    ]
    if (order.status === 'cancelled') {
      nodes.push({
        time: addDays(order.created, 1),
        title: statusLabel('cancelled', tt),
        color: 'red',
      })
      return nodes
    }
    const idx = FLOW_STEPS.indexOf(order.status)
    if (idx >= 1) nodes.push({ time: addDays(order.created, 1), title: statusLabel('paid', tt) })
    if (idx >= 2)
      nodes.push({ time: addDays(order.created, 2), title: statusLabel('shipping', tt) })
    if (idx >= 3)
      nodes.push({
        time: addDays(order.created, 3),
        title: statusLabel('done', tt),
        color: 'green',
      })
    return nodes
  }

  // 快照读取：与 react 版一致，组件初始化时一次性固化（pageKey 重挂载即重新读取）
  const id = sessionStorage.getItem('order-detail-id') ?? ''

  let order = $state<OrderRow | null>(null)
  let loaded = $state(false)
  let flowing = $state(false)

  onMount(() => {
    void (async () => {
      const data = await getOrder(id)
      order = data
      loaded = true
    })()
  })

  const missing = $derived(loaded && order === null)
  const flow = $derived(order ? flowFor(order.status) : undefined)
  const steps = $derived(
    order && order.status !== 'cancelled'
      ? FLOW_STEPS.map((s) => ({ title: statusLabel(s, tt) }))
      : null,
  )
  const timeline = $derived(order ? buildTimeline(order) : [])

  async function onAction(): Promise<void> {
    if (!order || !flow || flowing) return
    flowing = true
    try {
      const updated = await updateOrderStatus(order.id, flow.to)
      if (!updated) {
        appMessage.error(tt('orders.notFound'))
        return
      }
      appMessage.success(tt('orders.flowApplied', { action: tt(`orders.flow.${order.status}`) }))
      order = updated
    } finally {
      flowing = false
    }
  }

  const note = $derived(
    !order
      ? ''
      : order.status === 'done'
        ? tt('orders.noteDone')
        : tt('orders.noteCancelled'),
  )

  let phEl: HTMLElement | null = $state(null)
  // title 命中 HTMLElement.prototype.title，oas-* 元素上的 title 必须走 setAttribute 通道
  $effect(() => {
    phEl?.setAttribute('title', order ? order.id : tt('nav.orderDetail'))
  })
</script>

<div class="page order-detail-page">
  <oas-page-header
    bind:this={phEl}
    data-testid="order-page-header"
    class="order-detail-ph"
  >
    <div slot="extra" class="ph-extra">
      <a
        class="link-btn"
        data-testid="order-back"
        href="#/orders"
        onclick={(e) => {
          e.preventDefault()
          navigate('/orders')
        }}>{tt('orderDetail.backList')}</a
      >
      {#if order}
        <oas-tag
          data-testid="order-status-tag"
          type={tagTypeFor(order.status) === 'purple' ? undefined : tagTypeFor(order.status)}
          color={tagTypeFor(order.status) === 'purple' ? 'purple' : undefined}
        >
          {statusLabel(order.status, tt)}
        </oas-tag>
      {:else}
        <oas-tag data-testid="order-status-tag">{tt('orderDetail.loading')}</oas-tag>
      {/if}
    </div>
  </oas-page-header>
  <div id="order-detail-card" hidden={missing}>
    <oas-card>
      {#if steps && order}
        <div id="order-detail-steps">
          <oas-steps
            class="order-steps"
            steps={JSON.stringify(steps)}
            current={FLOW_STEPS.indexOf(order.status)}
          ></oas-steps>
        </div>
      {/if}
      <oas-descriptions data-testid="order-detail-basic" id="order-detail-basic" column="2">
        <oas-descriptions-item label={tt('orders.th.customer')}>
          {order?.customer ?? ''}
        </oas-descriptions-item>
        <oas-descriptions-item label={tt('orders.th.amount')}>
          <span class="mono">{order ? formatMoney(order.amount) : ''}</span>
        </oas-descriptions-item>
        <oas-descriptions-item label={tt('form.label.phone')}>
          <span class="mono">{order?.phone ?? '-'}</span>
        </oas-descriptions-item>
        <oas-descriptions-item label={tt('form.summary.urgent')}>
          {#if order}
            {order.urgent ? tt('form.label.urgent') : tt('form.summary.normalDelivery')}
          {/if}
        </oas-descriptions-item>
        <oas-descriptions-item label={tt('orders.th.created')}>
          <span class="mono">{order?.created ?? ''}</span>
        </oas-descriptions-item>
        <oas-descriptions-item label={tt('orders.th.items')}>
          {#each order?.items ?? [] as it, i (`${it}-${i}`)}
            <oas-tag>{it}</oas-tag>
          {/each}
        </oas-descriptions-item>
      </oas-descriptions>
      <div class="order-timeline-head">{tt('orderDetail.timelineTitle')}</div>
      <div id="order-detail-timeline-wrap">
        <oas-timeline data-testid="order-detail-timeline">
          {#each timeline as n, i (`${n.time}-${i}`)}
            <oas-timeline-item time={n.time} color={n.color}>{n.title}</oas-timeline-item>
          {/each}
        </oas-timeline>
      </div>
      <div class="order-detail-foot">
        {#if flow}
          <oas-button
            data-testid="order-detail-action"
            type="primary"
            loading={flowing}
            data-target={flow.to}
            onclick={onAction}
          >
            {flow.label}
          </oas-button>
        {/if}
        {#if !flow}
          <div class="order-detail-note" id="order-detail-note">{note}</div>
        {/if}
      </div>
    </oas-card>
  </div>
  {#if missing}
    <div id="order-detail-missing">
      <oas-empty description={tt('orderDetail.missing')}></oas-empty>
    </div>
  {/if}
</div>

// templates/admin-pro/react/src/pages/order-detail.tsx
// src/pages/order-detail.tsx —— 订单详情页（步骤条 + 描述列表 + 时间线 + 状态流转）
//    sessionStorage('order-detail-id') 后经 href="#/order-detail" 跳转（URL 不带 id 参数，
//    hidden+parent 路由仅用于面包屑）；本模版 orders-drawer 以同键同时机写入 + navigate
//    驱动全部动态区（标题/标签/步骤/描述/时间线/操作），flow 成功后 setOrder(updated) 即最新
// 3. 事件绑定：操作按钮位于 oas-card 内容区（非 drawer/modal panel），原生 click 用 React
//    双模式均正确，product-edit 同款）
//    重渲染，步骤/描述/时间线/操作随 locale 自动重算
//    load 语义一致）
import { useEffect, useState } from 'react'
import { Link } from 'react-router'
import { getOrder, updateOrderStatus } from '../data/orders'
import type { OrderRow, OrderStatus } from '../data/orders'
import { useT } from '../hooks/use-t'
import { appMessage } from '../lib/app-message'
import { statusLabel, tagTypeFor } from './orders-table'

type TFunc = (key: string, params?: Record<string, string | number>) => string

/** vanilla FLOW_STEPS / FLOW_TO：流转顺序与下一步映射 */
const FLOW_STEPS: OrderStatus[] = ['pending', 'paid', 'shipping', 'done']

const FLOW_TO: Partial<Record<OrderStatus, OrderStatus>> = {
  pending: 'paid',
  paid: 'shipping',
  shipping: 'done',
}

function flowFor(status: OrderStatus, t: TFunc): { label: string; to: OrderStatus } | undefined {
  const to = FLOW_TO[status]
  return to ? { label: t(`orders.flow.${status}`), to } : undefined
}

/** vanilla formatMoney（详情页版本：两位小数、无空格——与列表页金额格式刻意不同，逐字对齐） */
function formatMoney(n: number): string {
  return `¥${n.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
}

/** vanilla addDays：yyyy-MM-dd 加 n 天 */
function addDays(dateStr: string, n: number): string {
  const [y, m, d] = dateStr.split('-').map(Number)
  const date = new Date(y, m - 1, d)
  date.setDate(date.getDate() + n)
  const mm = String(date.getMonth() + 1).padStart(2, '0')
  const dd = String(date.getDate()).padStart(2, '0')
  return `${date.getFullYear()}-${mm}-${dd}`
}

interface TimelineNode {
  time: string
  title: string
  color?: string
}

/** vanilla buildTimeline：创建 → 已按状态推进的各节点（取消态只有取消节点） */
function buildTimeline(order: OrderRow, t: TFunc): TimelineNode[] {
  const nodes: TimelineNode[] = [{ time: order.created, title: t('orderDetail.timeline.created') }]
  if (order.status === 'cancelled') {
    nodes.push({
      time: addDays(order.created, 1),
      title: statusLabel('cancelled', t),
      color: 'red',
    })
    return nodes
  }
  const idx = FLOW_STEPS.indexOf(order.status)
  if (idx >= 1) nodes.push({ time: addDays(order.created, 1), title: statusLabel('paid', t) })
  if (idx >= 2) nodes.push({ time: addDays(order.created, 2), title: statusLabel('shipping', t) })
  if (idx >= 3)
    nodes.push({ time: addDays(order.created, 3), title: statusLabel('done', t), color: 'green' })
  return nodes
}

export default function OrderDetailPage() {
  const { t } = useT()
  const [id] = useState(() => sessionStorage.getItem('order-detail-id') ?? '')
  const [order, setOrder] = useState<OrderRow | null>(null)
  const [missing, setMissing] = useState(false)

  useEffect(() => {
    let cancelled = false
    void (async () => {
      const row = await getOrder(id)
      if (cancelled) return
      if (!row) setMissing(true)
      else setOrder(row)
    })()
    return () => {
      cancelled = true
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [id])

  const onAction = async (e: React.MouseEvent) => {
    if (!order) return
    const button = e.currentTarget as HTMLElement
    const target = button.dataset.target as OrderStatus | undefined
    if (!target) return
    button.setAttribute('loading', '')
    const updated = await updateOrderStatus(order.id, target)
    button.removeAttribute('loading')
    if (!updated) {
      appMessage.error(t('orders.notFound'))
      return
    }
    appMessage.success(t('orders.flowApplied', { action: button.textContent }))
    setOrder(updated)
  }

  const flow = order ? flowFor(order.status, t) : undefined
  const steps =
    order && order.status !== 'cancelled'
      ? FLOW_STEPS.map((s) => ({ title: statusLabel(s, t) }))
      : null
  const timeline = order ? buildTimeline(order, t) : []

  return (
    <div className="page order-detail-page">
      <oas-page-header
        data-testid="order-page-header"
        className="order-detail-ph"
        title={order ? order.id : t('nav.orderDetail')}
      >
        <div slot="extra" className="ph-extra">
          <Link className="link-btn" to="/orders" data-testid="order-back">
            {t('orderDetail.backList')}
          </Link>
          <oas-tag
            data-testid="order-status-tag"
            type={
              order
                ? tagTypeFor(order.status) === 'purple'
                  ? undefined
                  : tagTypeFor(order.status)
                : undefined
            }
            color={order && tagTypeFor(order.status) === 'purple' ? 'purple' : undefined}
          >
            {order ? statusLabel(order.status, t) : t('orderDetail.loading')}
          </oas-tag>
        </div>
      </oas-page-header>
      <div id="order-detail-card" hidden={missing || undefined}>
        <oas-card>
          <div id="order-detail-steps" hidden={!steps || undefined}>
            {steps && order && (
              <oas-steps
                className="order-steps"
                steps={JSON.stringify(steps)}
                current={FLOW_STEPS.indexOf(order.status)}
              />
            )}
          </div>
          <oas-descriptions data-testid="order-detail-basic" id="order-detail-basic" column="2">
            <oas-descriptions-item label={t('orders.th.customer')}>
              {order?.customer ?? ''}
            </oas-descriptions-item>
            <oas-descriptions-item label={t('orders.th.amount')}>
              <span className="mono">{order ? formatMoney(order.amount) : ''}</span>
            </oas-descriptions-item>
            <oas-descriptions-item label={t('form.label.phone')}>
              <span className="mono">{order?.phone ?? '-'}</span>
            </oas-descriptions-item>
            <oas-descriptions-item label={t('form.summary.urgent')}>
              {order
                ? order.urgent
                  ? t('form.label.urgent')
                  : t('form.summary.normalDelivery')
                : ''}
            </oas-descriptions-item>
            <oas-descriptions-item label={t('orders.th.created')}>
              <span className="mono">{order?.created ?? ''}</span>
            </oas-descriptions-item>
            <oas-descriptions-item label={t('orders.th.items')}>
              {order?.items.map((it, i) => (
                <oas-tag key={`${it}-${i}`}>{it}</oas-tag>
              ))}
            </oas-descriptions-item>
          </oas-descriptions>
          <div className="order-timeline-head">{t('orderDetail.timelineTitle')}</div>
          <div id="order-detail-timeline-wrap">
            <oas-timeline data-testid="order-detail-timeline">
              {timeline.map((n, i) => (
                <oas-timeline-item key={`${n.time}-${i}`} time={n.time} color={n.color}>
                  {n.title}
                </oas-timeline-item>
              ))}
            </oas-timeline>
          </div>
          <div className="order-detail-foot">
            <oas-button
              data-testid="order-detail-action"
              type="primary"
              hidden={!flow || undefined}
              data-target={flow?.to}
              onClick={(e) => void onAction(e)}
            >
              {flow?.label ?? ''}
            </oas-button>
            <div className="order-detail-note" id="order-detail-note" hidden={!!flow || undefined}>
              {order
                ? order.status === 'done'
                  ? t('orders.noteDone')
                  : t('orders.noteCancelled')
                : ''}
            </div>
          </div>
        </oas-card>
      </div>
      <div id="order-detail-missing" hidden={!missing || undefined}>
        {missing && <oas-empty description={t('orderDetail.missing')} />}
      </div>
    </div>
  )
}
