// templates/admin-pro/svelte/src/pages/products/products-batch-bar.svelte
<script lang="ts">
  // src/pages/products/products-batch-bar.svelte —— 商品批量操作栏（表格多选后出现：批量上下架 + 批量删除）
  // 1. 执行逻辑（toggle/removeProduct 循环、clearSelection、appMessage、refresh）留在父组件——
  //    它们依赖 rows/selected；本组件只负责呈现与事件接线
  // 2. 事件绑定：上下架/删除按钮在 light DOM，原生 click 模板直绑 onclick；oas-popconfirm 的
  //    oas-ok 是自定义事件，onoas-ok 模板直绑
  import { useT } from '../../lib/use-t.svelte'

  interface Props {
    /** 卡片视图或无选中项时隐藏 */
    hidden: boolean
    selectedCount: number
    canMutate: boolean
    onBatchStatus: (target: 'on' | 'off') => void
    /** popconfirm 确认删除后回调（父组件执行删除循环 + 提示 + 刷新） */
    onBatchDelete: () => void
  }

  let { hidden, selectedCount, canMutate, onBatchStatus, onBatchDelete }: Props = $props()

  const { t, locale } = useT()
  /** 模板文案函数：读 $locale 建立响应式依赖，切语言时重渲 */
  const tt = $derived.by(() => {
    void $locale
    return t
  })

  const enabled = $derived(canMutate && selectedCount > 0)
</script>

<div class="product-batch-bar" data-testid="product-batch-bar" hidden={hidden}>
  <span class="product-batch-count" data-testid="product-batch-count">
    {selectedCount > 0 ? tt('products.batch.selected', { count: selectedCount }) : ''}
  </span>
  <oas-space class="product-batch-actions" justify="end">
    <oas-button
      data-testid="product-batch-unlist"
      size="small"
      disabled={!enabled ? '' : null}
      onclick={() => onBatchStatus('off')}
    >
      {tt('products.batch.unlist')}
    </oas-button>
    <oas-button
      data-testid="product-batch-list"
      size="small"
      disabled={!enabled ? '' : null}
      onclick={() => onBatchStatus('on')}
    >
      {tt('products.batch.list')}
    </oas-button>
    <oas-popconfirm
      data-testid="product-batch-del-pop"
      id="product-batch-del-pop"
      title={tt('products.batch.confirmDelete', { count: selectedCount })}
      onoas-ok={() => onBatchDelete()}
    >
      <oas-button
        data-testid="product-batch-delete"
        size="small"
        type="danger"
        disabled={!enabled ? '' : null}
      >
        {tt('products.batch.delete')}
      </oas-button>
    </oas-popconfirm>
  </oas-space>
</div>

// templates/admin-pro/react/src/pages/products-batch-bar.tsx
// src/pages/products-batch-bar.tsx —— 商品批量操作栏（表格多选后出现：批量上下架 + 批量删除）
// popconfirm oas-ok 段。
// 1. 执行逻辑（toggleProductStatus/removeProduct 循环、clearSelection、appMessage、refresh）
//    留在父组件——它们依赖 rows/selected/refresh；本组件只负责呈现与事件接线
// 2. 事件绑定：上下架按钮在 light DOM，原生 click 用 React onClick；oas-popconfirm 的
//    oas-ok 是自定义事件，走 useOasEvent
import { useRef } from 'react'
import { useOasEvent } from '../hooks/use-oas-event'
import { useT } from '../hooks/use-t'

export interface ProductsBatchBarProps {
  /** 卡片视图或无选中项时隐藏 */
  hidden: boolean
  selectedCount: number
  canMutate: boolean
  onBatchStatus: (target: 'on' | 'off') => void
  /** popconfirm 确认删除后回调（父组件执行删除循环 + 提示 + 刷新） */
  onBatchDelete: () => void
}

export function ProductsBatchBar({
  hidden,
  selectedCount,
  canMutate,
  onBatchStatus,
  onBatchDelete,
}: ProductsBatchBarProps) {
  const { t } = useT()
  const delPopRef = useRef<HTMLElement | null>(null)
  const enabled = canMutate && selectedCount > 0

  useOasEvent(delPopRef, 'oas-ok', () => onBatchDelete())

  return (
    <div className="product-batch-bar" data-testid="product-batch-bar" hidden={hidden}>
      <span className="product-batch-count" data-testid="product-batch-count">
        {selectedCount > 0 ? t('products.batch.selected', { count: selectedCount }) : ''}
      </span>
      <oas-space className="product-batch-actions" justify="end">
        <oas-button
          data-testid="product-batch-unlist"
          size="small"
          disabled={!enabled || undefined}
          onClick={() => onBatchStatus('off')}
        >
          {t('products.batch.unlist')}
        </oas-button>
        <oas-button
          data-testid="product-batch-list"
          size="small"
          disabled={!enabled || undefined}
          onClick={() => onBatchStatus('on')}
        >
          {t('products.batch.list')}
        </oas-button>
        <oas-popconfirm
          ref={delPopRef}
          data-testid="product-batch-del-pop"
          id="product-batch-del-pop"
          title={t('products.batch.confirmDelete', { count: selectedCount })}
        >
          <oas-button
            data-testid="product-batch-delete"
            size="small"
            type="danger"
            disabled={!enabled || undefined}
          >
            {t('products.batch.delete')}
          </oas-button>
        </oas-popconfirm>
      </oas-space>
    </div>
  )
}
