// templates/admin-pro/vue/src/pages/result.vue
<script setup lang="ts">
// src/pages/result.vue —— 表单提交结果页（成功/失败双态，一次性读取 sessionStorage）
//    result-reset/result-back-form/result-actions）
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { appMessage, destroyAll } from '../lib/app-message'
import { useT } from '../composables/use-t'

destroyAll()
const success = ref(false)
const orderId = ref('')
try {
  const raw = sessionStorage.getItem('form-result')
  if (raw) {
    const data = JSON.parse(raw) as { status?: string; orderId?: string }
    success.value = data.status === 'success'
    orderId.value = data.orderId ?? ''
  }
} catch {
  success.value = false
}
sessionStorage.removeItem('form-result')

const { t: tt, locale } = useT()
/** 模板文案函数：读 locale.value 建立响应式依赖，切语言时重渲 */
function t(key: string, params?: Record<string, string | number>): string {
  void locale.value
  return tt(key, params)
}

const router = useRouter()

function go(path: string): void {
  void router.push(path)
}
</script>

<template>
  <div class="page result-page">
    <div class="result-wrap">
      <oas-result
        data-testid="form-result"
        :status="success ? 'success' : 'error'"
        :title="success ? t('result.success.title') : t('result.error.title')"
        :description="
          success ? t('result.success.desc', { orderId }) : t('result.error.desc')
        "
      >
        <div slot="extra" class="result-actions">
          <template v-if="success">
            <oas-button data-testid="result-view-order" type="primary" @click="go('/orders')">
              {{ t('result.viewOrder') }}
            </oas-button>
            <oas-button data-testid="result-reset" @click="go('/form')">
              {{ t('result.createAnother') }}
            </oas-button>
          </template>
          <template v-else>
            <oas-button data-testid="result-back-form" type="primary" @click="go('/form')">
              {{ t('result.backForm') }}
            </oas-button>
          </template>
        </div>
      </oas-result>
    </div>
  </div>
</template>

// templates/admin-pro/react/src/pages/result.tsx
// src/pages/result.tsx —— 表单结果页（成功/失败双态，sessionStorage 快照驱动）
// 1. 快照读取：useState 惰性初始化 + 模块级缓存，保证 StrictMode 双渲染的两次惰性初始化
//    取同一份快照（首个实例已 removeItem，否则第二次初始化会读到 null 而误判失败态）；
//    缓存于卸载清理时复位，再次进入页面取新快照；快照在挂载时固化，重渲染只换文案
// 2. 进入结果页时 destroyAll 清空遗留消息
import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router'
import { destroyAll } from '@oas-ui/ui/feedback/message'
import { useT } from '../hooks/use-t'

interface FormResult {
  success: boolean
  orderId: string
}

// StrictMode 双渲染共用快照
let cachedResult: FormResult | null = null

function consumeFormResult(): FormResult {
  if (cachedResult) return cachedResult
  let success = false
  let orderId = ''
  try {
    const raw = sessionStorage.getItem('form-result')
    if (raw) {
      const data = JSON.parse(raw) as { status?: string; orderId?: string }
      success = data.status === 'success'
      orderId = data.orderId ?? ''
    }
  } catch {
    success = false
  }
  sessionStorage.removeItem('form-result')
  cachedResult = { success, orderId }
  return cachedResult
}

export default function ResultPage() {
  const { t } = useT()
  const navigate = useNavigate()
  const [result] = useState(consumeFormResult)

  useEffect(() => {
    destroyAll()
    return () => {
      cachedResult = null
    }
  }, [])

  return (
    <div className="page result-page">
      <div className="result-wrap">
        {result.success ? (
          <oas-result
            data-testid="form-result"
            status="success"
            title={t('result.success.title')}
            description={t('result.success.desc', { orderId: result.orderId })}
          >
            <div slot="extra" className="result-actions">
              <oas-button
                data-testid="result-view-order"
                type="primary"
                onClick={() => navigate('/orders')}
              >
                {t('result.viewOrder')}
              </oas-button>
              <oas-button data-testid="result-reset" onClick={() => navigate('/form')}>
                {t('result.createAnother')}
              </oas-button>
            </div>
          </oas-result>
        ) : (
          <oas-result
            data-testid="form-result"
            status="error"
            title={t('result.error.title')}
            description={t('result.error.desc')}
          >
            <div slot="extra" className="result-actions">
              <oas-button
                data-testid="result-back-form"
                type="primary"
                onClick={() => navigate('/form')}
              >
                {t('result.backForm')}
              </oas-button>
            </div>
          </oas-result>
        )}
      </div>
    </div>
  )
}
