// templates/admin-pro/vue/src/pages/users-table.vue
<script setup lang="ts">
// src/pages/users-table.vue —— 用户列表表格（oas-table + 行编辑按钮 + 行点击）
// 拆分边界参照 products-table.vue 先例
// 1. columns 含 render 函数（action 列返回真实 DOM 节点），JSON 序列化会丢函数，故走 property
//    renderTable 里 table.columns = COLUMNS(...) 的时机
// 3. 行编辑按钮：原生 click 是 composed 事件，能冒泡出 oas-table shadow，直绑 oas-table 的
//    @click（Vue 直绑元素本身，无 react 根委托问题），composedPath 匹配 .user-row-edit
// 5. loading/pagination 布尔 attribute 存在性语义（:loading="loading ? '' : null"，第 2 条）；
import { computed, ref } from 'vue'
import type { TableColumn } from '@oas-ui/ui/data/table'
import type { RoleRow } from '../data/system'
import { readPageSize } from '../settings-init'
import { useT } from '../composables/use-t'

/** 表格展示行（父组件 toDisplay 已把角色名/状态标签本地化） */
export interface UserDisplayRow {
  id: number
  name: string
  email: string
  role: string
  status: string
  created: string
}

const props = defineProps<{
  rows: UserDisplayRow[]
  /** 角色列表（role 列 filters 来源，vanilla COLUMNS(roleFilters)） */
  roles: RoleRow[]
  /** 筛选结果为空：表格隐藏（empty-overlay 由父组件显示） */
  empty: boolean
  loading: boolean
}>()
const emit = defineEmits<{
  'edit-row': [id: number]
  'row-click': [id: number]
}>()

const { t: tt, locale } = useT()

const tableRef = ref<HTMLElement | null>(null)

const pageSize = Number(readPageSize()) || 5

function cellAction(row: UserDisplayRow): HTMLElement {
  const edit = document.createElement('oas-button')
  edit.className = 'user-row-edit'
  edit.setAttribute('data-testid', 'user-row-edit')
  edit.setAttribute('data-id', String(row.id))
  edit.setAttribute('size', 'small')
  edit.setAttribute('icon', 'edit')
  edit.setAttribute('aria-label', tt('common.edit'))
  return edit
}

const columns = computed<TableColumn[]>(() => {
  void locale.value
  return [
    { key: 'id', title: 'ID', width: '60px' },
    { key: 'name', title: tt('users.name') },
    { key: 'email', title: tt('users.email') },
    {
      key: 'role',
      title: tt('users.role'),
      filterable: true,
      filters: props.roles.map((r) => ({ label: r.name, value: r.name })),
    },
    {
      key: 'status',
      title: tt('users.status'),
      filterable: true,
      filters: [
        { label: tt('users.status.active'), value: tt('users.status.active') },
        { label: tt('users.status.disabled'), value: tt('users.status.disabled') },
      ],
    },
    { key: 'created', title: tt('users.created'), sortable: true },
    {
      key: 'action',
      title: tt('users.th.action'),
      width: '80px',
      render: (r) => cellAction(r as unknown as UserDisplayRow),
    },
  ]
})
// data 走 JSON 字符串通道
const rowsJson = computed(() => JSON.stringify(props.rows))

function onTableClick(e: MouseEvent): void {
  const btn = e
    .composedPath()
    .find((n): n is HTMLElement => n instanceof HTMLElement && n.matches('.user-row-edit'))
  if (!btn) return
  const id = Number(btn.getAttribute('data-id'))
  if (id) emit('edit-row', id)
}

function onRowClick(e: Event): void {
  const row = (e as CustomEvent<{ row: Record<string, unknown> }>).detail.row
  const id = Number(row.id)
  if (id) emit('row-click', id)
}

function resetPage(): void {
  tableRef.value?.setAttribute('current', '1')
}
function clearFilterValues(): void {
  tableRef.value?.removeAttribute('filter-values')
}
defineExpose({ resetPage, clearFilterValues })
</script>

<template>
  <oas-table
    ref="tableRef"
    data-testid="users-table"
    row-key="id"
    pagination
    :page-size="pageSize"
    :class="{ 'table-hidden': empty }"
    :columns="columns"
    :data="rowsJson"
    :loading="loading ? '' : null"
    @click="onTableClick"
    @oas-row-click="onRowClick"
  />
</template>

// templates/admin-pro/react/src/pages/users-table.tsx
// src/pages/users-table.tsx —— 用户列表（oas-table + 空态覆盖层 + 行事件委托）
// 1. columns 含 render 函数（返回真实 DOM 节点），JSON 序列化会丢函数，故走 property 通道
//   （oas-table 的 columns setter 双通道均支持，例外）；columns 用 useMemo
//    角色筛选选项来自 roles，文案来自 t）
// 2. 行事件：oas-row-click 自定义事件走 useOasEvent编辑按钮的原生
//    click 是 composed 事件，能冒泡出 oas-table shadow 到 React 根委托（oas-table 不在
//    drawer/modal 例外之列），故用容器 onClick + composedPath 匹配 .user-row-edit
//    prop 派生（is-empty/table-hidden/hidden 三处同一事实来源）
import { useMemo } from 'react'
import type { TableColumn } from '@oas-ui/ui/data/table'
import type { UserRow, UserStatus } from '../data/users'
import type { RoleRow } from '../data/system'
import { useOasEvent } from '../hooks/use-oas-event'
import { useT } from '../hooks/use-t'

export interface UsersTableProps {
  /** 父组件持有 ref：搜索/清筛选时 setAttribute('current','1')、refresh 时切 loading（vanilla 同款） */
  tableRef: React.RefObject<HTMLElement | null>
  /** 展示行 JSON（toDisplay 后的数据，vanilla setAttribute('data', JSON) 同通道） */
  dataJson: string
  roles: RoleRow[]
  /** 关键字过滤结果为空：表格隐藏 + 空态覆盖层显示 */
  empty: boolean
  pageSize: number
  onRowOpen: (id: number) => void
  onEditRow: (id: number) => void
  onClearFilters: () => void
}

type TFunc = (key: string, params?: Record<string, string | number>) => string

function statusLabel(status: UserStatus, t: TFunc): string {
  return t(`users.status.${status}`)
}

/** vanilla cellAction：行内编辑按钮（class/data-testid/data-id 逐字对齐） */
function cellAction(row: UserRow, t: TFunc): HTMLElement {
  const edit = document.createElement('oas-button')
  edit.className = 'user-row-edit'
  edit.setAttribute('data-testid', 'user-row-edit')
  edit.setAttribute('data-id', String(row.id))
  edit.setAttribute('size', 'small')
  edit.setAttribute('icon', 'edit')
  edit.setAttribute('aria-label', t('common.edit'))
  return edit
}

/** vanilla COLUMNS：role/status 可过滤，created 可排序，action 列 render 走富内容挂载 */
function buildColumns(
  t: TFunc,
  roleFilters: Array<{ label: string; value: string }>,
): TableColumn[] {
  return [
    { key: 'id', title: 'ID', width: '60px' },
    { key: 'name', title: t('users.name') },
    { key: 'email', title: t('users.email') },
    { key: 'role', title: t('users.role'), filterable: true, filters: roleFilters },
    {
      key: 'status',
      title: t('users.status'),
      filterable: true,
      filters: [
        { label: statusLabel('active', t), value: statusLabel('active', t) },
        { label: statusLabel('disabled', t), value: statusLabel('disabled', t) },
      ],
    },
    { key: 'created', title: t('users.created'), sortable: true },
    {
      key: 'action',
      title: t('users.th.action'),
      width: '80px',
      render: (r) => cellAction(r as unknown as UserRow, t),
    },
  ]
}

export function UsersTable({
  tableRef,
  dataJson,
  roles,
  empty,
  pageSize,
  onRowOpen,
  onEditRow,
  onClearFilters,
}: UsersTableProps) {
  const { t } = useT()
  const columns = useMemo<TableColumn[]>(
    () =>
      buildColumns(
        t,
        roles.map((r) => ({ label: r.name, value: r.name })),
      ),
    [t, roles],
  )

  useOasEvent<{ row: Record<string, unknown> }>(tableRef, 'oas-row-click', (detail) => {
    const id = Number(detail.row.id)
    if (Number.isFinite(id)) onRowOpen(id)
  })

  const onWrapClick = (e: React.MouseEvent) => {
    const btn = e.nativeEvent
      .composedPath()
      .find((n): n is HTMLElement => n instanceof HTMLElement && n.matches('.user-row-edit'))
    if (!btn) return
    const id = Number(btn.getAttribute('data-id'))
    if (id) onEditRow(id)
  }

  return (
    <div className={`table-wrap${empty ? ' is-empty' : ''}`} id="table-wrap" onClick={onWrapClick}>
      <oas-table
        ref={tableRef}
        data-testid="users-table"
        row-key="id"
        className={empty ? 'table-hidden' : undefined}
        columns={columns}
        data={dataJson}
        pagination
        page-size={pageSize}
      />
      <div className="empty-overlay" id="empty-overlay" hidden={!empty}>
        <oas-empty description={t('users.empty')} />
        <oas-button id="clear-filters" type="primary" onClick={onClearFilters}>
          {t('common.clearFilter')}
        </oas-button>
      </div>
    </div>
  )
}
