// templates/admin-pro/svelte/src/pages/dict-item-modal.svelte
<script lang="ts">
  // src/pages/dict-item-modal.svelte —— 字典键值弹窗（新增/编辑双态，表单事件自包含）
  // 1. visible 由父组件 open 单一事实来源驱动；组件侧关闭（遮罩/Esc/✕）经 oas-close 回写
  // 2. open 边沿 $effect 逐字段 setAttribute 回填（编辑态带出当前值，sort 数字转字符串）
  // 3. 取消/保存按钮为 oas-button，Svelte 原生直绑 onclick（不走根委托，panel 内亦可达）；
  //    保存经 shadowRoot 内原生 form 的 requestSubmit 触发（跨 shadow 提交通道）
  import { useT } from '../lib/use-t.svelte'

  interface DictItemFormValues {
    label?: string
    value?: string
    sort?: string
  }

  interface Props {
    open: boolean
    /** 编辑目标（null → 新建态） */
    editing: { label?: string; value?: string; sort?: number } | null
    onClose: () => void
    onSubmit: (values: DictItemFormValues) => void
  }

  let { open, editing, onClose, onSubmit }: Props = $props()

  const { t, locale } = useT()
  /** 模板文案函数：读 $locale 建立响应式依赖，切语言时重算 */
  const tt = $derived.by(() => {
    void $locale
    return t
  })

  let modalEl: HTMLElement | null = $state(null)
  let formEl: HTMLElement | null = $state(null)
  let labelEl: HTMLElement | null = $state(null)
  let valueEl: HTMLElement | null = $state(null)
  let sortEl: HTMLElement | null = $state(null)

  /** vanilla RULES_ITEM：标签/键值必填 */
  const rules = $derived(
    JSON.stringify({
      label: [{ required: true, message: tt('dict.rule.label') }],
      value: [{ required: true, message: tt('dict.rule.value') }],
    }),
  )

  // open 边沿回填（编辑态带出当前值，sort 数字转字符串）
  $effect(() => {
    if (!open) return
    void editing
    labelEl?.setAttribute('value', editing?.label ?? '')
    valueEl?.setAttribute('value', editing?.value ?? '')
    sortEl?.setAttribute('value', editing ? String(editing.sort) : '')
  })

  /** 保存：触发 oas-form shadow 内原生 form 提交（跨 shadow requestSubmit 通道） */
  function onSave(): void {
    ;(formEl?.shadowRoot?.querySelector('form') as HTMLFormElement | null)?.requestSubmit()
  }

  /** oas-submit：校验通过后的值上行交给父组件编排 */
  function onFormSubmit(e: Event): void {
    const { values } = (e as CustomEvent<{ values: DictItemFormValues }>).detail
    onSubmit(values)
  }
</script>

<oas-modal
  bind:this={modalEl}
  data-testid="dict-item-modal"
  no-footer
  visible={open ? '' : null}
  onoas-close={onClose}
>
  <div class="modal-body">
    <h2 id="dict-item-title">
      {editing == null ? tt('dict.newItem') : tt('dict.editItem', { label: editing.label ?? '' })}
    </h2>
    <oas-form bind:this={formEl} {rules} onoas-submit={onFormSubmit}>
      <div class="dict-form-body">
        <div class="form-field">
          <label class="form-label" for="dif-label">
            {tt('dict.form.label')} <span class="req">*</span>
          </label>
          <oas-input
            bind:this={labelEl}
            id="dif-label"
            data-testid="dif-label"
            name="label"
            placeholder={tt('dict.placeholder.label')}
          ></oas-input>
        </div>
        <div class="form-field">
          <label class="form-label" for="dif-value">
            {tt('dict.form.value')} <span class="req">*</span>
          </label>
          <oas-input
            bind:this={valueEl}
            id="dif-value"
            data-testid="dif-value"
            name="value"
            placeholder={tt('dict.placeholder.value')}
          ></oas-input>
        </div>
        <div class="form-field">
          <label class="form-label" for="dif-sort">{tt('dict.form.sort')}</label>
          <oas-input-number
            bind:this={sortEl}
            id="dif-sort"
            data-testid="dif-sort"
            name="sort"
            min="0"
            placeholder="1"
          ></oas-input-number>
        </div>
        <div class="form-actions">
          <oas-space justify="end">
            <oas-button data-testid="dif-cancel" onclick={onClose}>{tt('common.cancel')}</oas-button>
            <oas-button data-testid="dif-save" type="primary" onclick={onSave}>
              {tt('common.save')}
            </oas-button>
          </oas-space>
        </div>
      </div>
    </oas-form>
  </div>
</oas-modal>

// templates/admin-pro/vue/src/pages/dict-item-modal.vue
<script setup lang="ts">
// src/pages/dict-item-modal.vue —— 字典键值新建/编辑弹窗（oas-modal + oas-form + 3 字段）
// 容器形态参照 category-form-modal.vue 先例
//    本模版在 open 边沿的 watch（flush: 'post'，等 DOM 就位）做同样的事（字段非受控）
//    监听 oas-close 上抛 close 回写（category-form-modal.vue 同款）
//    本模版上抛 submit(values)，父组件持有 editingItemId/selectedTypeId 做持久化
//    规则/按钮随 locale 自动重算
import { computed, ref, watch } from 'vue'
import { createDictItem, updateDictItem } from '../data/system'
import type { DictItem } from '../data/system'
import { useT } from '../composables/use-t'
import { appMessage } from '../lib/app-message'

interface FormValues {
  label: string
  value: string
  sort: string
}

const props = defineProps<{
  open: boolean
  /** 编辑态 id（null=新建）；与 editing 分离以对齐 vanilla 的 editingItemId 语义 */
  editingId: number | null
  editing: DictItem | null
  /** 所属字典类型 id（父组件保证非空才打开） */
  typeId: number | null
}>()
const emit = defineEmits<{
  close: []
  saved: []
}>()

const { t: tt, locale } = useT()
/** 模板文案函数：读 locale.value 建立响应式依赖，切语言时重渲 */
function t(key: string, params?: Record<string, string | number>): string {
  void locale.value
  return tt(key, params)
}

const formRef = ref<HTMLElement | null>(null)
const labelRef = ref<HTMLElement | null>(null)
const valueRef = ref<HTMLElement | null>(null)
const sortRef = ref<HTMLElement | null>(null)
const saving = ref(false)

const title = computed(() =>
  props.editing ? t('dict.editItem', { label: props.editing.label }) : t('dict.newItem'),
)

const rules = computed(() =>
  JSON.stringify({
    label: [{ required: true, message: t('dict.rule.label') }],
    value: [{ required: true, message: t('dict.rule.value') }],
  }),
)

watch(
  () => [props.open, props.editing],
  () => {
    if (!props.open) return
    const row = props.editing
    labelRef.value?.setAttribute('value', row?.label ?? '')
    valueRef.value?.setAttribute('value', row?.value ?? '')
    sortRef.value?.setAttribute('value', row ? String(row.sort) : '')
  },
  { flush: 'post' },
)

// 保存=触发 oas-form 内部原生 form 提交（跨 shadow，category-form-modal.vue 同款模式）
function onSave(): void {
  const form = formRef.value?.shadowRoot?.querySelector('form') as HTMLFormElement | null
  form?.requestSubmit()
}

async function onSubmit(e: Event): Promise<void> {
  if (saving.value) return
  if (props.typeId == null) return
  saving.value = true
  try {
    const values = (e as CustomEvent<{ values: FormValues }>).detail.values
    const label = values.label?.trim()
    const value = values.value?.trim()
    if (!label || !value) return
    const sort = Number(values.sort) || 0
    if (props.editingId == null) {
      await createDictItem({ typeId: props.typeId, label, value, sort })
      appMessage.success(tt('common.created'))
    } else {
      const updated = await updateDictItem(props.editingId, { label, value, sort })
      if (!updated) appMessage.error(t('dict.notFoundItem'))
      else appMessage.success(tt('common.saved'))
    }
    emit('saved')
  } finally {
    saving.value = false
  }
}
</script>

<template>
  <oas-modal
    data-testid="dict-item-modal"
    no-footer
    :visible="open ? '' : null"
    @oas-close="emit('close')"
  >
    <div class="modal-body">
      <h2>{{ title }}</h2>
      <oas-form ref="formRef" :rules="rules" @oas-submit="void onSubmit($event)">
        <div class="dict-form-body">
          <div class="form-field">
            <label class="form-label">
              {{ t('dict.form.label') }}
              <span class="req">*</span>
            </label>
            <oas-input ref="labelRef" data-testid="dif-label" name="label" :placeholder="t('dict.placeholder.label')" />
          </div>
          <div class="form-field">
            <label class="form-label">
              {{ t('dict.form.value') }}
              <span class="req">*</span>
            </label>
            <oas-input ref="valueRef" data-testid="dif-value" name="value" :placeholder="t('dict.placeholder.value')" />
          </div>
          <div class="form-field">
            <label class="form-label">{{ t('dict.form.sort') }}</label>
            <oas-input-number ref="sortRef" data-testid="dif-sort" name="sort" min="0" placeholder="1" />
          </div>
          <div class="form-actions">
            <oas-space justify="end">
              <oas-button data-testid="dif-cancel" @click="emit('close')">
                {{ t('common.cancel') }}
              </oas-button>
              <oas-button data-testid="dif-save" type="primary" @click="onSave">
                {{ t('common.save') }}
              </oas-button>
            </oas-space>
          </div>
        </div>
      </oas-form>
    </div>
  </oas-modal>
</template>
