// templates/admin-pro/svelte/src/pages/logs-vlist.svelte
<script lang="ts">
  // src/pages/logs-vlist.svelte —— 日志虚拟列表（oas-virtual-list 封装：行模板 + items 注入 + 行回填）
  // 对齐 react 版 logs.tsx 虚拟列表段 / vue 版 logs-vlist.vue：
  // 1. 行模板：oas-virtual-list 读取子节点 template[slot="item"]（shadow 容器约定）；
  //    模板含原生 <style> 隔离样式与 data-col 占位单元格，oas-item 事件里逐列回填
  // 2. items 走 property 通道（bind:this + $effect，数据变化与语言切换都重建行）；
  //    本模版数据变化回顶（vanilla applyFilter→resetScroll 同款）、语言切换保持滚动位置
  // 3. buffer 必须走 setAttribute 通道：oas-virtual-list 原型上的 buffer() 是方法，
  //    property 通道赋 number 会把方法遮蔽成数据致 this.buffer is not a function（实测崩溃）
  import { onMount } from 'svelte'
  type LogEntry = import('../data/logs').LogEntry
  import { useT } from '../lib/use-t.svelte'
  import { formatTime, ITEM_HEIGHT, ITEM_TEMPLATE_HTML, LEVEL_TAG, levelLabel } from './logs-shared'

  interface Props {
    rows: LogEntry[]
    /** 筛选后为空（列表隐藏，动态 overlay 覆盖提示显示用） */
    empty: boolean
    /** 当前过滤关键词（命中列 oas-highlight 高亮），空串不高亮 */
    keyword: string
    onOpenDetail: (entry: LogEntry) => void
    /** oas-scroll 透传（驱动锚点 active 联动） */
    onScroll: () => void
  }

  let { rows, empty, keyword, onOpenDetail, onScroll }: Props = $props()

  const { t, locale } = useT()

  let vlistEl: HTMLElement | null = $state(null)

  // items 走 property 通道；随 rows/locale 变化重新注入（组件库 setter 内部 slice + update）
  $effect(() => {
    void $locale
    if (vlistEl) (vlistEl as HTMLElement & { items: LogEntry[] }).items = rows
  })

  // 数据变化回顶；语言切换不回顶（locale 变化只重建行）
  $effect(() => {
    if (rows) resetScroll()
  })

  onMount(() => {
    if (!vlistEl) return
    // buffer 走 attribute 通道（理由见文件头注释 3）
    vlistEl.setAttribute('buffer', '8')
    // 行模板：与 react 版 dangerouslySetInnerHTML / vue 版 createElement+innerHTML 同款注入
    const template = document.createElement('template')
    template.setAttribute('slot', 'item')
    template.innerHTML = ITEM_TEMPLATE_HTML
    vlistEl.appendChild(template)
  })

  /** oas-item：行节点回收复用时逐列回填，并直绑行 click 打开详情 */
  function onItem(e: Event): void {
    const { item, element } = (e as CustomEvent<{ item: LogEntry; element: HTMLElement }>).detail
    const row = item
    element.querySelector<HTMLElement>('[data-col="time"]')!.textContent = formatTime(row.time)
    const tag = element.querySelector('oas-tag')!
    tag.textContent = levelLabel(row.level, t)
    tag.setAttribute('type', LEVEL_TAG[row.level])
    // 关键词命中高亮（operator/action/IP 与过滤字段一致）：oas-highlight 属性通道，无注入风险
    const kw = keyword.trim()
    const paint = (col: string, text: string) => {
      const cell = element.querySelector<HTMLElement>(`[data-col="${col}"]`)!
      cell.setAttribute('text', text)
      if (kw) cell.setAttribute('highlight', kw)
      else cell.removeAttribute('highlight')
    }
    paint('operator', row.operator)
    paint('action', row.action)
    paint('ip', row.IP)
    element.addEventListener('click', () => onOpenDetail(row))
  }

  /** 滚动到指定行号（锚点点击定位） */
  export function scrollToIndex(index: number): void {
    const viewport = (vlistEl as unknown as { shadowRoot: ShadowRoot } | null)?.shadowRoot.querySelector<HTMLElement>(
      '.viewport',
    )
    if (!viewport) return
    viewport.scrollTop = Math.max(0, index * ITEM_HEIGHT)
  }

  /** 数据变化回顶（vanilla applyFilter→resetScroll 同款） */
  export function resetScroll(): void {
    scrollToIndex(0)
  }

  /** 锚点联动取数：滚动位置换算当前可见行 index（父组件据此反查日期 → anchor active） */
  export function currentScrollIndex(): number {
    const viewport = (vlistEl as unknown as { shadowRoot: ShadowRoot } | null)?.shadowRoot.querySelector<HTMLElement>(
      '.viewport',
    )
    if (!viewport) return 0
    return Math.floor(viewport.scrollTop / ITEM_HEIGHT)
  }
</script>

<oas-virtual-list
  bind:this={vlistEl}
  data-testid="logs-list"
  id="logs-list"
  height="480"
  item-height={ITEM_HEIGHT}
  hidden={empty}
  onoas-item={onItem}
  onoas-scroll={onScroll}
></oas-virtual-list>

// templates/admin-pro/vue/src/pages/logs-vlist.vue
<script setup lang="ts">
// src/pages/logs-vlist.vue —— 日志虚拟列表（oas-virtual-list 封装：行模板 + items 注入 + 行回填）
// scrollToIndex/oas-item 段（
// 拆分边界：logs.vue 主文件 ≤400 行纪律，锚点联动留在父组件）
// 1. 行模板：oas-virtual-list 读取子节点 template[slot="item"]（shadow 容器约定）；Vue 编译器
//    watch([rows, locale], flush:'post') 里走同一 property 通道（数据变化与语言切换都重建行）
//    （语言切换保持滚动位置）；本模版数据 watch 回顶、语言 watch 不回顶，语义一一对应
import { onMounted, ref, watch } from 'vue'
import type { LogEntry, LogLevel } from '../data/logs'
import { useT } from '../composables/use-t'

const props = defineProps<{
  rows: LogEntry[]
  /** 筛选后为空（列表隐藏，动态 overlay 覆盖提示显示用） */
  empty: boolean
  /** 当前过滤关键词（命中列 oas-highlight 高亮），空串不高亮 */
  keyword: string
}>()
const emit = defineEmits<{
  'open-detail': [entry: LogEntry]
  /** oas-scroll 透传给父组件做锚点 active 联动 */
  scroll: []
}>()

const { t: tt, locale } = useT()

const ITEM_HEIGHT = 44

const LEVEL_TAG: Record<LogLevel, string> = {
  info: 'default',
  warn: 'warning',
  error: 'danger',
}

function levelLabel(level: LogLevel): string {
  return tt(`logs.level.${level}`)
}

function formatTime(time: string): string {
  const d = new Date(time)
  const pad = (n: number) => String(n).padStart(2, '0')
  return `${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`
}

const vlistRef = ref<HTMLElement | null>(null)

watch(
  [() => props.rows, locale, vlistRef],
  () => {
    const vlist = vlistRef.value as (HTMLElement & { items?: LogEntry[] }) | null
    if (vlist) vlist.items = props.rows
  },
  { flush: 'post' },
)

watch(
  () => props.rows,
  () => {
    resetScroll()
  },
  { flush: 'post' },
)

// buffer 同为命令式 setAttribute：组件原型有 buffer() 方法（读 attribute 的访问器），Vue 对
// 「el 上存在同名 property（含原型方法）」的 attribute 走 property 赋值，会遮蔽方法导致
// this.buffer is not a function（item-height 等 kebab 属性不受影响）
onMounted(() => {
  const vlist = vlistRef.value
  if (!vlist) return
  vlist.setAttribute('buffer', '8')
  const template = document.createElement('template')
  template.setAttribute('slot', 'item')
  template.innerHTML = `
    <style>
      .logs-cell {
        font-size: var(--oas-font-size-sm);
        color: var(--oas-color-text-primary);
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
      }
      .logs-cell.mono {
        font-family: var(--app-mono);
      }
      .logs-cell.logs-time {
        color: var(--oas-color-text-secondary);
      }
      @media (max-width: 768px) {
        .logs-cell {
          font-size: var(--oas-font-size-xs);
        }
      }
    </style>
    <span class="logs-cell logs-time mono" data-col="time"></span>
    <span class="logs-cell logs-level" data-col="level"><oas-tag size="small"></oas-tag></span>
    <span class="logs-cell logs-operator"><oas-highlight data-col="operator"></oas-highlight></span>
    <span class="logs-cell logs-action"><oas-highlight data-col="action"></oas-highlight></span>
    <span class="logs-cell logs-ip mono"><oas-highlight data-col="ip"></oas-highlight></span>`
  vlist.appendChild(template)
})

function onItem(e: Event): void {
  const { item, element } = (e as CustomEvent<{ item: LogEntry; element: HTMLElement }>).detail
  const row = item
  element.querySelector<HTMLElement>('[data-col="time"]')!.textContent = formatTime(row.time)
  const tag = element.querySelector('oas-tag')!
  tag.textContent = levelLabel(row.level)
  tag.setAttribute('type', LEVEL_TAG[row.level])
  // 关键词命中高亮（operator/action/IP 与过滤字段一致）：oas-highlight 属性通道，无注入风险
  const kw = props.keyword.trim()
  const paint = (col: string, text: string) => {
    const cell = element.querySelector<HTMLElement>(`[data-col="${col}"]`)!
    cell.setAttribute('text', text)
    if (kw) cell.setAttribute('highlight', kw)
    else cell.removeAttribute('highlight')
  }
  paint('operator', row.operator)
  paint('action', row.action)
  paint('ip', row.IP)
  element.addEventListener('click', () => emit('open-detail', row))
}

function scrollToIndex(index: number): void {
  const vlist = vlistRef.value as (HTMLElement & { shadowRoot: ShadowRoot }) | null
  const viewport = vlist?.shadowRoot.querySelector<HTMLElement>('.viewport')
  if (!viewport) return
  viewport.scrollTop = Math.max(0, index * ITEM_HEIGHT)
}

function resetScroll(): void {
  scrollToIndex(0)
}

// 锚点联动取数：滚动位置换算当前可见行 index（父组件据此反查日期 → anchor active）
function currentScrollIndex(): number {
  const vlist = vlistRef.value as (HTMLElement & { shadowRoot: ShadowRoot }) | null
  const viewport = vlist?.shadowRoot.querySelector<HTMLElement>('.viewport')
  if (!viewport) return 0
  return Math.floor(viewport.scrollTop / ITEM_HEIGHT)
}

defineExpose({ scrollToIndex, resetScroll, currentScrollIndex })
</script>

<template>
  <oas-virtual-list
    ref="vlistRef"
    data-testid="logs-list"
    id="logs-list"
    height="480"
    :item-height="ITEM_HEIGHT"
    :hidden="empty"
    @oas-item="onItem"
    @oas-scroll="emit('scroll')"
  />
</template>
