// templates/admin-pro/react/src/pages/order-detail.tsx
// src/pages/order-detail.tsx —— 订单详情页（步骤条 + 描述列表 + 时间线 + 状态流转）
//    sessionStorage('order-detail-id') 后经 href="#/order-detail" 跳转（URL 不带 id 参数，
//    hidden+parent 路由仅用于面包屑）；本模版 orders-drawer 以同键同时机写入 + navigate
//    驱动全部动态区（标题/标签/步骤/描述/时间线/操作），flow 成功后 setOrder(updated) 即最新
// 3. 事件绑定：操作按钮位于 oas-card 内容区（非 drawer/modal panel），原生 click 用 React
//    双模式均正确，product-edit 同款）
//    重渲染，步骤/描述/时间线/操作随 locale 自动重算
//    load 语义一致）
import { useEffect, useState } from 'react'
import { Link } from 'react-router'
import { getOrder, updateOrderStatus } from '../data/orders'
import type { OrderRow, OrderStatus } from '../data/orders'
import { useT } from '../hooks/use-t'
import { appMessage } from '../lib/app-message'
import { statusLabel, tagTypeFor } from './orders-table'

type TFunc = (key: string, params?: Record<string, string | number>) => string

/** vanilla FLOW_STEPS / FLOW_TO：流转顺序与下一步映射 */
const FLOW_STEPS: OrderStatus[] = ['pending', 'paid', 'shipping', 'done']

const FLOW_TO: Partial<Record<OrderStatus, OrderStatus>> = {
  pending: 'paid',
  paid: 'shipping',
  shipping: 'done',
}

function flowFor(status: OrderStatus, t: TFunc): { label: string; to: OrderStatus } | undefined {
  const to = FLOW_TO[status]
  return to ? { label: t(`orders.flow.${status}`), to } : undefined
}

/** vanilla formatMoney（详情页版本：两位小数、无空格——与列表页金额格式刻意不同，逐字对齐） */
function formatMoney(n: number): string {
  return `¥${n.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
}

/** vanilla addDays：yyyy-MM-dd 加 n 天 */
function addDays(dateStr: string, n: number): string {
  const [y, m, d] = dateStr.split('-').map(Number)
  const date = new Date(y, m - 1, d)
  date.setDate(date.getDate() + n)
  const mm = String(date.getMonth() + 1).padStart(2, '0')
  const dd = String(date.getDate()).padStart(2, '0')
  return `${date.getFullYear()}-${mm}-${dd}`
}

interface TimelineNode {
  time: string
  title: string
  color?: string
}

/** vanilla buildTimeline：创建 → 已按状态推进的各节点（取消态只有取消节点） */
function buildTimeline(order: OrderRow, t: TFunc): TimelineNode[] {
  const nodes: TimelineNode[] = [{ time: order.created, title: t('orderDetail.timeline.created') }]
  if (order.status === 'cancelled') {
    nodes.push({
      time: addDays(order.created, 1),
      title: statusLabel('cancelled', t),
      color: 'red',
    })
    return nodes
  }
  const idx = FLOW_STEPS.indexOf(order.status)
  if (idx >= 1) nodes.push({ time: addDays(order.created, 1), title: statusLabel('paid', t) })
  if (idx >= 2) nodes.push({ time: addDays(order.created, 2), title: statusLabel('shipping', t) })
  if (idx >= 3)
    nodes.push({ time: addDays(order.created, 3), title: statusLabel('done', t), color: 'green' })
  return nodes
}

export default function OrderDetailPage() {
  const { t } = useT()
  const [id] = useState(() => sessionStorage.getItem('order-detail-id') ?? '')
  const [order, setOrder] = useState<OrderRow | null>(null)
  const [missing, setMissing] = useState(false)

  useEffect(() => {
    let cancelled = false
    void (async () => {
      const row = await getOrder(id)
      if (cancelled) return
      if (!row) setMissing(true)
      else setOrder(row)
    })()
    return () => {
      cancelled = true
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [id])

  const onAction = async (e: React.MouseEvent) => {
    if (!order) return
    const button = e.currentTarget as HTMLElement
    const target = button.dataset.target as OrderStatus | undefined
    if (!target) return
    button.setAttribute('loading', '')
    const updated = await updateOrderStatus(order.id, target)
    button.removeAttribute('loading')
    if (!updated) {
      appMessage.error(t('orders.notFound'))
      return
    }
    appMessage.success(t('orders.flowApplied', { action: button.textContent }))
    setOrder(updated)
  }

  const flow = order ? flowFor(order.status, t) : undefined
  const steps =
    order && order.status !== 'cancelled'
      ? FLOW_STEPS.map((s) => ({ title: statusLabel(s, t) }))
      : null
  const timeline = order ? buildTimeline(order, t) : []

  return (
    <div className="page order-detail-page">
      <oas-page-header
        data-testid="order-page-header"
        className="order-detail-ph"
        title={order ? order.id : t('nav.orderDetail')}
      >
        <div slot="extra" className="ph-extra">
          <Link className="link-btn" to="/orders" data-testid="order-back">
            {t('orderDetail.backList')}
          </Link>
          <oas-tag
            data-testid="order-status-tag"
            type={
              order
                ? tagTypeFor(order.status) === 'purple'
                  ? undefined
                  : tagTypeFor(order.status)
                : undefined
            }
            color={order && tagTypeFor(order.status) === 'purple' ? 'purple' : undefined}
          >
            {order ? statusLabel(order.status, t) : t('orderDetail.loading')}
          </oas-tag>
        </div>
      </oas-page-header>
      <div id="order-detail-card" hidden={missing || undefined}>
        <oas-card>
          <div id="order-detail-steps" hidden={!steps || undefined}>
            {steps && order && (
              <oas-steps
                className="order-steps"
                steps={JSON.stringify(steps)}
                current={FLOW_STEPS.indexOf(order.status)}
              />
            )}
          </div>
          <oas-descriptions data-testid="order-detail-basic" id="order-detail-basic" column="2">
            <oas-descriptions-item label={t('orders.th.customer')}>
              {order?.customer ?? ''}
            </oas-descriptions-item>
            <oas-descriptions-item label={t('orders.th.amount')}>
              <span className="mono">{order ? formatMoney(order.amount) : ''}</span>
            </oas-descriptions-item>
            <oas-descriptions-item label={t('form.label.phone')}>
              <span className="mono">{order?.phone ?? '-'}</span>
            </oas-descriptions-item>
            <oas-descriptions-item label={t('form.summary.urgent')}>
              {order
                ? order.urgent
                  ? t('form.label.urgent')
                  : t('form.summary.normalDelivery')
                : ''}
            </oas-descriptions-item>
            <oas-descriptions-item label={t('orders.th.created')}>
              <span className="mono">{order?.created ?? ''}</span>
            </oas-descriptions-item>
            <oas-descriptions-item label={t('orders.th.items')}>
              {order?.items.map((it, i) => (
                <oas-tag key={`${it}-${i}`}>{it}</oas-tag>
              ))}
            </oas-descriptions-item>
          </oas-descriptions>
          <div className="order-timeline-head">{t('orderDetail.timelineTitle')}</div>
          <div id="order-detail-timeline-wrap">
            <oas-timeline data-testid="order-detail-timeline">
              {timeline.map((n, i) => (
                <oas-timeline-item key={`${n.time}-${i}`} time={n.time} color={n.color}>
                  {n.title}
                </oas-timeline-item>
              ))}
            </oas-timeline>
          </div>
          <div className="order-detail-foot">
            <oas-button
              data-testid="order-detail-action"
              type="primary"
              hidden={!flow || undefined}
              data-target={flow?.to}
              onClick={(e) => void onAction(e)}
            >
              {flow?.label ?? ''}
            </oas-button>
            <div className="order-detail-note" id="order-detail-note" hidden={!!flow || undefined}>
              {order
                ? order.status === 'done'
                  ? t('orders.noteDone')
                  : t('orders.noteCancelled')
                : ''}
            </div>
          </div>
        </oas-card>
      </div>
      <div id="order-detail-missing" hidden={!missing || undefined}>
        {missing && <oas-empty description={t('orderDetail.missing')} />}
      </div>
    </div>
  )
}

// templates/admin-pro/vue/src/pages/order-detail.vue
<script setup lang="ts">
// src/pages/order-detail.vue —— 订单详情页（步骤条 + 描述列表 + 时间线 + 流程操作）
//    本模版改读 route.query.id（orders-drawer.vue 的 RouterLink 携带）——可观察行为一致
//    （目标页拿到同一订单号），且 URL 可收藏/刷新后恢复，sessionStorage 通道不再使用
//    renderAction 逐节点写）；本模版声明式——order ref 就绪后各区块由 computed 派生，
//    addEventListener 同款）；按钮 loading 态用 :loading 存在性语义对齐 setAttribute('loading')
//    product-edit.vue 先例）
//    步骤/描述/时间线/操作随 locale 自动重算（加载中/缺失态同样响应式）
import { computed, onMounted, onUnmounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { getOrder, updateOrderStatus } from '../data/orders'
import type { OrderRow, OrderStatus } from '../data/orders'
import { useT } from '../composables/use-t'
import { appMessage } from '../lib/app-message'

const FLOW_STEPS: OrderStatus[] = ['pending', 'paid', 'shipping', 'done']
const FLOW_TO: Partial<Record<OrderStatus, OrderStatus>> = {
  pending: 'paid',
  paid: 'shipping',
  shipping: 'done',
}
const STATUS_TAG: Record<OrderStatus, string> = {
  pending: 'warning',
  paid: 'primary',
  shipping: 'purple',
  done: 'success',
  cancelled: 'danger',
}

const { t: tt, locale } = useT()
/** 模板文案函数：读 locale.value 建立响应式依赖，切语言时重渲 */
function t(key: string, params?: Record<string, string | number>): string {
  void locale.value
  return tt(key, params)
}

function statusLabel(status: OrderStatus): string {
  return t(`orders.status.${status}`)
}

const route = useRoute()

const id = typeof route.query.id === 'string' ? route.query.id : ''

const order = ref<OrderRow | null>(null)
const missing = ref(false)
const flowing = ref(false)

// 异步拉取存活标记：卸载后丢弃迟到的 Promise 结果（product-edit.vue 同款语义）
let alive = true
onUnmounted(() => {
  alive = false
})

onMounted(async () => {
  const row = await getOrder(id)
  if (!alive) return
  if (!row) {
    missing.value = true
    return
  }
  order.value = row
})

function formatMoney(n: number): string {
  return `¥${n.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
}

function addDays(dateStr: string, n: number): string {
  const [y, m, d] = dateStr.split('-').map(Number)
  const date = new Date(y, m - 1, d)
  date.setDate(date.getDate() + n)
  const mm = String(date.getMonth() + 1).padStart(2, '0')
  const dd = String(date.getDate()).padStart(2, '0')
  return `${date.getFullYear()}-${mm}-${dd}`
}

const title = computed(() => (order.value ? order.value.id : t('nav.orderDetail')))
const statusTag = computed(() => {
  if (!order.value) return { label: t('orderDetail.loading'), type: 'default' as const }
  return { label: statusLabel(order.value.status), type: STATUS_TAG[order.value.status] }
})

const steps = computed(() => FLOW_STEPS.map((s) => ({ title: statusLabel(s) })))
const stepsCurrent = computed(() => (order.value ? FLOW_STEPS.indexOf(order.value.status) : -1))
const stepsVisible = computed(
  () => !!order.value && order.value.status !== 'cancelled' && stepsCurrent.value >= 0,
)

const timeline = computed(() => {
  const o = order.value
  if (!o) return []
  const nodes: Array<{ time: string; title: string; color?: string }> = [
    { time: o.created, title: t('orderDetail.timeline.created') },
  ]
  if (o.status === 'cancelled') {
    nodes.push({ time: addDays(o.created, 1), title: statusLabel('cancelled'), color: 'red' })
    return nodes
  }
  const idx = FLOW_STEPS.indexOf(o.status)
  if (idx >= 1) nodes.push({ time: addDays(o.created, 1), title: statusLabel('paid') })
  if (idx >= 2) nodes.push({ time: addDays(o.created, 2), title: statusLabel('shipping') })
  if (idx >= 3)
    nodes.push({ time: addDays(o.created, 3), title: statusLabel('done'), color: 'green' })
  return nodes
})

const flowTo = computed(() => (order.value ? FLOW_TO[order.value.status] ?? null : null))
const note = computed(() => {
  if (!order.value || flowTo.value) return ''
  return order.value.status === 'done' ? t('orders.noteDone') : t('orders.noteCancelled')
})

async function onAction(): Promise<void> {
  if (!order.value || !flowTo.value) return
  const actionLabel = t(`orders.flow.${order.value.status}`)
  flowing.value = true
  const updated = await updateOrderStatus(order.value.id, flowTo.value)
  flowing.value = false
  if (!updated) {
    appMessage.error(tt('orders.notFound'))
    return
  }
  appMessage.success(tt('orders.flowApplied', { action: actionLabel }))
  order.value = updated
}
</script>

<template>
  <div class="page order-detail-page">
    <oas-page-header data-testid="order-page-header" class="order-detail-ph" :title="title">
      <div slot="extra" class="ph-extra">
        <RouterLink class="link-btn" to="/orders" data-testid="order-back">
          {{ t('orderDetail.backList') }}
        </RouterLink>
        <oas-tag
          data-testid="order-status-tag"
          :type="statusTag.type === 'purple' ? null : statusTag.type"
          :color="statusTag.type === 'purple' ? 'purple' : null"
        >
          {{ statusTag.label }}
        </oas-tag>
      </div>
    </oas-page-header>
    <div v-if="order" id="order-detail-card">
      <oas-card>
        <oas-steps
          v-if="stepsVisible"
          class="order-steps"
          id="order-detail-steps"
          :steps="JSON.stringify(steps)"
          :current="stepsCurrent"
        />
        <oas-descriptions data-testid="order-detail-basic" id="order-detail-basic" column="2">
          <oas-descriptions-item :label="t('orders.th.customer')">
            <span>{{ order.customer }}</span>
          </oas-descriptions-item>
          <oas-descriptions-item :label="t('orders.th.amount')">
            <span class="mono">{{ formatMoney(order.amount) }}</span>
          </oas-descriptions-item>
          <oas-descriptions-item :label="t('form.label.phone')">
            <span class="mono">{{ order.phone ?? '-' }}</span>
          </oas-descriptions-item>
          <oas-descriptions-item :label="t('form.summary.urgent')">
            <span>{{ order.urgent ? t('form.label.urgent') : t('form.summary.normalDelivery') }}</span>
          </oas-descriptions-item>
          <oas-descriptions-item :label="t('orders.th.created')">
            <span class="mono">{{ order.created }}</span>
          </oas-descriptions-item>
          <oas-descriptions-item :label="t('orders.th.items')">
            <span>
              <oas-tag v-for="it in order.items" :key="it">{{ it }}</oas-tag>
            </span>
          </oas-descriptions-item>
        </oas-descriptions>
        <div class="order-timeline-head">{{ t('orderDetail.timelineTitle') }}</div>
        <div id="order-detail-timeline-wrap">
          <oas-timeline data-testid="order-detail-timeline">
            <oas-timeline-item
              v-for="n in timeline"
              :key="`${n.time}-${n.title}`"
              :time="n.time"
              :color="n.color ?? null"
            >
              {{ n.title }}
            </oas-timeline-item>
          </oas-timeline>
        </div>
        <div class="order-detail-foot">
          <oas-button
            v-if="flowTo"
            data-testid="order-detail-action"
            type="primary"
            :loading="flowing ? '' : null"
            @click="void onAction()"
          >
            {{ t(`orders.flow.${order.status}`) }}
          </oas-button>
          <div v-if="!flowTo" class="order-detail-note" data-testid="order-detail-note">
            {{ note }}
          </div>
        </div>
      </oas-card>
    </div>
    <div v-if="missing" id="order-detail-missing">
      <oas-empty :description="t('orderDetail.missing')" />
    </div>
  </div>
</template>
