// templates/admin-pro/svelte/src/pages/product-edit.svelte
<script lang="ts">
  // src/pages/product-edit.svelte —— 商品编辑页（page 表单模式：oas-page-header + 表单）
  // 1. 编辑 id 从 sessionStorage 键 product-edit-id 读取（openForm page 分支写入，逐字一致）；
  //    分类/商品详情挂载后异步拉取，数据就绪边沿 $effect 命令式回填（字段非受控，
  //    与 vanilla 异步加载完成后的 setAttribute 同时机）：新建=分类就绪即填；
  //    编辑=分类与商品详情都就绪再填；编辑 id 查无商品时提示一次
  // 2. 事件绑定：pe-save/pe-cancel 按钮在 light DOM（非 drawer/modal panel），原生 click
  //    模板直绑 onclick；oas-submit 自定义事件 onoas-submit 直绑
  // 3. 返回列表：<a class="link-btn"> + onclick preventDefault 后走编程式导航（hash/history
  //    两模式均正确；href 保留可右键新开）
  import '../styles/pages/products.css'
  import { navigate } from '../router'
  import { listCategories } from '../data/categories'
  import type { CategoryRow } from '../data/categories'
  import { createProduct, getProduct, updateProduct } from '../data/products'
  import type { ProductRow } from '../data/products'
  import { appMessage } from '../lib/app-message'
  import { useT } from '../lib/use-t.svelte'

  function today(): string {
    return new Date().toISOString().slice(0, 10)
  }

  const { t, locale } = useT()
  /** 模板文案函数：读 $locale 建立响应式依赖，切语言时重渲 */
  const tt = $derived.by(() => {
    void $locale
    return t
  })

  const rawId = sessionStorage.getItem('product-edit-id')
  const id: number | null = rawId ? Number(rawId) : null

  let catOptions = $state<Array<{ label: string; value: string }>>([])
  let editing = $state<ProductRow | null>(null)
  let saving = $state(false)
  /** 商品详情是否已返回（新建模式立即就绪）；未返回前不回填、不误报 notFound */
  let productLoaded = $state(false)
  /** 编辑态查无商品的提示只发一次 */
  let notFoundNotified = false

  let formEl = $state<HTMLElement | null>(null)
  let nameEl = $state<HTMLElement | null>(null)
  let catEl = $state<HTMLElement | null>(null)
  let priceEl = $state<HTMLElement | null>(null)
  let stockEl = $state<HTMLElement | null>(null)
  let dateEl = $state<HTMLElement | null>(null)

  // 挂载拉取：分类必取；编辑态再取商品详情（vanilla init 同款两段）
  $effect(() => {
    void (async () => {
      const cats: CategoryRow[] = await listCategories()
      catOptions = cats.map((c) => ({ label: c.name, value: c.name }))
      if (id != null && Number.isFinite(id)) {
        editing = await getProduct(id)
      }
      productLoaded = true
    })()
  })

  // 数据就绪边沿回填：新建=分类就绪即填；编辑=分类与商品详情都就绪再填
  $effect(() => {
    if (!productLoaded || catOptions.length === 0) return
    if (id != null && editing === null && !notFoundNotified) {
      notFoundNotified = true
      appMessage.error(t('products.notFound'))
    }
    const row = editing
    const fallbackCat =
      row && catOptions.some((c) => c.value === row.category)
        ? row.category
        : (catOptions[0]?.value ?? '')
    nameEl?.setAttribute('value', row?.name ?? '')
    catEl?.setAttribute('value', fallbackCat)
    priceEl?.setAttribute('value', row ? String(row.price) : '')
    stockEl?.setAttribute('value', row ? String(row.stock) : '')
    dateEl?.setAttribute('value', row?.created ?? today())
  })

  function onSave(): void {
    ;(formEl?.shadowRoot?.querySelector('form') as HTMLFormElement | null)?.requestSubmit()
  }

  function onBack(): void {
    navigate('/products')
  }

  interface FormValues {
    name: string
    category: string
    price: string
    stock: string
  }

  async function onSubmit(e: Event): Promise<void> {
    if (saving) return
    const values = (e as CustomEvent<{ values: FormValues }>).detail.values
    const price = Number(values.price)
    if (!(price > 0)) {
      appMessage.error(t('products.priceError'))
      return
    }
    saving = true
    try {
      const payload = {
        name: values.name,
        category: values.category || catOptions[0]?.value || '',
        price,
        stock: Number(values.stock) || 0,
        status: editing?.status ?? ('on' as const),
        created: dateEl?.getAttribute('value') || today(),
      }
      if (editing) {
        const updated = await updateProduct(editing.id, payload)
        if (!updated) appMessage.error(t('products.notFound'))
        else appMessage.success(t('common.saved'))
      } else {
        await createProduct(payload)
        appMessage.success(t('common.created'))
      }
      navigate('/products')
    } finally {
      saving = false
    }
  }

  const title = $derived.by(() => {
    void $locale
    return id
      ? t('products.editItem').replace('#{id}', String(id))
      : t('products.newProduct')
  })
  const rules = $derived.by(() => {
    void $locale
    return JSON.stringify({ name: [{ required: true, message: t('products.rule.name') }] })
  })
  const catOptionsJson = $derived(JSON.stringify(catOptions))
</script>

<div class="page product-edit-page">
  <oas-page-header data-testid="pe-page-header" title={title}>
    <div slot="extra" class="ph-extra">
      <a
        class="link-btn"
        data-testid="pe-back"
        href="#/products"
        onclick={(e) => {
          e.preventDefault()
          onBack()
        }}
      >
        {tt('orderDetail.backList')}
      </a>
    </div>
  </oas-page-header>
  <oas-card>
    <oas-form bind:this={formEl} id="product-form" rules={rules} onoas-submit={(e) => void onSubmit(e)}>
      <div class="product-form">
        <div class="form-field">
          <label class="form-label" for="pf-name">
            {tt('products.form.name')}
            <span class="req">*</span>
          </label>
          <oas-input
            bind:this={nameEl}
            id="pf-name"
            data-testid="pf-name"
            name="name"
            placeholder={tt('products.form.namePlaceholder')}
          ></oas-input>
        </div>
        <div class="form-field">
          <label class="form-label" for="pf-category">{tt('products.category')}</label>
          <oas-select
            bind:this={catEl}
            id="pf-category"
            data-testid="pf-category"
            name="category"
            options={catOptionsJson}
          ></oas-select>
        </div>
        <div class="form-grid">
          <div class="form-field">
            <label class="form-label" for="pf-price">{tt('products.th.price')}</label>
            <oas-input-number
              bind:this={priceEl}
              id="pf-price"
              data-testid="pf-price"
              name="price"
              min="0.01"
              precision="2"
              placeholder="0.00"
            ></oas-input-number>
          </div>
          <div class="form-field">
            <label class="form-label" for="pf-stock">{tt('products.th.stock')}</label>
            <oas-input-number
              bind:this={stockEl}
              id="pf-stock"
              data-testid="pf-stock"
              name="stock"
              min="0"
              placeholder="0"
            ></oas-input-number>
          </div>
        </div>
        <div class="form-field">
          <label class="form-label" for="pf-date">{tt('products.form.listedDate')}</label>
          <oas-date-picker
            bind:this={dateEl}
            id="pf-date"
            data-testid="pf-date"
            placeholder={tt('products.form.datePlaceholder')}
          ></oas-date-picker>
        </div>
        <div class="form-field">
          <label class="form-label" for="pf-cover">{tt('products.form.cover')}</label>
          <oas-upload id="pf-cover" data-testid="pf-cover" accept="image/*" list-type="picture"></oas-upload>
        </div>
        <div class="form-actions">
          <oas-space justify="end">
            <oas-button data-testid="pe-cancel" onclick={onBack}>{tt('common.cancel')}</oas-button>
            <oas-button data-testid="pe-save" type="primary" onclick={onSave}>
              {tt('common.save')}
            </oas-button>
          </oas-space>
        </div>
      </div>
    </oas-form>
  </oas-card>
</div>

// templates/admin-pro/vue/src/pages/product-edit.vue
<script setup lang="ts">
// src/pages/product-edit.vue —— 商品编辑页（page 表单模式：oas-page-header + 表单）
//    结构 + onMounted 数据就绪后做同款 setAttribute 回填（表单字段非受控，value 全走
// 2. 事件绑定：pe-save/pe-cancel 按钮在 light DOM（非 drawer/modal panel），原生 click
//    模板直绑 @click；oas-submit 自定义事件同样模板直绑（Vue 原生支持 kebab 事件，
//    无需 react 版 useOasEvent 桥接）
//    （to="/products"），hash/history 双模式均正确（react 版 Link 同款）
//    整页重渲染，title/rules/placeholder/标签随 locale 自动重算（products 同款模式）
import { computed, onMounted, onUnmounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import '../styles/pages/products.css'
import { listCategories } from '../data/categories'
import { createProduct, getProduct, updateProduct } from '../data/products'
import type { ProductRow } from '../data/products'
import { useT } from '../composables/use-t'
import { appMessage } from '../lib/app-message'

interface Option {
  label: string
  value: string
}

interface FormValues {
  name: string
  category: string
  price: string
  stock: string
}

function today(): string {
  return new Date().toISOString().slice(0, 10)
}

const { t: tt, locale } = useT()
/** 模板文案函数：读 locale.value 建立响应式依赖，切语言时重渲 */
function t(key: string, params?: Record<string, string | number>): string {
  void locale.value
  return tt(key, params)
}

const router = useRouter()

const id: number | null = (() => {
  const rawId = sessionStorage.getItem('product-edit-id')
  return rawId ? Number(rawId) : null
})()

const editing = ref<ProductRow | null>(null)
const catOptions = ref<Option[]>([])

const formRef = ref<HTMLElement | null>(null)
const nameRef = ref<HTMLElement | null>(null)
const catRef = ref<HTMLElement | null>(null)
const priceRef = ref<HTMLElement | null>(null)
const stockRef = ref<HTMLElement | null>(null)
const dateRef = ref<HTMLElement | null>(null)
const saving = ref(false)

// 异步拉取存活标记：卸载后丢弃迟到的 Promise 结果（dashboard.vue 同款语义）
let alive = true
onUnmounted(() => {
  alive = false
})

onMounted(async () => {
  const cats = await listCategories()
  if (!alive) return
  const opts = cats.map((c) => ({ label: c.name, value: c.name }))
  catOptions.value = opts
  let row: ProductRow | null = null
  if (id && Number.isFinite(id)) {
    row = await getProduct(id)
    if (!alive) return
    if (!row) appMessage.error(tt('products.notFound'))
  }
  editing.value = row
  const fallbackCat =
    row && opts.some((c) => c.value === row.category) ? row.category : (opts[0]?.value ?? '')
  nameRef.value?.setAttribute('value', row?.name ?? '')
  catRef.value?.setAttribute('value', fallbackCat)
  priceRef.value?.setAttribute('value', row ? String(row.price) : '')
  stockRef.value?.setAttribute('value', row ? String(row.stock) : '')
  dateRef.value?.setAttribute('value', row?.created ?? today())
})

function onSave(): void {
  const form = formRef.value?.shadowRoot?.querySelector('form') as HTMLFormElement | null
  form?.requestSubmit()
}

async function onSubmit(e: Event): Promise<void> {
  if (saving.value) return
  const values = (e as CustomEvent<{ values: FormValues }>).detail.values
  const price = Number(values.price)
  if (!(price > 0)) {
    appMessage.error(tt('products.priceError'))
    return
  }
  saving.value = true
  try {
    const payload = {
      name: values.name,
      category: values.category || catOptions.value[0]?.value || '',
      price,
      stock: Number(values.stock) || 0,
      status: editing.value?.status ?? ('on' as const),
      created: dateRef.value?.getAttribute('value') || today(),
    }
    if (editing.value) {
      const updated = await updateProduct(editing.value.id, payload)
      if (!updated) appMessage.error(tt('products.notFound'))
      else appMessage.success(tt('common.saved'))
    } else {
      await createProduct(payload)
      appMessage.success(tt('common.created'))
    }
    void router.push('/products')
  } finally {
    saving.value = false
  }
}

const title = computed(() =>
  id ? t('products.editItem').replace('#{id}', String(id)) : t('products.newProduct'),
)
const rules = computed(() =>
  JSON.stringify({ name: [{ required: true, message: t('products.rule.name') }] }),
)
const catOptionsJson = computed(() => JSON.stringify(catOptions.value))
</script>

<template>
  <div class="page product-edit-page">
    <oas-page-header data-testid="pe-page-header" :title="title">
      <div slot="extra" class="ph-extra">
        <RouterLink class="link-btn" data-testid="pe-back" to="/products">
          {{ t('orderDetail.backList') }}
        </RouterLink>
      </div>
    </oas-page-header>
    <oas-card>
      <oas-form ref="formRef" id="product-form" :rules="rules" @oas-submit="onSubmit">
        <div class="product-form">
          <div class="form-field">
            <label class="form-label">
              {{ t('products.form.name') }}
              <span class="req">*</span>
            </label>
            <oas-input
              ref="nameRef"
              data-testid="pf-name"
              name="name"
              :placeholder="t('products.form.namePlaceholder')"
            />
          </div>
          <div class="form-field">
            <label class="form-label">{{ t('products.category') }}</label>
            <oas-select
              ref="catRef"
              data-testid="pf-category"
              name="category"
              :options="catOptionsJson"
            />
          </div>
          <div class="form-grid">
            <div class="form-field">
              <label class="form-label">{{ t('products.th.price') }}</label>
              <oas-input-number
                ref="priceRef"
                data-testid="pf-price"
                name="price"
                min="0.01"
                precision="2"
                placeholder="0.00"
              />
            </div>
            <div class="form-field">
              <label class="form-label">{{ t('products.th.stock') }}</label>
              <oas-input-number
                ref="stockRef"
                data-testid="pf-stock"
                name="stock"
                min="0"
                placeholder="0"
              />
            </div>
          </div>
          <div class="form-field">
            <label class="form-label">{{ t('products.form.listedDate') }}</label>
            <oas-date-picker
              ref="dateRef"
              data-testid="pf-date"
              :placeholder="t('products.form.datePlaceholder')"
            />
          </div>
          <div class="form-field">
            <label class="form-label">{{ t('products.form.cover') }}</label>
            <oas-upload data-testid="pf-cover" accept="image/*" list-type="picture" />
          </div>
          <div class="form-actions">
            <oas-space justify="end">
              <oas-button data-testid="pe-cancel" @click="void router.push('/products')">
                {{ t('common.cancel') }}
              </oas-button>
              <oas-button data-testid="pe-save" type="primary" @click="onSave">
                {{ t('common.save') }}
              </oas-button>
            </oas-space>
          </div>
        </div>
      </oas-form>
    </oas-card>
  </div>
</template>
