// templates/admin-pro/svelte/src/pages/users/user-detail.svelte
<script lang="ts">
  // src/pages/users/user-detail.svelte —— 用户详情弹窗（descriptions + 权限标识 + 编辑/删除）
  // 1. 全声明式——user/roleName/perms 由父组件 state 派生，重渲即最新（oas-descriptions 的
  //    items 走默认 slot，light DOM 子节点变化自然生效）
  // 2. 编辑/删除按钮位于 oas-modal 的 panel 内，panel 对原生 click stopPropagation；Svelte 的
  //    onclick 直绑元素本身，不受该陷阱影响；popconfirm 的 oas-ok 与 modal 的 oas-close
  //    自定义事件 onoas-* 直绑
  import type { UserRow } from '../../data/users'
  import { useT } from '../../lib/use-t.svelte'

  export interface UserPermItem {
    perm: string
    allowed: boolean
  }

  interface Props {
    open: boolean
    user: UserRow | null
    /** 角色显示名（roleMap 命中取角色名，否则取枚举文案；父组件 roleName() 同款） */
    roleName: string
    /** 角色标签色调（vanilla roleTagType/tagTypeForRole 段，父组件算好传入） */
    roleTagType: string
    perms: UserPermItem[]
    canMutate: boolean
    onClose: () => void
    onEdit: () => void
    onDelete: () => void
  }

  let { open, user, roleName, roleTagType, perms, canMutate, onClose, onEdit, onDelete }: Props =
    $props()

  const { t, locale } = useT()
  /** 模板文案函数：读 $locale 建立响应式依赖，切语言时重渲 */
  const tt = $derived.by(() => {
    void $locale
    return t
  })

  function statusTagType(status: UserRow['status']): string {
    return status === 'active' ? 'success' : 'danger'
  }
</script>

<oas-modal
  data-testid="user-detail-modal"
  no-footer
  visible={open ? '' : null}
  onoas-close={() => onClose()}
>
  <div class="modal-body">
    <div class="detail-header">
      <oas-avatar id="detail-avatar" size="48">
        <span slot="fallback" id="detail-avatar-text">
          {user ? user.name.charAt(0).toUpperCase() : ''}
        </span>
      </oas-avatar>
      <div>
        <div id="detail-name" class="detail-name">{user?.name ?? ''}</div>
        <oas-tag id="detail-role-tag" type={roleTagType}>{roleName}</oas-tag>
      </div>
    </div>
    {#if user}
      <oas-descriptions id="detail-desc" column="1">
        <oas-descriptions-item label="ID">
          <span id="detail-id">{user.id}</span>
        </oas-descriptions-item>
        <oas-descriptions-item label={tt('users.name')}>
          <span id="detail-name2">{user.name}</span>
        </oas-descriptions-item>
        <oas-descriptions-item label={tt('users.email')}>
          <span id="detail-email">{user.email}</span>
        </oas-descriptions-item>
        <oas-descriptions-item label={tt('users.role')}>
          <span id="detail-role">{roleName}</span>
        </oas-descriptions-item>
        <oas-descriptions-item label={tt('users.status')}>
          <oas-tag id="detail-status-tag" type={statusTagType(user.status)}>
            {tt(`users.status.${user.status}`)}
          </oas-tag>
        </oas-descriptions-item>
        <oas-descriptions-item label={tt('users.created')}>
          <span id="detail-created">{user.created}</span>
        </oas-descriptions-item>
      </oas-descriptions>
    {/if}
    <oas-divider></oas-divider>
    <div class="detail-perms-title form-label">{tt('users.perm')}</div>
    <div id="detail-perms-list" class="detail-perms-list">
      {#if perms.length === 0}
        <oas-tag type="default">{tt('users.nonePerm')}</oas-tag>
      {:else}
        {#each perms as p (p.perm)}
          <oas-tag class="mono" type={p.allowed ? 'success' : 'default'}>{p.perm}</oas-tag>
        {/each}
      {/if}
    </div>
    <oas-space justify="end">
      <oas-button data-testid="detail-edit" type="primary" onclick={() => onEdit()}>
        {tt('common.edit')}
      </oas-button>
      <oas-popconfirm title={tt('users.confirmDelete')} id="delete-popconfirm" onoas-ok={() => onDelete()}>
        <oas-button
          data-testid="detail-delete"
          type="danger"
          disabled={!canMutate ? '' : null}
          title={!canMutate ? tt('common.noPerm') : undefined}
        >
          {tt('common.delete')}
        </oas-button>
      </oas-popconfirm>
    </oas-space>
  </div>
</oas-modal>

// templates/admin-pro/vue/src/pages/user-detail.vue
<script setup lang="ts">
// src/pages/user-detail.vue —— 用户详情弹窗（头像 + 描述列表 + 权限标识 + 编辑/删除）
// renderPerms/delete-popconfirm 段
//    声明式——详情字段由 user/roleName/permTags props 派生，oas-descriptions 结构静态写出
//    detail-status-tag/detail-created）
//    type=success/default 由 allowed 派生；空列表回落单个 users.nonePerm 标签（同款）
//    本模版 oas-ok 仅上抛 delete，校验/持久化/提示在父组件（编辑/新建同样父组件持有状态）
// 4. visible 受控：oas-close 上抛 close 回写父组件 state（user-form.vue 同款）
import { computed } from 'vue'
import type { UserRow } from '../data/users'
import { useT } from '../composables/use-t'

export interface PermTag {
  perm: string
  allowed: boolean
}

const props = defineProps<{
  open: boolean
  user: UserRow | null
  /** 角色显示名（父组件 roleName：roleId 命中角色表优先，否则本地化枚举标签） */
  roleName: string
  /** 角色标签配色（vanilla：roleId != null ? roleTagType(target) : tagTypeForRole(role)） */
  roleTagType: string
  permTags: PermTag[]
  canMutate: boolean
}>()
const emit = defineEmits<{
  close: []
  edit: []
  delete: []
}>()

const { t: tt, locale } = useT()
/** 模板文案函数：读 locale.value 建立响应式依赖，切语言时重渲 */
function t(key: string, params?: Record<string, string | number>): string {
  void locale.value
  return tt(key, params)
}

const avatarText = computed(() => props.user?.name.charAt(0).toUpperCase() ?? '')
const statusLabel = computed(() => (props.user ? t(`users.status.${props.user.status}`) : ''))
const statusTagType = computed(() => (props.user?.status === 'active' ? 'success' : 'danger'))
</script>

<template>
  <oas-modal
    data-testid="user-detail-modal"
    no-footer
    :visible="open ? '' : null"
    @oas-close="emit('close')"
  >
    <div class="modal-body">
      <div class="detail-header">
        <oas-avatar id="detail-avatar" size="48">
          <span slot="fallback" id="detail-avatar-text">{{ avatarText }}</span>
        </oas-avatar>
        <div>
          <div id="detail-name" class="detail-name">{{ user?.name ?? '' }}</div>
          <oas-tag id="detail-role-tag" :type="roleTagType">{{ roleName }}</oas-tag>
        </div>
      </div>
      <oas-descriptions id="detail-desc" column="1">
        <oas-descriptions-item label="ID">
          <span id="detail-id">{{ user?.id ?? '' }}</span>
        </oas-descriptions-item>
        <oas-descriptions-item :label="t('users.name')">
          <span id="detail-name2">{{ user?.name ?? '' }}</span>
        </oas-descriptions-item>
        <oas-descriptions-item :label="t('users.email')">
          <span id="detail-email">{{ user?.email ?? '' }}</span>
        </oas-descriptions-item>
        <oas-descriptions-item :label="t('users.role')">
          <span id="detail-role">{{ roleName }}</span>
        </oas-descriptions-item>
        <oas-descriptions-item :label="t('users.status')">
          <oas-tag id="detail-status-tag" :type="statusTagType">{{ statusLabel }}</oas-tag>
        </oas-descriptions-item>
        <oas-descriptions-item :label="t('users.created')">
          <span id="detail-created">{{ user?.created ?? '' }}</span>
        </oas-descriptions-item>
      </oas-descriptions>
      <oas-divider />
      <div class="detail-perms-title form-label">{{ t('users.perm') }}</div>
      <div id="detail-perms-list" class="detail-perms-list">
        <oas-tag v-if="permTags.length === 0" type="default">{{ t('users.nonePerm') }}</oas-tag>
        <oas-tag
          v-for="p in permTags"
          :key="p.perm"
          class="mono"
          :type="p.allowed ? 'success' : 'default'"
        >
          {{ p.perm }}
        </oas-tag>
      </div>
      <oas-space justify="end">
        <oas-button data-testid="detail-edit" type="primary" @click="emit('edit')">
          {{ t('common.edit') }}
        </oas-button>
        <oas-popconfirm id="delete-popconfirm" :title="t('users.confirmDelete')" @oas-ok="emit('delete')">
          <oas-button
            data-testid="detail-delete"
            type="danger"
            :disabled="canMutate ? null : ''"
            :title="canMutate ? null : t('common.noPerm')"
          >
            {{ t('common.delete') }}
          </oas-button>
        </oas-popconfirm>
      </oas-space>
    </div>
  </oas-modal>
</template>
