// templates/admin-pro/react/src/pages/users.tsx
// src/pages/users.tsx —— 用户管理（表格 + 搜索 + 详情 descriptions + modal 表单 + 角色权限）
//    rows/roles/menuTree/keyword/editingId/formOpen/detailOpen 全部 useState，表格 data/
//    空态/按钮禁用全部由 state 派生；refresh() 仅重拉数据 setState，重渲染即最新
// 2. 事件绑定：oas-input 的 oas-input/oas-clear 自定义事件走 useOasEvent//    新建/刷新/清筛选按钮为 light DOM 原生 click，直绑 onClick；表格行事件与两个弹窗的
//    事件接线见 ./users-table.tsx / ./user-form.tsx / ./user-detail.tsx 头注释
//   （组件受控集合外的人工复位），本模版经 tableRef 做同样的事，不纳入 state
//    重渲染，columns/options/标签随 locale 自动重算（dashboard 同款模式）
// 5. 子组件拆分（单文件 ≤400 行纪律）：表格 ./users-table.tsx、表单弹窗 ./user-form.tsx、
//    详情弹窗 ./user-detail.tsx
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { listUsers, removeUser } from '../data/users'
import type { UserRow, UserRole } from '../data/users'
import { listRoles, treeMenus } from '../data/system'
import type { MenuTree, RoleRow } from '../data/system'
import { useOasEvent } from '../hooks/use-oas-event'
import { useT } from '../hooks/use-t'
import { appMessage } from '../lib/app-message'
import { readPageSize } from '../settings-init'
import { session } from '../store/session'
import { UserDetail } from './user-detail'
import type { UserPermItem } from './user-detail'
import { UserForm } from './user-form'
import { UsersTable } from './users-table'

/** 每页条数跟随设置中心（settings 页 page-size，默认 5），vanilla pageSize() 同款 */
function readPageSizeNum(): number {
  return Number(readPageSize()) || 5
}

/** vanilla ALLOWED：各角色枚举在用户管理下可用的权限标识 */
const ALLOWED: Record<UserRole, string[]> = {
  admin: ['user:list', 'user:add', 'user:edit', 'user:delete'],
  editor: ['user:list', 'user:add', 'user:edit'],
  viewer: ['user:list'],
}

/** vanilla findMenu：菜单树里按标题找 C 类节点（用户管理） */
function findMenu(nodes: MenuTree[], title: string): MenuTree | null {
  for (const n of nodes) {
    if (n.title === title && n.type === 'C') return n
    if (n.children?.length) {
      const f = findMenu(n.children, title)
      if (f) return f
    }
  }
  return null
}

/** vanilla tagTypeForStatus / tagTypeForRole / roleTagType 段 */
function tagTypeForRole(role: UserRole): string {
  if (role === 'admin') return 'primary'
  if (role === 'editor') return 'warning'
  return 'default'
}

function roleTagType(target: UserRow): string {
  return target.roleId === 1 ? 'primary' : target.roleId === 4 ? 'default' : 'warning'
}

export default function UsersPage() {
  const { t } = useT()
  const [rows, setRows] = useState<UserRow[]>([])
  const [roles, setRoles] = useState<RoleRow[]>([])
  const [menuTree, setMenuTree] = useState<MenuTree[]>([])
  const [keyword, setKeyword] = useState('')
  const [editingId, setEditingId] = useState<number | null>(null)
  const [formOpen, setFormOpen] = useState(false)
  const [detailOpen, setDetailOpen] = useState(false)
  const [loading, setLoading] = useState(false)
  const [pageSize] = useState(readPageSizeNum)

  const tableRef = useRef<HTMLElement | null>(null)
  const searchRef = useRef<HTMLElement | null>(null)

  const canMutate = session.user?.role !== 'viewer'
  const roleMap = useMemo(() => new Map(roles.map((r) => [r.id, r])), [roles])

  const refresh = useCallback(async () => {
    setLoading(true)
    const [list, roleList, tree] = await Promise.all([listUsers(), listRoles(), treeMenus()])
    setRows(list)
    setRoles(roleList)
    setMenuTree(tree)
    setLoading(false)
  }, [])

  useEffect(() => {
    void refresh()
  }, [refresh])

  useEffect(() => {
    const table = tableRef.current
    if (!table) return
    if (loading) table.setAttribute('loading', '')
    else table.removeAttribute('loading')
  }, [loading])

  const roleName = useCallback(
    (target: UserRow): string => {
      if (target.roleId != null) {
        const r = roleMap.get(target.roleId)
        if (r) return r.name
      }
      return t(`users.role.${target.role}`)
    },
    [roleMap, t],
  )

  const filtered = useMemo(() => {
    const kw = keyword.trim().toLowerCase()
    return rows.filter((r) => {
      if (kw && !(r.name.toLowerCase().includes(kw) || r.email.toLowerCase().includes(kw)))
        return false
      return true
    })
  }, [rows, keyword])

  const dataJson = useMemo(
    () =>
      JSON.stringify(
        filtered.map((row) => ({
          id: row.id,
          name: row.name,
          email: row.email,
          role: roleName(row),
          status: t(`users.status.${row.status}`),
          created: row.created,
        })),
      ),
    [filtered, roleName, t],
  )

  const detailPerms = useMemo((): UserPermItem[] => {
    const target = rows.find((r) => r.id === editingId)
    if (!target) return []
    const node = findMenu(menuTree, '用户管理')
    if (!node) return []
    const perms = (node.children ?? [])
      .filter((c) => c.type === 'F')
      .map((c) => c.perms ?? '')
      .filter(Boolean)
    const allowed = new Set(ALLOWED[target.role])
    return perms.map((p) => ({ perm: p, allowed: allowed.has(p) }))
  }, [rows, editingId, menuTree])

  const detailRow = rows.find((r) => r.id === editingId) ?? null

  const onCreate = () => {
    if (!canMutate) return
    setEditingId(null)
    setFormOpen(true)
  }

  const onEditRow = (id: number) => {
    if (!rows.some((r) => r.id === id)) return
    if (!canMutate) {
      appMessage.error(t('common.noPerm'))
      return
    }
    setEditingId(id)
    setFormOpen(true)
  }

  const onRowOpen = (id: number) => {
    if (!rows.some((r) => r.id === id)) return
    setEditingId(id)
    setDetailOpen(true)
  }

  const onDetailEdit = () => {
    if (!detailRow) return
    setDetailOpen(false)
    setFormOpen(true)
  }

  const onDelete = async () => {
    if (editingId == null) return
    if (!canMutate) {
      appMessage.error(t('common.noPerm'))
      return
    }
    await removeUser(editingId)
    setEditingId(null)
    setDetailOpen(false)
    appMessage.success(t('common.deleted'))
    void refresh()
  }

  const backToFirstPage = () => tableRef.current?.setAttribute('current', '1')
  useOasEvent<{ value: string }>(searchRef, 'oas-input', (d) => {
    setKeyword(d.value)
    backToFirstPage()
  })
  useOasEvent(searchRef, 'oas-clear', () => {
    setKeyword('')
    backToFirstPage()
  })

  const onClearFilters = () => {
    setKeyword('')
    backToFirstPage()
    tableRef.current?.removeAttribute('filter-values')
    searchRef.current?.setAttribute('value', '')
  }

  return (
    <div className="page">
      <div className="page-head">
        <div>
          <h1 className="page-title">{t('users.title')}</h1>
          <p className="page-subtitle">{t('users.subtitle')}</p>
        </div>
        <oas-button
          data-testid="user-create"
          type="primary"
          icon="plus"
          disabled={!canMutate || undefined}
          title={!canMutate ? t('common.noPerm') : undefined}
          aria-disabled={!canMutate ? 'true' : undefined}
          onClick={onCreate}
        >
          {t('users.new')}
        </oas-button>
      </div>
      <oas-card className="list-card" title={t('users.list')}>
        <div className="users-toolbar" slot="extra">
          <oas-input
            ref={searchRef}
            data-testid="user-search"
            placeholder={t('users.search')}
            clearable
            prefix-icon="search"
          />
          <oas-button
            id="users-refresh"
            icon="refresh"
            title={t('common.refresh')}
            onClick={() => void refresh()}
          />
        </div>
        <UsersTable
          tableRef={tableRef}
          dataJson={dataJson}
          roles={roles}
          empty={filtered.length === 0}
          pageSize={pageSize}
          onRowOpen={onRowOpen}
          onEditRow={onEditRow}
          onClearFilters={onClearFilters}
        />
      </oas-card>
      <UserForm
        open={formOpen}
        editingId={editingId}
        editing={rows.find((r) => r.id === editingId) ?? null}
        roles={roles}
        onClose={() => setFormOpen(false)}
        onSaved={() => {
          setFormOpen(false)
          void refresh()
        }}
      />
      <UserDetail
        open={detailOpen}
        user={detailRow}
        roleName={detailRow ? roleName(detailRow) : ''}
        roleTagType={
          detailRow
            ? detailRow.roleId != null
              ? roleTagType(detailRow)
              : tagTypeForRole(detailRow.role)
            : 'default'
        }
        perms={detailPerms}
        canMutate={canMutate}
        onClose={() => setDetailOpen(false)}
        onEdit={onDetailEdit}
        onDelete={() => void onDelete()}
      />
    </div>
  )
}

// templates/admin-pro/vue/src/pages/users.vue
<script setup lang="ts">
// src/pages/users.vue —— 用户管理（搜索/刷新 + 表格 + 新建/编辑弹窗 + 详情弹窗）
//    本模版声明式——rows/roles/menuTree/keyword/editingId/formOpen/detailOpen 全部 ref，
//    表格 data/空态/弹窗 visible 由 state 派生；refresh() 仅重拉数据写 ref，重渲染即最新
// 2. 子组件拆分（单文件 ≤400 行纪律）：表格 ./users-table.vue、表单弹窗 ./user-form.vue、
//    等纯函数留在本文件（跨子组件共享的派生逻辑单一出处）
//    本模版经子组件 defineExpose 的 resetPage/clearFilterValues 走同一 attribute 通道
//    本模版 useT() 订阅后整页重渲染，columns（子组件内）/displayRows/规则/选项随 locale 重算
// 6. session 为模块级状态（登录后页面重挂载才变），canMutate 非响应式取值（dashboard.vue 同款）
import { computed, onMounted, ref } from 'vue'
import { listUsers, removeUser } from '../data/users'
import type { UserRow, UserRole } from '../data/users'
import { listRoles, treeMenus } from '../data/system'
import type { MenuTree, RoleRow } from '../data/system'
import { session } from '../store/session'
import { useT } from '../composables/use-t'
import { appMessage } from '../lib/app-message'
import UsersTable from './users-table.vue'
import type { UserDisplayRow } from './users-table.vue'
import UserForm from './user-form.vue'
import UserDetail from './user-detail.vue'
import type { PermTag } from './user-detail.vue'

const ALLOWED: Record<UserRole, string[]> = {
  admin: ['user:list', 'user:add', 'user:edit', 'user:delete'],
  editor: ['user:list', 'user:add', 'user:edit'],
  viewer: ['user:list'],
}

const { t: tt, locale } = useT()
/** 模板文案函数：读 locale.value 建立响应式依赖，切语言时重渲 */
function t(key: string, params?: Record<string, string | number>): string {
  void locale.value
  return tt(key, params)
}

const canMutate = session.user?.role !== 'viewer'

const rows = ref<UserRow[]>([])
const roles = ref<RoleRow[]>([])
const roleMap = ref<Map<number, RoleRow>>(new Map())
const menuTree = ref<MenuTree[]>([])
const keyword = ref('')
const loading = ref(false)
const editingId = ref<number | null>(null)
const formOpen = ref(false)
const detailOpen = ref(false)

const searchRef = ref<HTMLElement | null>(null)
const tableRef = ref<InstanceType<typeof UsersTable> | null>(null)

function findMenu(nodes: MenuTree[], title: string): MenuTree | null {
  for (const n of nodes) {
    if (n.title === title && n.type === 'C') return n
    if (n.children?.length) {
      const f = findMenu(n.children, title)
      if (f) return f
    }
  }
  return null
}

function roleName(target: UserRow): string {
  if (target.roleId != null) {
    const r = roleMap.value.get(target.roleId)
    if (r) return r.name
  }
  return tt(`users.role.${target.role}`)
}

async function refresh(): Promise<void> {
  loading.value = true
  const [list, roleList, tree] = await Promise.all([listUsers(), listRoles(), treeMenus()])
  rows.value = list
  roles.value = roleList
  roleMap.value = new Map(roleList.map((r) => [r.id, r]))
  menuTree.value = tree
  loading.value = false
}
onMounted(() => void refresh())

const filtered = computed(() => {
  const kw = keyword.value.trim().toLowerCase()
  return rows.value.filter((r) => {
    if (kw && !(r.name.toLowerCase().includes(kw) || r.email.toLowerCase().includes(kw)))
      return false
    return true
  })
})

const displayRows = computed<UserDisplayRow[]>(() => {
  void locale.value
  return filtered.value.map((r) => ({
    id: r.id,
    name: r.name,
    email: r.email,
    role: roleName(r),
    status: tt(`users.status.${r.status}`),
    created: r.created,
  }))
})
const empty = computed(() => displayRows.value.length === 0)

const editingRow = computed(() => rows.value.find((r) => r.id === editingId.value) ?? null)
const detailRoleName = computed(() => {
  void locale.value
  return editingRow.value ? roleName(editingRow.value) : ''
})
function tagTypeForRole(role: UserRole): string {
  if (role === 'admin') return 'primary'
  if (role === 'editor') return 'warning'
  return 'default'
}
function roleTagTypeFor(target: UserRow): string {
  return target.roleId === 1 ? 'primary' : target.roleId === 4 ? 'default' : 'warning'
}
const detailRoleTagType = computed(() => {
  const target = editingRow.value
  if (!target) return 'default'
  return target.roleId != null ? roleTagTypeFor(target) : tagTypeForRole(target.role)
})

const permTags = computed<PermTag[]>(() => {
  const node = findMenu(menuTree.value, '用户管理')
  if (!node) return []
  const perms = (node.children ?? [])
    .filter((c) => c.type === 'F')
    .map((c) => c.perms ?? '')
    .filter(Boolean)
  const allowed = new Set(ALLOWED[editingRow.value?.role ?? 'viewer'])
  return perms.map((p) => ({ perm: p, allowed: allowed.has(p) }))
})

function onCreate(): void {
  if (!canMutate) return
  editingId.value = null
  formOpen.value = true
}

function onEditRow(id: number): void {
  const row = rows.value.find((r) => r.id === id)
  if (!row) return
  if (!canMutate) {
    appMessage.error(tt('common.noPerm'))
    return
  }
  editingId.value = id
  formOpen.value = true
}

function onRowClick(id: number): void {
  const target = rows.value.find((r) => r.id === id)
  if (!target) return
  editingId.value = id
  detailOpen.value = true
}

function onDetailEdit(): void {
  if (!editingRow.value) return
  detailOpen.value = false
  formOpen.value = true
}

async function onDelete(): Promise<void> {
  if (editingId.value == null) return
  if (!canMutate) {
    appMessage.error(tt('common.noPerm'))
    return
  }
  await removeUser(editingId.value)
  editingId.value = null
  detailOpen.value = false
  appMessage.success(tt('common.deleted'))
  void refresh()
}

function onFormSaved(): void {
  formOpen.value = false
  void refresh()
}

function onSearchInput(e: Event): void {
  keyword.value = (e as CustomEvent<{ value: string }>).detail.value
  tableRef.value?.resetPage()
}
function onSearchClear(): void {
  keyword.value = ''
  tableRef.value?.resetPage()
}

function onClearFilters(): void {
  keyword.value = ''
  tableRef.value?.resetPage()
  tableRef.value?.clearFilterValues()
  searchRef.value?.setAttribute('value', '')
}
</script>

<template>
  <div class="page">
    <div class="page-head">
      <div>
        <h1 class="page-title">{{ t('users.title') }}</h1>
        <p class="page-subtitle">{{ t('users.subtitle') }}</p>
      </div>
      <oas-button
        data-testid="user-create"
        type="primary"
        icon="plus"
        :disabled="canMutate ? null : ''"
        :title="canMutate ? null : t('common.noPerm')"
        :aria-disabled="canMutate ? null : 'true'"
        @click="onCreate"
      >
        {{ t('users.new') }}
      </oas-button>
    </div>
    <oas-card class="list-card" :title="t('users.list')">
      <div class="users-toolbar" slot="extra">
        <oas-input
          ref="searchRef"
          data-testid="user-search"
          :placeholder="t('users.search')"
          clearable
          prefix-icon="search"
          @oas-input="onSearchInput"
          @oas-clear="onSearchClear"
        />
        <oas-button id="users-refresh" icon="refresh" :title="t('common.refresh')" @click="void refresh()" />
      </div>
      <div class="table-wrap" id="table-wrap" :class="{ 'is-empty': empty }">
        <UsersTable
          ref="tableRef"
          :rows="displayRows"
          :roles="roles"
          :empty="empty"
          :loading="loading"
          @edit-row="onEditRow"
          @row-click="onRowClick"
        />
        <div class="empty-overlay" id="empty-overlay" :hidden="!empty">
          <oas-empty :description="t('users.empty')" />
          <oas-button id="clear-filters" type="primary" @click="onClearFilters">
            {{ t('common.clearFilter') }}
          </oas-button>
        </div>
      </div>
    </oas-card>
    <UserForm
      :open="formOpen"
      :editing-id="editingId"
      :editing="editingRow"
      :roles="roles"
      @close="formOpen = false"
      @saved="onFormSaved"
    />
    <UserDetail
      :open="detailOpen"
      :user="editingRow"
      :role-name="detailRoleName"
      :role-tag-type="detailRoleTagType"
      :perm-tags="permTags"
      :can-mutate="canMutate"
      @close="detailOpen = false"
      @edit="onDetailEdit"
      @delete="void onDelete()"
    />
  </div>
</template>
