// templates/admin-pro/vue/src/pages/dept.vue
<script setup lang="ts">
// src/pages/dept.vue —— 部门管理：左树右详情（oas-splitter）+ 详情子部门表格 + 新建/编辑抽屉
//    本模版声明式——tree/selectedId/flat 全部 ref，详情区/子部门表由 selected 派生
// 2. 子组件拆分（单文件 ≤400 行纪律）：表单抽屉 ./dept-form-drawer.vue（RULES/fillForm/
//    父级树选择/oas-submit 段）；子部门表格列 render（操作列）保留本文件
//    template 元素透传（isCustomElement 下编译为真实 <template> 元素），oas-tree 的
//    fillNodeLabel 对 content/childNodes 双通道读取（组件源码实测），模板直写即可
// 4. 树数据通道：data=JSON 字符串、expanded=逗号串、selected 存在性语义；
//    oas-node-render（徽标回填）与 oas-select（选中）模板直绑（第 1 条）
// 5. 删除：详情区按钮 popconfirm 直绑 @oas-ok；子表行内 popconfirm 经 oas-ok 的
//    detail.source 带 data-del 反查（v2.2.8 popconfirm 原生自驱动，无需模板手动 open）；
//    行内编辑按钮经 @click composedPath 匹配（category.vue 同款）
//    本模版 useT() 订阅后整页重渲染，columns（含行内标签）随 locale 自动重算
import '../styles/pages/dept.css'
import { computed, onMounted, ref } from 'vue'
import type { TableColumn } from '@oas-ui/ui/data/table'
import { listDepts, removeDept, treeDepts } from '../data/system'
import type { DeptNode, DeptTree } from '../data/system'
import { useT } from '../composables/use-t'
import { appMessage } from '../lib/app-message'
import DeptFormDrawer from './dept-form-drawer.vue'

const { t: tt, locale } = useT()
/** 模板文案函数：读 locale.value 建立响应式依赖，切语言时重渲 */
function t(key: string, params?: Record<string, string | number>): string {
  void locale.value
  return tt(key, params)
}

function findNode(nodes: DeptTree[], id: number): DeptTree | null {
  for (const n of nodes) {
    if (n.id === id) return n
    if (n.children?.length) {
      const f = findNode(n.children, id)
      if (f) return f
    }
  }
  return null
}

function flatten(nodes: DeptTree[]): DeptNode[] {
  const out: DeptNode[] = []
  const walk = (list: DeptTree[]) => {
    for (const n of list) {
      out.push(n)
      if (n.children?.length) walk(n.children)
    }
  }
  walk(nodes)
  return out
}

function toTreeNodes(nodes: DeptTree[]): Array<Record<string, unknown>> {
  return nodes.map((n) => ({
    key: String(n.id),
    label: n.name,
    members: n.members,
    children: n.children?.length ? toTreeNodes(n.children) : [],
  }))
}

function expandKeys(nodes: DeptTree[]): string[] {
  const keys: string[] = []
  const walk = (list: DeptTree[]) => {
    for (const n of list) {
      if (n.children?.length) {
        keys.push(String(n.id))
        walk(n.children)
      }
    }
  }
  walk(nodes)
  return keys
}

const tree = ref<DeptTree[]>([])
const flat = ref<DeptNode[]>([])
const selectedId = ref<number | null>(null)

// 抽屉状态：editingId（null=新建）/编辑节点/新建子部门时的父节点
const editingId = ref<number | null>(null)
const editing = computed(() => (editingId.value == null ? null : findNode(tree.value, editingId.value)))
const parentForNew = ref<DeptTree | null>(null)
const drawerOpen = ref(false)

const selected = computed(() =>
  selectedId.value == null ? null : findNode(tree.value, selectedId.value),
)

const treeJson = computed(() => JSON.stringify(toTreeNodes(tree.value)))
const expandedStr = computed(() => expandKeys(tree.value).join(','))
const selectedAttr = computed(() => (selectedId.value == null ? null : String(selectedId.value)))

function subActionCell(node: DeptTree): HTMLElement {
  const ctx = document.createElement('div')
  ctx.className = 'action-cell'
  const edit = document.createElement('oas-button')
  edit.setAttribute('data-edit', String(node.id))
  edit.setAttribute('size', 'small')
  edit.setAttribute('type', 'text')
  edit.textContent = tt('common.edit')
  const pop = document.createElement('oas-popconfirm')
  pop.setAttribute('data-del', String(node.id))
  pop.setAttribute('title', tt('dept.confirmDelete'))
  const del = document.createElement('oas-button')
  del.setAttribute('size', 'small')
  del.setAttribute('type', 'danger')
  del.textContent = tt('common.delete')
  pop.appendChild(del)
  ctx.appendChild(edit)
  ctx.appendChild(pop)
  return ctx
}

const subColumns = computed<TableColumn[]>(() => {
  void locale.value
  return [
    { key: 'name', title: tt('dept.th.name') },
    { key: 'members', title: tt('dept.th.members'), align: 'right' },
    { key: 'action', title: tt('dept.th.action'), render: (r) => subActionCell(r as unknown as DeptTree) },
  ]
})

const subRows = computed(() => selected.value?.children ?? [])
const subRowsJson = computed(() => JSON.stringify(subRows.value))

async function refresh(): Promise<void> {
  const [rows, treeRows] = await Promise.all([listDepts(), treeDepts()])
  tree.value = treeRows
  flat.value = rows
  if (selectedId.value == null || !findNode(tree.value, selectedId.value)) {
    selectedId.value = tree.value[0]?.id ?? null
  }
}
onMounted(() => void refresh())

function onNodeRender(e: Event): void {
  const { node, element } = (e as CustomEvent<{ node: { members: number }; element: HTMLElement }>)
    .detail
  const badge = element.querySelector<HTMLElement>('.dept-member-badge')
  if (badge) badge.textContent = String(node.members)
}

function onSelect(e: Event): void {
  selectedId.value = Number((e as CustomEvent<{ key: string }>).detail.key)
}

function openForm(node: DeptNode | null, parent?: DeptTree): void {
  editingId.value = node?.id ?? null
  parentForNew.value = parent ?? null
  drawerOpen.value = true
}

function onCreate(): void {
  openForm(null)
}

function onEditSelected(): void {
  if (selected.value) openForm(selected.value)
}
function onAddChild(): void {
  if (selected.value) openForm(null, selected.value)
}

async function doDelete(id: number): Promise<void> {
  const node = findNode(tree.value, id)
  if (!node) {
    appMessage.error(t('dept.notFound'))
    return
  }
  if ((node.children ?? []).length > 0) {
    appMessage.error(t('dept.hasChildren'))
    return
  }
  const ok = await removeDept(id)
  if (!ok) {
    appMessage.error(t('dept.notFound'))
    return
  }
  appMessage.success(tt('common.deleted'))
  selectedId.value = null
  void refresh()
}

function onDeleteSelected(): void {
  if (selected.value) void doDelete(selected.value.id)
}

// （v2.2.8 起行点击忽略内嵌交互控件：单元格内 popconfirm 原生自驱动，无需模板手动 open）
function onSubClick(e: MouseEvent): void {
  const btn = e
    .composedPath()
    .find((n): n is HTMLElement => n instanceof HTMLElement && n.matches('[data-edit]'))
  if (!btn) return
  const row = flat.value.find((d) => d.id === Number(btn.getAttribute('data-edit')))
  if (row) openForm(row)
}

function onSubDeleteOk(e: Event): void {
  const src = (e as CustomEvent<{ source?: HTMLElement }>).detail?.source
  if (!src?.hasAttribute?.('data-del')) return
  void doDelete(Number(src.getAttribute('data-del')))
}

function onFormSaved(): void {
  drawerOpen.value = false
  editingId.value = null
  void refresh()
}
</script>

<template>
  <div class="page">
    <div class="page-head">
      <div>
        <h1 class="page-title">{{ t('nav.dept') }}</h1>
        <p class="page-subtitle">{{ t('dept.subtitle') }}</p>
      </div>
      <oas-button data-testid="dept-create" type="primary" icon="plus" @click="onCreate">
        {{ t('dept.new') }}
      </oas-button>
    </div>
    <oas-splitter class="dept-layout" percent="30" min="20" max="45">
      <oas-card slot="left" class="dept-tree-card" :title="t('dept.treeTitle')">
        <oas-tree
          data-testid="dept-tree"
          :data="treeJson"
          :expanded="expandedStr"
          :selected="selectedAttr"
          @oas-node-render="onNodeRender"
          @oas-select="onSelect"
        >
          <template slot="node">
            <span class="tree-node-label">
              <span data-node-label></span>
              <span class="dept-member-badge"></span>
            </span>
          </template>
        </oas-tree>
      </oas-card>
      <oas-card slot="right" class="dept-detail-card" :title="t('dept.detailTitle')">
        <div class="dept-detail">
          <template v-if="selected">
            <div class="dept-detail-head">
              <div class="dept-detail-title">{{ selected.name }}</div>
              <oas-tag type="primary" data-testid="dept-detail-members">
                {{ t('dept.memberCount', { n: selected.members }) }}
              </oas-tag>
            </div>
            <oas-descriptions column="1">
              <oas-descriptions-item :label="t('dept.detail.id')">
                <span class="mono">{{ selected.id }}</span>
              </oas-descriptions-item>
              <oas-descriptions-item :label="t('dept.form.parent')">
                <span class="mono">{{ selected.parentId == null ? '—' : selected.parentId }}</span>
              </oas-descriptions-item>
              <oas-descriptions-item :label="t('dept.detail.childCount')">
                <span class="mono">{{ (selected.children ?? []).length }}</span>
              </oas-descriptions-item>
            </oas-descriptions>
            <div class="dept-detail-actions">
              <oas-button type="primary" @click="onEditSelected">{{ t('common.edit') }}</oas-button>
              <oas-button @click="onAddChild">{{ t('dept.addChild') }}</oas-button>
              <oas-popconfirm :title="t('dept.confirmDelete')" @oas-ok="onDeleteSelected">
                <oas-button type="danger">{{ t('common.delete') }}</oas-button>
              </oas-popconfirm>
            </div>
            <div class="dept-detail-sub">
              <div class="dept-detail-sub-title">{{ t('dept.subTitle') }}</div>
              <div>
                <div v-if="subRows.length === 0" class="sub-dept-empty">
                  {{ t('dept.empty.noChildren') }}
                </div>
                <oas-table
                  v-else
                  data-testid="dept-sub-table"
                  row-key="id"
                  :columns="subColumns"
                  :data="subRowsJson"
                  @click="onSubClick"
                  @oas-ok="onSubDeleteOk"
                />
              </div>
            </div>
          </template>
          <oas-empty v-else :description="t('dept.empty.selectNode')" />
        </div>
      </oas-card>
    </oas-splitter>

    <DeptFormDrawer
      :open="drawerOpen"
      :editing-id="editingId"
      :editing="editing"
      :parent-for-new="parentForNew"
      :tree="tree"
      @close="drawerOpen = false"
      @saved="onFormSaved"
    />
  </div>
</template>

// templates/admin-pro/svelte/src/pages/dept.svelte
<script lang="ts">
  // src/pages/dept.svelte —— 部门管理（左树右详情 + 抽屉表单 + 子部门表）
  // 1. 数据：平铺列表/树走 data/system 的 listDepts/treeDepts（内存 CRUD 后 refresh 重取）；
  //    selectedId/editingId/drawerOpen 全部 $state，树的 data/expanded/selected、详情区、
  //    抽屉标题全部由 state 派生；useT() 订阅 locale 后整页重渲
  // 2. 事件绑定：oas-tree 的 oas-select/oas-node-render、oas-form 的 oas-submit 走展开通道直绑；
  //    oas-button 为 custom element，Svelte 原生直绑 onclick（不走根委托，panel 内亦可达）
  // 3. 抽屉字段非受控：open 边沿 $effect 逐字段 setAttribute 回填（含父级树 options/expanded，
  //    expanded 契约为 JSON 字符串数组——oas-ui 2.5.0 收紧）
  // 4. 命令式 API 规避（oas-virtual-list.buffer 崩溃教训）：对 oas-tree/oas-tree-select 只用
  //    attribute 通道，不触碰任何命令式成员
  // 5. 子组件拆分（单文件 ≤400 行纪律）：详情卡 ./dept-detail.svelte（描述/操作/子部门表）
  import '../styles/pages/dept.css'
  import { onMount } from 'svelte'
  import type { DeptNode, DeptTree } from '../data/system'
  import { createDept, listDepts, removeDept, treeDepts, updateDept } from '../data/system'
  import { useT } from '../lib/use-t.svelte'
  import { appMessage } from '../lib/app-message'
  import DeptDetail from './dept-detail.svelte'

  /** oas-tree 自定义节点模板的数据形态 */
  interface DeptTreeNode {
    key: string
    label: string
    members: number
    children: DeptTreeNode[]
  }

  /** vanilla findNode */
  function findNode(nodes: DeptTree[], id: number): DeptTree | null {
    for (const n of nodes) {
      if (n.id === id) return n
      if (n.children?.length) {
        const f = findNode(n.children, id)
        if (f) return f
      }
    }
    return null
  }

  /** vanilla descendants */
  function descendants(nodes: DeptTree[], id: number): Set<number> {
    const set = new Set<number>()
    const node = findNode(nodes, id)
    const walk = (list: DeptTree[]) => {
      for (const n of list) {
        set.add(n.id)
        if (n.children?.length) walk(n.children)
      }
    }
    if (node) walk(node.children ?? [])
    return set
  }

  /** vanilla toTreeNodes */
  function toTreeNodes(nodes: DeptTree[]): DeptTreeNode[] {
    return nodes.map((n) => ({
      key: String(n.id),
      label: n.name,
      members: n.members,
      children: n.children?.length ? toTreeNodes(n.children) : [],
    }))
  }

  /** vanilla expandKeys */
  function expandKeys(nodes: DeptTree[]): string[] {
    const keys: string[] = []
    const walk = (list: DeptTree[]) => {
      for (const n of list) {
        if (n.children?.length) {
          keys.push(String(n.id))
          walk(n.children)
        }
      }
    }
    walk(nodes)
    return keys
  }

  /** vanilla prune：剔除自身及其后代后的选项树 */
  function prune(node: DeptTree, excluded: Set<number>): DeptTree | null {
    if (excluded.has(node.id)) return null
    const children = (node.children ?? [])
      .map((c) => prune(c, excluded))
      .filter((c): c is DeptTree => c !== null)
    return { ...node, children }
  }

  /** vanilla buildParentOptions：剔除编辑目标自身/后代后的选项树（顶级哨兵在回填处拼） */
  function parentOptionTree(nodes: DeptTree[], excludeId: number | null): DeptTree[] {
    if (excludeId == null) return nodes
    const excluded = descendants(nodes, excludeId)
    excluded.add(excludeId)
    return nodes.map((n) => prune(n, excluded)).filter((n): n is DeptTree => n !== null)
  }

  const { t, locale } = useT()
  /** 模板文案函数：读 $locale 建立响应式依赖，切语言时整页重渲 */
  const tt = $derived.by(() => {
    void $locale
    return t
  })

  let tree = $state<DeptTree[]>([])
  let flat = $state<DeptNode[]>([])
  let selectedId = $state<number | null>(null)
  // 抽屉状态：editingId（null=新建）/新建子部门时的父节点/开关
  let editingId = $state<number | null>(null)
  let formParentId = $state<number | null>(null)
  let drawerOpen = $state(false)
  let saving = false // 防重入（非响应式，与 react savingRef 同语义）

  let treeEl: HTMLElement | null = $state(null)
  let drawerEl: HTMLElement | null = $state(null)
  let formEl: HTMLElement | null = $state(null)
  let nameEl: HTMLElement | null = $state(null)
  let parentEl: HTMLElement | null = $state(null)
  let membersEl: HTMLElement | null = $state(null)

  const selectedNode = $derived(selectedId != null ? findNode(tree, selectedId) : null)
  const editingNode = $derived(editingId != null ? findNode(tree, editingId) : null)
  const drawerTitle = $derived(
    editingNode ? tt('dept.editDept', { name: editingNode.name }) : tt('dept.new'),
  )

  // 平铺列表/树双路加载（变更后一并重取，等价 react 版双 key 失效）
  async function refresh(): Promise<void> {
    const [rows, treeRows] = await Promise.all([listDepts(), treeDepts()])
    tree = treeRows
    flat = rows
    if (selectedId == null || !findNode(tree, selectedId)) {
      selectedId = tree[0]?.id ?? null
    }
  }

  onMount(() => {
    void refresh()
  })

  // 树数据通道：data/expanded 均 JSON attribute（expanded 契约=JSON 字符串数组，2.5.0 收紧）；
  // oas-select/oas-node-render 事件处理函数保持稳定引用，随展开对象整体直绑
  const treeAttrs = $derived.by(() => ({
    data: JSON.stringify(toTreeNodes(tree)),
    expanded: JSON.stringify(expandKeys(tree)),
    selected: selectedId != null ? String(selectedId) : null,
    'onoas-select': onSelect,
    'onoas-node-render': onNodeRender,
  }))

  /** vanilla 规则：有子部门禁删；删除后选中复位并重取 */
  async function doDelete(id: number): Promise<void> {
    const node = findNode(tree, id)
    if (!node) {
      appMessage.error(t('dept.notFound'))
      return
    }
    if ((node.children ?? []).length > 0) {
      appMessage.error(t('dept.hasChildren'))
      return
    }
    const ok = await removeDept(id)
    if (!ok) {
      appMessage.error(t('dept.notFound'))
      return
    }
    appMessage.success(t('common.deleted'))
    selectedId = null
    await refresh()
  }

  /** oas-node-render：自定义节点模板里回填成员数徽标 */
  function onNodeRender(e: Event): void {
    const { node, element } = (e as CustomEvent<{ node: DeptTreeNode; element: HTMLElement }>).detail
    const badge = element.querySelector<HTMLElement>('.dept-member-badge')
    if (badge) badge.textContent = String(node.members)
  }

  function onSelect(e: Event): void {
    selectedId = Number((e as CustomEvent<{ key: string }>).detail.key)
  }

  const openCreate = (): void => {
    editingId = null
    formParentId = null
    drawerOpen = true
  }
  const openEdit = (node: DeptNode): void => {
    editingId = node.id
    formParentId = node.parentId
    drawerOpen = true
  }
  const openAddChild = (node: DeptTree): void => {
    editingId = null
    formParentId = node.id
    drawerOpen = true
  }
  const onEditRow = (id: number): void => {
    const row = flat.find((d) => d.id === id)
    if (row) openEdit(row)
  }

  // 抽屉 open 边沿回填：字段值 + 父级树选项/展开（expanded 走 JSON 数组契约）
  $effect(() => {
    if (!drawerOpen) return
    void editingId
    void formParentId
    nameEl?.setAttribute('value', editingNode?.name ?? '')
    membersEl?.setAttribute('value', String(editingNode?.members ?? 0))
    const pid = editingNode?.parentId ?? formParentId ?? null
    parentEl?.setAttribute('value', String(pid ?? 0))
    const toOpt = (list: DeptTree[]): Array<Record<string, unknown>> =>
      list.map((n) => ({
        value: String(n.id),
        label: n.name,
        children: n.children?.length ? toOpt(n.children) : undefined,
      }))
    const opts = [
      { value: '0', label: tt('dept.option.top'), children: toOpt(parentOptionTree(tree, editingId)) },
    ]
    parentEl?.setAttribute('options', JSON.stringify(opts))
    parentEl?.setAttribute('expanded', JSON.stringify(expandKeys(tree)))
  })

  /** 取消：仅关抽屉 */
  function onCancel(): void {
    drawerOpen = false
  }

  /** 保存：触发 oas-form shadow 内原生 form 提交（跨 shadow requestSubmit 通道） */
  function onSave(): void {
    ;(formEl?.shadowRoot?.querySelector('form') as HTMLFormElement | null)?.requestSubmit()
  }

  /** oas-submit：值收集 + create/update 编排（校验失败不关抽屉） */
  async function onFormSubmit(e: Event): Promise<void> {
    if (saving) return
    const { values } = (e as CustomEvent<{ values: { name?: string; members?: string } }>).detail
    const name = values.name?.trim()
    if (!name) return
    const parentRaw = parentEl?.getAttribute('value') || '0'
    const parentId = parentRaw === '0' ? null : Number(parentRaw)
    const members = Number(values.members) || 0
    if (editingId != null && parentId === editingId) {
      appMessage.error(t('dept.err.parentSelf'))
      return
    }
    saving = true
    try {
      if (editingId == null) {
        await createDept({ name, parentId, members })
        appMessage.success(t('common.created'))
      } else {
        const updated = await updateDept(editingId, { name, parentId, members })
        if (!updated) appMessage.error(t('dept.notFound'))
        else appMessage.success(t('common.saved'))
      }
      drawerOpen = false
    } finally {
      saving = false
    }
    await refresh()
  }
</script>

<div class="page">
  <div class="page-head">
    <div>
      <h1 class="page-title">{tt('nav.dept')}</h1>
      <p class="page-subtitle">{tt('dept.subtitle')}</p>
    </div>
    <oas-button data-testid="dept-create" type="primary" icon="plus" onclick={openCreate}>
      {tt('dept.new')}
    </oas-button>
  </div>
  <oas-splitter class="dept-layout" {...{ percent: '30', min: '20', max: '45' }}>
    <oas-card slot="left" class="dept-tree-card" title={tt('dept.treeTitle')}>
      <oas-tree bind:this={treeEl} data-testid="dept-tree" {...treeAttrs}>
        <!-- vanilla template[slot="node"]：节点标签 + 人数徽标（oas-node-render 回填徽标） -->
        <template slot="node">
          <span class="tree-node-label">
            <span data-node-label></span>
            <span class="dept-member-badge"></span>
          </span>
        </template>
      </oas-tree>
    </oas-card>
    <oas-card slot="right" class="dept-detail-card" title={tt('dept.detailTitle')}>
      <DeptDetail
        node={selectedNode}
        onEdit={openEdit}
        onAddChild={openAddChild}
        onDelete={(node) => void doDelete(node.id)}
        onEditRow={onEditRow}
        onSubDelete={(id) => void doDelete(id)}
      />
    </oas-card>
  </oas-splitter>

  <oas-drawer
    bind:this={drawerEl}
    data-testid="dept-form-drawer"
    title={drawerTitle}
    placement="right"
    size="medium"
    no-footer
    visible={drawerOpen ? '' : null}
    onoas-close={() => (drawerOpen = false)}
  >
    <oas-form
      bind:this={formEl}
      rules={JSON.stringify({ name: [{ required: true, message: tt('dept.rule.name') }] })}
      onoas-submit={onFormSubmit}
    >
      <div class="dept-form-body">
        <div class="form-field">
          <label class="form-label" for="df-name">
            {tt('dept.form.name')} <span class="req">*</span>
          </label>
          <oas-input bind:this={nameEl} id="df-name" data-testid="df-name" name="name" placeholder={tt('dept.rule.name')}>
          </oas-input>
        </div>
        <div class="form-field">
          <label class="form-label" for="df-parent">{tt('dept.form.parent')}</label>
          <oas-tree-select bind:this={parentEl} id="df-parent" data-testid="df-parent" placeholder={tt('dept.placeholder.top')}>
          </oas-tree-select>
        </div>
        <div class="form-field">
          <label class="form-label" for="df-members">{tt('dept.form.members')}</label>
          <oas-input-number bind:this={membersEl} id="df-members" data-testid="df-members" name="members" min="0" placeholder="0">
          </oas-input-number>
        </div>
        <div class="form-actions">
          <oas-space justify="end">
            <oas-button data-testid="df-cancel" onclick={onCancel}>{tt('common.cancel')}</oas-button>
            <oas-button data-testid="df-save" type="primary" onclick={onSave}>{tt('common.save')}</oas-button>
          </oas-space>
        </div>
      </div>
    </oas-form>
  </oas-drawer>
</div>
