// templates/admin-pro/vue/src/pages/dict-type-modal.vue
<script setup lang="ts">
// src/pages/dict-type-modal.vue —— 字典类型新建/编辑弹窗（oas-modal + oas-form + 2 字段）
// 容器形态参照 category-form-modal.vue 先例
//    （flush: 'post'，等 DOM 就位）做同样的事（表单字段非受控，value 全走 attribute 通道）
//    监听 oas-close 上抛 close 回写（category-form-modal.vue 同款）
//    规则/按钮随 locale 自动重算
import { computed, ref, watch } from 'vue'
import { createDictType, updateDictType } from '../data/system'
import type { DictType } from '../data/system'
import { useT } from '../composables/use-t'
import { appMessage } from '../lib/app-message'

interface FormValues {
  name: string
  code: string
}

const props = defineProps<{
  open: boolean
  /** 编辑态 id（null=新建）；与 editing 分离以对齐 vanilla 的 editingTypeId 语义 */
  editingId: number | null
  editing: DictType | null
}>()
const emit = defineEmits<{
  close: []
  saved: []
}>()

const { t: tt, locale } = useT()
/** 模板文案函数：读 locale.value 建立响应式依赖，切语言时重渲 */
function t(key: string, params?: Record<string, string | number>): string {
  void locale.value
  return tt(key, params)
}

const formRef = ref<HTMLElement | null>(null)
const nameRef = ref<HTMLElement | null>(null)
const codeRef = ref<HTMLElement | null>(null)
const saving = ref(false)

const title = computed(() =>
  props.editing ? t('dict.editType', { name: props.editing.name }) : t('dict.newType'),
)

const rules = computed(() =>
  JSON.stringify({
    name: [{ required: true, message: t('dict.rule.typeName') }],
    code: [{ required: true, message: t('dict.rule.typeCode') }],
  }),
)

watch(
  () => [props.open, props.editing],
  () => {
    if (!props.open) return
    const row = props.editing
    nameRef.value?.setAttribute('value', row?.name ?? '')
    codeRef.value?.setAttribute('value', row?.code ?? '')
  },
  { flush: 'post' },
)

// 保存=触发 oas-form 内部原生 form 提交（跨 shadow，category-form-modal.vue 同款模式）
function onSave(): void {
  const form = formRef.value?.shadowRoot?.querySelector('form') as HTMLFormElement | null
  form?.requestSubmit()
}

async function onSubmit(e: Event): Promise<void> {
  if (saving.value) return
  saving.value = true
  try {
    const values = (e as CustomEvent<{ values: FormValues }>).detail.values
    const name = values.name?.trim()
    const code = values.code?.trim()
    if (!name || !code) return
    if (props.editingId == null) {
      await createDictType({ name, code })
      appMessage.success(tt('common.created'))
    } else {
      const updated = await updateDictType(props.editingId, { name, code })
      if (!updated) appMessage.error(t('dict.notFoundType'))
      else appMessage.success(tt('common.saved'))
    }
    emit('saved')
  } finally {
    saving.value = false
  }
}
</script>

<template>
  <oas-modal
    data-testid="dict-type-modal"
    no-footer
    :visible="open ? '' : null"
    @oas-close="emit('close')"
  >
    <div class="modal-body">
      <h2>{{ title }}</h2>
      <oas-form ref="formRef" :rules="rules" @oas-submit="void onSubmit($event)">
        <div class="dict-form-body">
          <div class="form-field">
            <label class="form-label">
              {{ t('dict.form.typeName') }}
              <span class="req">*</span>
            </label>
            <oas-input ref="nameRef" data-testid="dtf-name" name="name" :placeholder="t('dict.placeholder.typeName')" />
          </div>
          <div class="form-field">
            <label class="form-label">
              {{ t('dict.form.typeCode') }}
              <span class="req">*</span>
            </label>
            <oas-input ref="codeRef" data-testid="dtf-code" name="code" :placeholder="t('dict.placeholder.typeCode')" />
          </div>
          <div class="form-actions">
            <oas-space justify="end">
              <oas-button data-testid="dtf-cancel" @click="emit('close')">
                {{ t('common.cancel') }}
              </oas-button>
              <oas-button data-testid="dtf-save" type="primary" @click="onSave">
                {{ t('common.save') }}
              </oas-button>
            </oas-space>
          </div>
        </div>
      </oas-form>
    </div>
  </oas-modal>
</template>

// templates/admin-pro/svelte/src/pages/dict-type-modal.svelte
<script lang="ts">
  // src/pages/dict-type-modal.svelte —— 字典类型弹窗（新增/编辑双态，表单事件自包含）
  // 1. visible 由父组件 open 单一事实来源驱动；组件侧关闭（遮罩/Esc/✕）经 oas-close 回写
  // 2. open 边沿 $effect 逐字段 setAttribute 回填（编辑态带出当前值）
  // 3. 取消/保存按钮为 oas-button，Svelte 原生直绑 onclick（不走根委托，panel 内亦可达）；
  //    保存经 shadowRoot 内原生 form 的 requestSubmit 触发（跨 shadow 提交通道）
  import { useT } from '../lib/use-t.svelte'

  interface DictTypeFormValues {
    name?: string
    code?: string
  }

  interface Props {
    open: boolean
    /** 编辑目标（null → 新建态） */
    editing: { name?: string; code?: string } | null
    onClose: () => void
    onSubmit: (values: DictTypeFormValues) => void
  }

  let { open, editing, onClose, onSubmit }: Props = $props()

  const { t, locale } = useT()
  /** 模板文案函数：读 $locale 建立响应式依赖，切语言时重算 */
  const tt = $derived.by(() => {
    void $locale
    return t
  })

  let modalEl: HTMLElement | null = $state(null)
  let formEl: HTMLElement | null = $state(null)
  let nameEl: HTMLElement | null = $state(null)
  let codeEl: HTMLElement | null = $state(null)

  /** vanilla RULES_TYPE：类型名/编码必填 */
  const rules = $derived(
    JSON.stringify({
      name: [{ required: true, message: tt('dict.rule.typeName') }],
      code: [{ required: true, message: tt('dict.rule.typeCode') }],
    }),
  )

  // open 边沿回填（编辑态带出当前值）
  $effect(() => {
    if (!open) return
    void editing
    nameEl?.setAttribute('value', editing?.name ?? '')
    codeEl?.setAttribute('value', editing?.code ?? '')
  })

  /** 保存：触发 oas-form shadow 内原生 form 提交（跨 shadow requestSubmit 通道） */
  function onSave(): void {
    ;(formEl?.shadowRoot?.querySelector('form') as HTMLFormElement | null)?.requestSubmit()
  }

  /** oas-submit：校验通过后的值上行交给父组件编排 */
  function onFormSubmit(e: Event): void {
    const { values } = (e as CustomEvent<{ values: DictTypeFormValues }>).detail
    onSubmit(values)
  }
</script>

<oas-modal
  bind:this={modalEl}
  data-testid="dict-type-modal"
  no-footer
  visible={open ? '' : null}
  onoas-close={onClose}
>
  <div class="modal-body">
    <h2 id="dict-type-title">
      {editing == null ? tt('dict.newType') : tt('dict.editType', { name: editing.name ?? '' })}
    </h2>
    <oas-form bind:this={formEl} {rules} onoas-submit={onFormSubmit}>
      <div class="dict-form-body">
        <div class="form-field">
          <label class="form-label" for="dtf-name">
            {tt('dict.form.typeName')} <span class="req">*</span>
          </label>
          <oas-input
            bind:this={nameEl}
            id="dtf-name"
            data-testid="dtf-name"
            name="name"
            placeholder={tt('dict.placeholder.typeName')}
          ></oas-input>
        </div>
        <div class="form-field">
          <label class="form-label" for="dtf-code">
            {tt('dict.form.typeCode')} <span class="req">*</span>
          </label>
          <oas-input
            bind:this={codeEl}
            id="dtf-code"
            data-testid="dtf-code"
            name="code"
            placeholder={tt('dict.placeholder.typeCode')}
          ></oas-input>
        </div>
        <div class="form-actions">
          <oas-space justify="end">
            
            <oas-button data-testid="dtf-cancel" onclick={onClose}>{tt('common.cancel')}</oas-button>
            
            <oas-button data-testid="dtf-save" type="primary" onclick={onSave}>
              {tt('common.save')}
            </oas-button>
          </oas-space>
        </div>
      </div>
    </oas-form>
  </div>
</oas-modal>
