// templates/admin-pro/vue/src/pages/forbidden.vue
<script setup lang="ts">
// src/pages/forbidden.vue —— 403 无权访问页
import { useRouter } from 'vue-router'
import { useT } from '../composables/use-t'

const { t: tt, locale } = useT()
/** 模板文案函数：读 locale.value 建立响应式依赖，切语言时重渲 */
function t(key: string): string {
  void locale.value
  return tt(key)
}

const router = useRouter()

function goHome(): void {
  void router.push('/dashboard')
}
function goBack(): void {
  if (history.length > 1) history.back()
  else void router.push('/dashboard')
}
</script>

<template>
  <div class="page notice">
    <oas-icon class="notice-icon notice-icon--lock" name="lock" size="28" />
    <div class="notice-code">403</div>
    <h1 class="notice-title">{{ t('common.403.title') }}</h1>
    <p class="notice-desc">{{ t('common.403.desc') }}</p>
    <div class="notice-actions">
      <oas-button type="default" variant="outlined" data-action="back" @click="goBack">
        {{ t('common.back') }}
      </oas-button>
      <oas-button type="primary" data-action="home" @click="goHome">
        {{ t('common.home') }}
      </oas-button>
    </div>
  </div>
</template>

// templates/admin-pro/svelte/src/pages/forbidden.svelte
<script lang="ts">
  // src/pages/forbidden.svelte —— 403 无权访问页
  // 事件：两个按钮均为 light DOM 原生 click，模板直绑 onclick；回退逻辑
  // （history.length > 1 → back，否则去 /dashboard）逐字保留
  import { navigate } from '../router'
  import { useT } from '../lib/use-t.svelte'

  const { t, locale } = useT()
  /** 模板文案函数：读 $locale 建立响应式依赖，切语言时重渲 */
  const tt = $derived.by(() => {
    void $locale
    return t
  })

  function goHome(): void {
    navigate('/dashboard')
  }
  function goBack(): void {
    if (history.length > 1) history.back()
    else navigate('/dashboard')
  }
</script>

<div class="page notice">
  <oas-icon class="notice-icon notice-icon--lock" name="lock" size="28"></oas-icon>
  <div class="notice-code">403</div>
  <h1 class="notice-title">{tt('common.403.title')}</h1>
  <p class="notice-desc">{tt('common.403.desc')}</p>
  <div class="notice-actions">
    <oas-button type="default" variant="outlined" data-action="back" onclick={goBack}>
      {tt('common.back')}
    </oas-button>
    <oas-button type="primary" data-action="home" onclick={goHome}>
      {tt('common.home')}
    </oas-button>
  </div>
</div>
