// templates/admin-pro/react/src/pages/login.tsx
// src/pages/login.tsx —— 登录页：双版式（split/glass）+ oas-form 本地直登
//    useSearchParams 读写（HashRouter 模式下查询串在 hash 内，location.search 恒为空），
//    setSearchParams 触发重渲染切换版式，不整页刷新
//    useOasEvent 绑在**页面根 div** 上（两事件均 bubbles+composed，见 @oas-ui/core emit），
//    根 div 在 split/glass 切换时被 React 复用（同位置同类型只换 className），监听器不丢；
//    若绑在 oas-form 上，切换版式后元素重挂载而 ref 对象不变，useEffect 不会重绑
//    取其 shadowRoot 内 <form> requestSubmit()（playground 实测模式）
//    后整页重渲染，rules/options 等 JSON attribute 随之重算
//    实测（Playwright 全流程）：路由层**不会**自动跳走——session.login() 触发 AppRouter
//    切到已登录分支后，当前 URL 仍是 /login，而已登录路由表不含 /login（匹配落空，
//    react-router 警告 "No routes matched location /login"，页面空白），必须手动 navigate
import { useRef } from 'react'
import { useNavigate, useSearchParams } from 'react-router'
import './login.css'
import { useOasEvent } from '../hooks/use-oas-event'
import { useT } from '../hooks/use-t'
import { session } from '../store/session'
import { appRoutes } from '../router/routes'

type LoginStyle = 'split' | 'glass'

interface LoginSubmitDetail {
  values: { name: string; role?: string }
}

function LogoLight() {
  return (
    <span className="oas-logo oas-logo-light">
      <span className="oas-logo-badge">OAS</span>
      <span className="oas-logo-word">OAS Admin Pro</span>
    </span>
  )
}

export default function LoginPage() {
  const { t } = useT()
  const navigate = useNavigate()
  const [searchParams, setSearchParams] = useSearchParams()
  const style: LoginStyle = searchParams.get('style') === 'glass' ? 'glass' : 'split'
  // 根 div：split/glass 切换时 React 复用同一节点，oas 事件监听挂此处不丢
  const rootRef = useRef<HTMLDivElement>(null)

  const switchStyle = (next: LoginStyle) => {
    const params = new URLSearchParams(searchParams)
    params.set('style', next)
    setSearchParams(params)
  }

  // 跨 shadow 提交：oas-form 内部 <form> 在 shadowRoot 里
  const requestSubmit = () => {
    const host = rootRef.current?.querySelector<HTMLElement>('#login-form')
    const form = host?.shadowRoot?.querySelector('form') as HTMLFormElement | null
    form?.requestSubmit()
  }

  useOasEvent<LoginSubmitDetail>(rootRef, 'oas-submit', (detail) => {
    const values = detail.values
    session.login(values.name || '用户', values.role === 'viewer' ? 'viewer' : 'admin')
    navigate(appRoutes[0].path, { replace: true })
  })
  useOasEvent(rootRef, 'oas-enter', requestSubmit)

  const rules = JSON.stringify({
    name: [{ required: true, message: t('login.rule.name') }],
  })
  const roleOptions = JSON.stringify([
    { label: t('users.role.admin'), value: 'admin' },
    { label: t('profile.roleViewer'), value: 'viewer' },
  ])

  const formBlock = (
    <>
      <div className="login-head">
        <LogoLight />
      </div>
      <h2 className="login-title">{t('login.welcome')}</h2>
      <p className="login-sub">{t('login.subtitle')}</p>
      <oas-form id="login-form" rules={rules}>
        <div className="login-fields">
          <oas-input
            data-testid="login-name"
            name="name"
            placeholder={t('login.namePlaceholder')}
          />
          <oas-select data-testid="login-role" name="role" value="admin" options={roleOptions} />
          <oas-button data-testid="login-submit" type="primary" block onClick={requestSubmit}>
            {t('login.submit')} <oas-icon name="arrow-right" size="14" />
          </oas-button>
        </div>
      </oas-form>
      <div className="login-divider" />
      <p className="login-tip">{t('login.tip')}</p>
    </>
  )

  if (style === 'glass') {
    return (
      <div ref={rootRef} className="login-glass">
        <div className="glass-card" data-theme="dark">
          {formBlock}
        </div>
        <div className="glass-foot">
          <p className="glass-slogan">{t('login.glassSlogan')}</p>
          <button
            className="link-btn link-btn-light"
            type="button"
            onClick={() => switchStyle('split')}
          >
            {t('login.switchSplit')}
          </button>
        </div>
      </div>
    )
  }

  return (
    <div ref={rootRef} className="login-split">
      <div className="login-brand">
        <div className="login-brand-main">
          <LogoLight />
          <h1>{t('login.slogan')}</h1>
          <p>{t('login.sloganSub')}</p>
          <div className="brand-stats">
            <div className="brand-stat">
              <span className="num">117</span>
              <span className="label">{t('login.statComponents')}</span>
            </div>
            <div className="brand-stat">
              <span className="num">22KB</span>
              <span className="label">{t('login.statBundle')}</span>
            </div>
            <div className="brand-stat">
              <span className="num">0</span>
              <span className="label">{t('login.statFrameworks')}</span>
            </div>
          </div>
        </div>
        <pre className="brand-code">{`<oas-button type="primary">${t('common.save')}</oas-button>`}</pre>
      </div>
      <div className="login-panel">
        <div className="login-card">
          {formBlock}
          <button className="link-btn login-alt" type="button" onClick={() => switchStyle('glass')}>
            {t('login.switchGlass')}
          </button>
        </div>
      </div>
    </div>
  )
}

// templates/admin-pro/svelte/src/pages/login.svelte
<script lang="ts">
  // src/pages/login.svelte —— 登录页：双版式（split/glass）+ oas-form 本地直登
  // 版式查询参数的等价实现（react 版 useSearchParams 思路）：参数写在 location.search 段
  // 而非 hash 内——hash 模式下路由 currentPath() 只读 hash 段且 matchRoute 是精确匹配，
  // query 拼进 hash 会被判成未知路径弹 /not-found；写在 search 段则两种路由模式都不参与
  // 路径匹配。pushState 写 search 不触发 hashchange/popstate，路由层无感不重估；
  // 浏览器前进/后退（popstate）时回读 search 同步版式。
  // 事件直绑（Svelte 5 原生支持 kebab 自定义事件）：onoas-submit 绑 oas-form、
  // onoas-enter 绑 oas-input（两事件均 bubbles+composed，见 @oas-ui/core emit）；
  // split/glass 用 if/else 切换重挂载后监听随元素重建，无需 react 版根 div 委托技巧。
  // session.login() 后必须手动 navigate('/dashboard')：路由层不会因登录态自动跳走，
  // 而已登录路由表无 /login，不手动导航会白屏（react 版同款结论）。
  import "./login.css"
  import { useT } from "../lib/use-t.svelte"
  import { navigate } from "../router"
  import { appRoutes } from "../router/routes"
  import { session } from "../store/session"

  type LoginStyle = "split" | "glass"

  interface LoginSubmitDetail {
    values: { name: string; role?: string }
  }

  const { t, locale } = useT()
  /** 模板文案函数：读 $locale 建立响应式依赖，切语言时重渲 */
  const tt = $derived.by(() => {
    void $locale
    return t
  })

  /** 版式初始值：读 URL ?style=（hash/history 两模式 query 均在 search 段） */
  function readLoginStyle(): LoginStyle {
    return new URLSearchParams(window.location.search).get("style") === "glass" ? "glass" : "split"
  }

  /** 版式写回 URL：pushState 留历史条目（对齐 react setSearchParams 默认 push） */
  function writeLoginStyle(next: LoginStyle): void {
    const url = new URL(window.location.href)
    url.searchParams.set("style", next)
    history.pushState(history.state, "", url.pathname + url.search + url.hash)
  }

  let style = $state<LoginStyle>(readLoginStyle())

  // 前进/后退回读版式（search 变化不触发路由事件，路由层不感知，页面自管）
  $effect(() => {
    const syncStyle = (): void => {
      style = readLoginStyle()
    }
    window.addEventListener("popstate", syncStyle)
    return () => window.removeEventListener("popstate", syncStyle)
  })

  function switchStyle(next: LoginStyle): void {
    writeLoginStyle(next)
    style = next
  }

  /** oas-form host（bind:this）：跨 shadow 拿内部 <form> requestSubmit */
  let formEl = $state<HTMLElement | null>(null)

  const requestSubmit = (): void => {
    const form = formEl?.shadowRoot?.querySelector("form") as HTMLFormElement | null
    form?.requestSubmit()
  }

  const onSubmit = (e: Event): void => {
    const values = (e as CustomEvent<LoginSubmitDetail>).detail.values
    session.login(values.name || "用户", values.role === "viewer" ? "viewer" : "admin")
    // 进首页前清掉版式查询参数（history 模式 navigate 换 pathname 天然剥离；hash 模式 search 会残留）
    const url = new URL(window.location.href)
    if (url.search) {
      url.search = ""
      history.replaceState(history.state, "", url.pathname + url.search + url.hash)
    }
    navigate(appRoutes[0].path)
  }

  // 纯数据走 JSON attribute（切语言随 $locale 重算，组件 observedAttributes 感知重读）
  const rules = $derived.by(() => {
    void $locale
    return JSON.stringify({ name: [{ required: true, message: t("login.rule.name") }] })
  })
  const roleOptions = $derived.by(() => {
    void $locale
    return JSON.stringify([
      { label: t("users.role.admin"), value: "admin" },
      { label: t("profile.roleViewer"), value: "viewer" },
    ])
  })
</script>

{#snippet logoLight()}
  <span class="oas-logo oas-logo-light">
    <span class="oas-logo-badge">OAS</span>
    <span class="oas-logo-word">OAS Admin Pro</span>
  </span>
{/snippet}

{#snippet formBlock()}
  <div class="login-head">
    {@render logoLight()}
  </div>
  <h2 class="login-title">{tt("login.welcome")}</h2>
  <p class="login-sub">{tt("login.subtitle")}</p>
  <oas-form id="login-form" bind:this={formEl} rules={rules} onoas-submit={onSubmit}>
    <div class="login-fields">
      <oas-input
        data-testid="login-name"
        name="name"
        placeholder={tt("login.namePlaceholder")}
        onoas-enter={requestSubmit}
      ></oas-input>
      <oas-select data-testid="login-role" name="role" value="admin" options={roleOptions}></oas-select>
      <oas-button data-testid="login-submit" type="primary" block onclick={requestSubmit}>
        {tt("login.submit")}
        <oas-icon name="arrow-right" size="14"></oas-icon>
      </oas-button>
    </div>
  </oas-form>
  <div class="login-divider"></div>
  <p class="login-tip">{tt("login.tip")}</p>
{/snippet}

{#if style === "glass"}
  <div class="login-glass">
    <div class="glass-card" data-theme="dark">
      {@render formBlock()}
    </div>
    <div class="glass-foot">
      <p class="glass-slogan">{tt("login.glassSlogan")}</p>
      <button class="link-btn link-btn-light" type="button" onclick={() => switchStyle("split")}>
        {tt("login.switchSplit")}
      </button>
    </div>
  </div>
{:else}
  <div class="login-split">
    <div class="login-brand">
      <div class="login-brand-main">
        {@render logoLight()}
        <h1>{tt("login.slogan")}</h1>
        <p>{tt("login.sloganSub")}</p>
        <div class="brand-stats">
          <div class="brand-stat">
            <span class="num">117</span>
            <span class="label">{tt("login.statComponents")}</span>
          </div>
          <div class="brand-stat">
            <span class="num">22KB</span>
            <span class="label">{tt("login.statBundle")}</span>
          </div>
          <div class="brand-stat">
            <span class="num">0</span>
            <span class="label">{tt("login.statFrameworks")}</span>
          </div>
        </div>
      </div>
      <pre class="brand-code">{`<oas-button type="primary">${tt("common.save")}</oas-button>`}</pre>
    </div>
    <div class="login-panel">
      <div class="login-card">
        {@render formBlock()}
        <button class="link-btn login-alt" type="button" onclick={() => switchStyle("glass")}>
          {tt("login.switchGlass")}
        </button>
      </div>
    </div>
  </div>
{/if}
