// templates/admin-pro/vue/src/pages/orders-drawer.vue
<script setup lang="ts">
// src/pages/orders-drawer.vue —— 订单详情抽屉（状态标签 + 描述列表 + 流程操作 + 完整详情链接）
// order-detail-action click）
//    order-detail-no/order-detail-tag/order-detail-desc/order-detail-action/order-detail-note）
//    oas-* 按钮在 drawer panel 内，Vue @click 直绑元素本身不受 stopPropagation 影响
//    点击仅上抛 flow(to)，持久化/提示/刷新在父组件（user-detail.vue 先例）
// 3. visible 受控：oas-close 上抛 close 回写父组件 state（user-form.vue 同款）
//    本模版改用 RouterLink 携带 query（/order-detail?id=…），order-detail 页从 route.query.id
//    取值——可观察行为一致（目标页拿到同一订单号），且刷新后可恢复
import { computed } from 'vue'
import type { OrderRow, OrderStatus } from '../data/orders'
import { useT } from '../composables/use-t'

const props = defineProps<{
  open: boolean
  /** 当前抽屉行（父组件从列表数据派生，流程操作成功后随刷新自动更新） */
  row: OrderRow | null
  /** 流转目标（null = 无可用操作，显示提示语） */
  flowTo: OrderStatus | null
  /** 父组件执行流转期间置真：按钮 loading 态（vanilla setAttribute('loading') 同款） */
  flowing: boolean
}>()
const emit = defineEmits<{
  close: []
  flow: [to: OrderStatus]
}>()

const { t: tt, locale } = useT()
/** 模板文案函数：读 locale.value 建立响应式依赖，切语言时重渲 */
function t(key: string, params?: Record<string, string | number>): string {
  void locale.value
  return tt(key, params)
}

const STATUS_TAG: Record<OrderRow['status'], string> = {
  pending: 'warning',
  paid: 'primary',
  shipping: 'purple',
  done: 'success',
  cancelled: 'danger',
}

const statusLabel = computed(() => (props.row ? t(`orders.status.${props.row.status}`) : ''))
const tagType = computed(() => (props.row ? STATUS_TAG[props.row.status] : 'default'))
const amountText = computed(() =>
  props.row ? `¥ ${props.row.amount.toLocaleString('en-US')}` : '',
)
const items = computed(() => props.row?.items ?? [])
const flowLabel = computed(() => (props.row ? t(`orders.flow.${props.row.status}`) : ''))
const note = computed(() => {
  if (!props.row || props.flowTo) return ''
  return props.row.status === 'done' ? t('orders.noteDone') : t('orders.noteCancelled')
})
const detailTo = computed(() => ({
  path: '/order-detail',
  query: props.row?.id ? { id: props.row.id } : {},
}))
</script>

<template>
  <oas-drawer
    data-testid="order-drawer"
    :title="t('orders.detailTitle')"
    placement="right"
    size="medium"
    no-footer
    :visible="open ? '' : null"
    @oas-close="emit('close')"
  >
    <div class="order-detail">
      <div class="order-detail-head">
        <div>
          <div class="order-detail-no mono">{{ row?.id ?? '' }}</div>
          <div class="order-detail-sub">{{ t('orders.detailTitle') }}</div>
        </div>
        <oas-tag
          data-testid="order-detail-tag"
          :type="tagType === 'purple' ? null : tagType"
          :color="tagType === 'purple' ? 'purple' : null"
        >
          {{ statusLabel }}
        </oas-tag>
      </div>
      <oas-descriptions id="order-detail-desc" column="1">
        <oas-descriptions-item :label="t('orders.th.customer')">
          <span>{{ row?.customer ?? '' }}</span>
        </oas-descriptions-item>
        <oas-descriptions-item :label="t('orders.dl.creator')">
          <span>{{ row?.creator ?? '' }}</span>
        </oas-descriptions-item>
        <oas-descriptions-item :label="t('orders.th.amount')">
          <span class="mono">{{ amountText }}</span>
        </oas-descriptions-item>
        <oas-descriptions-item :label="t('orders.th.created')">
          <span class="mono">{{ row?.created ?? '' }}</span>
        </oas-descriptions-item>
        <oas-descriptions-item :label="t('orders.dl.items')">
          <span>
            <oas-tag v-for="it in items" :key="it">{{ it }}</oas-tag>
          </span>
        </oas-descriptions-item>
      </oas-descriptions>
      <div class="order-detail-foot">
        <div class="order-detail-foot-row">
          <oas-button
            v-if="flowTo"
            data-testid="order-detail-action"
            type="primary"
            :loading="flowing ? '' : null"
            @click="emit('flow', flowTo)"
          >
            {{ flowLabel }}
          </oas-button>
          <RouterLink class="link-btn" data-testid="order-detail-link" :to="detailTo">
            {{ t('orders.fullDetail') }}
          </RouterLink>
        </div>
        <div v-if="!flowTo" class="order-detail-note" data-testid="order-detail-note">
          {{ note }}
        </div>
      </div>
    </div>
  </oas-drawer>
</template>

// templates/admin-pro/svelte/src/pages/orders-drawer.svelte
<script lang="ts">
  // src/pages/orders-drawer.svelte —— 订单快捷详情抽屉（orders 页行点击弹出）
  // 对齐 react 版 orders-drawer.tsx：
  // 1. visible 受控：oas-close（遮罩/Esc/✕）→ 回写父级 open 状态（属性单一事实来源）
  // 2. 「查看完整详情」链接：sessionStorage('order-detail-id') 与 react 版同键同时机写入 +
  //    preventDefault 走自研 navigate('/order-detail')（hash/history 双模式均正确）
  // 3. 流程按钮：本组件只管 loading 态与取 target，持久化/提示/刷新在父组件（vanilla 同款编排）；
  //    Svelte 的 onclick 直绑元素本身（不走根委托），oas-drawer panel 的 stopPropagation 无影响
  import type { OrderRow, OrderStatus } from '../data/orders'
  import { navigate } from '../router'
  import { useT } from '../lib/use-t.svelte'
  import { formatMoney, statusLabel, tagTypeFor } from './orders-shared'

  interface Props {
    open: boolean
    /** 当前选中订单（父组件由列表数据派生，流程成功后随刷新自动更新，可能为 null） */
    row: OrderRow | null
    onClose: () => void
    /** 流程按钮：父组件执行 updateOrderStatus + 提示 + 刷新（vanilla 同款编排） */
    onApplyFlow: (id: string, target: OrderStatus) => Promise<void>
  }

  let { open, row, onClose, onApplyFlow }: Props = $props()

  const { t, locale } = useT()
  /** 模板文案函数：读 $locale 建立响应式依赖，切语言时重渲 */
  const tt = $derived.by(() => {
    void $locale
    return t
  })

  /** vanilla FLOW_TO：状态流转（pending→paid→shipping→done），终态无可用操作 */
  const FLOW_TO: Partial<Record<OrderStatus, OrderStatus>> = {
    pending: 'paid',
    paid: 'shipping',
    shipping: 'done',
  }

  const flow = $derived(row && FLOW_TO[row.status] ? { to: FLOW_TO[row.status]! } : null)
  let flowing = $state(false)

  function onLinkClick(e: Event): void {
    if (row?.id) sessionStorage.setItem('order-detail-id', row.id)
    e.preventDefault()
    navigate('/order-detail')
  }

  async function onActionClick(): Promise<void> {
    if (!row || !flow || flowing) return
    flowing = true
    try {
      await onApplyFlow(row.id, flow.to)
    } finally {
      flowing = false
    }
  }

  const note = $derived(
    !row ? '' : row.status === 'done' ? tt('orders.noteDone') : tt('orders.noteCancelled'),
  )

  let drawerEl: HTMLElement | null = $state(null)
  // title 命中 HTMLElement.prototype.title，oas-* 元素上的 title 必须走 setAttribute 通道
  $effect(() => {
    drawerEl?.setAttribute('title', tt('orders.detailTitle'))
  })
</script>

<oas-drawer
  bind:this={drawerEl}
  data-testid="order-drawer"
  placement="right"
  size="medium"
  no-footer
  visible={open ? '' : null}
  onoas-close={onClose}
>
  <div class="order-detail">
    <div class="order-detail-head">
      <div>
        <div class="order-detail-no mono" id="order-detail-no">{row?.id ?? ''}</div>
        <div class="order-detail-sub">{tt('orders.detailTitle')}</div>
      </div>
      {#if row}
        <oas-tag
          data-testid="order-detail-tag"
          id="order-detail-tag"
          type={tagTypeFor(row.status) === 'purple' ? undefined : tagTypeFor(row.status)}
          color={tagTypeFor(row.status) === 'purple' ? 'purple' : undefined}
        >
          {statusLabel(row.status, tt)}
        </oas-tag>
      {/if}
    </div>
    <oas-descriptions id="order-detail-desc" column="1">
      <oas-descriptions-item label={tt('orders.th.customer')}>{row?.customer ?? ''}</oas-descriptions-item>
      <oas-descriptions-item label={tt('orders.dl.creator')}>{row?.creator ?? ''}</oas-descriptions-item>
      <oas-descriptions-item label={tt('orders.th.amount')}>
        <span class="mono">{row ? formatMoney(row.amount) : ''}</span>
      </oas-descriptions-item>
      <oas-descriptions-item label={tt('orders.th.created')}>
        <span class="mono">{row?.created ?? ''}</span>
      </oas-descriptions-item>
      <oas-descriptions-item label={tt('orders.dl.items')}>
        {#each row?.items ?? [] as it, i (`${it}-${i}`)}
          <oas-tag>{it}</oas-tag>
        {/each}
      </oas-descriptions-item>
    </oas-descriptions>
    <div class="order-detail-foot">
      <div class="order-detail-foot-row">
        {#if flow}
          <oas-button
            data-testid="order-detail-action"
            id="order-detail-action"
            type="primary"
            loading={flowing}
            data-target={flow.to}
            onclick={onActionClick}
          >
            {tt(`orders.flow.${row?.status ?? ''}`)}
          </oas-button>
        {/if}
        <a class="link-btn" data-testid="order-detail-link" href="#/order-detail" onclick={onLinkClick}>
          {tt('orders.fullDetail')}
        </a>
      </div>
      {#if !flow}
        <div class="order-detail-note" id="order-detail-note">{note}</div>
      {/if}
    </div>
  </div>
</oas-drawer>
