// templates/admin-pro/react/src/pages/orders-drawer.tsx
// src/pages/orders-drawer.tsx —— 订单快捷详情抽屉（orders 页行点击弹出）
// openDrawer/order-detail-link/order-detail-action 段。
//    「flow 后 refresh 再回填 tag/action」的可观察结果）
// 2. 面板内原生 click 例外直绑：「查看完整详情」链接与流程按钮位于
//    oas-drawer panel 内，panel 对原生事件 stopPropagation，React 根委托收不到，故与
//    'order-detail-id'；本模版路由支持 hash/history 双模式，改 preventDefault + react-router
//    navigate('/order-detail')，sessionStorage 键名与写入时机逐字一致
//    state 单一持有，监听 oas-close 回写 state（product-form 同款）
//    :host([hidden]) 生效，可观察结果一致）
import { useEffect, useRef } from 'react'
import { useNavigate } from 'react-router'
import type { OrderRow, OrderStatus } from '../data/orders'
import { useOasEvent } from '../hooks/use-oas-event'
import { useT } from '../hooks/use-t'
import { formatMoney, statusLabel, tagTypeFor } from './orders-table'

/** vanilla FLOW_TO + flowFor：状态流转（pending→paid→shipping→done） */
const FLOW_TO: Partial<Record<OrderStatus, OrderStatus>> = {
  pending: 'paid',
  paid: 'shipping',
  shipping: 'done',
}

function flowFor(
  status: OrderStatus,
  t: (key: string) => string,
): { label: string; to: OrderStatus } | undefined {
  const to = FLOW_TO[status]
  return to ? { label: t(`orders.flow.${status}`), to } : undefined
}

export interface OrdersDrawerProps {
  open: boolean
  /** 当前选中订单（state.selectedId 同语义；列表刷新后由父组件给出最新行，可能为 null） */
  row: OrderRow | null
  onClose: () => void
  /** 流程按钮：父组件执行 updateOrderStatus + 提示 + refresh（vanilla 同款编排） */
  onApplyFlow: (id: string, target: OrderStatus) => Promise<void>
}

export function OrdersDrawer({ open, row, onClose, onApplyFlow }: OrdersDrawerProps) {
  const { t } = useT()
  const navigate = useNavigate()
  const drawerRef = useRef<HTMLElement | null>(null)
  const actionRef = useRef<HTMLElement | null>(null)
  const linkRef = useRef<HTMLAnchorElement | null>(null)

  // 回调最新化：面板内原生监听只在挂载时绑一次（product-form 同款）
  const rowRef = useRef(row)
  rowRef.current = row
  const onApplyFlowRef = useRef(onApplyFlow)
  onApplyFlowRef.current = onApplyFlow
  const onCloseRef = useRef(onClose)
  onCloseRef.current = onClose

  useEffect(() => {
    const link = linkRef.current
    const action = actionRef.current
    const onLinkClick = (e: Event) => {
      const current = rowRef.current
      if (current?.id) sessionStorage.setItem('order-detail-id', current.id)
      e.preventDefault()
      navigate('/order-detail')
    }
    const onActionClick = async (e: Event) => {
      const current = rowRef.current
      const button = e.currentTarget as HTMLElement
      const target = button.dataset.target as OrderStatus | undefined
      if (!target || !current) return
      button.setAttribute('loading', '')
      await onApplyFlowRef.current(current.id, target)
      button.removeAttribute('loading')
    }
    link?.addEventListener('click', onLinkClick)
    action?.addEventListener('click', onActionClick)
    return () => {
      link?.removeEventListener('click', onLinkClick)
      action?.removeEventListener('click', onActionClick)
    }
  }, [navigate])

  // 组件侧关闭（遮罩/Esc/✕）→ 回写 React 状态（visible 单一事实来源）
  useOasEvent(drawerRef, 'oas-close', () => {
    onCloseRef.current()
  })

  const flow = row ? flowFor(row.status, t) : undefined

  return (
    <oas-drawer
      ref={drawerRef}
      data-testid="order-drawer"
      title={t('orders.detailTitle')}
      placement="right"
      size="medium"
      no-footer
      visible={open}
    >
      <div className="order-detail">
        <div className="order-detail-head">
          <div>
            <div className="order-detail-no mono" id="order-detail-no">
              {row?.id ?? ''}
            </div>
            <div className="order-detail-sub">{t('orders.detailTitle')}</div>
          </div>
          {row && (
            <oas-tag
              data-testid="order-detail-tag"
              id="order-detail-tag"
              type={tagTypeFor(row.status) === 'purple' ? undefined : tagTypeFor(row.status)}
              color={tagTypeFor(row.status) === 'purple' ? 'purple' : undefined}
            >
              {statusLabel(row.status, t)}
            </oas-tag>
          )}
        </div>
        <oas-descriptions id="order-detail-desc" column="1">
          <oas-descriptions-item label={t('orders.th.customer')}>
            {row?.customer ?? ''}
          </oas-descriptions-item>
          <oas-descriptions-item label={t('orders.dl.creator')}>
            {row?.creator ?? ''}
          </oas-descriptions-item>
          <oas-descriptions-item label={t('orders.th.amount')}>
            <span className="mono">{row ? formatMoney(row.amount) : ''}</span>
          </oas-descriptions-item>
          <oas-descriptions-item label={t('orders.th.created')}>
            <span className="mono">{row?.created ?? ''}</span>
          </oas-descriptions-item>
          <oas-descriptions-item label={t('orders.dl.items')}>
            {row?.items.map((it) => (
              <oas-tag key={it}>{it}</oas-tag>
            ))}
          </oas-descriptions-item>
        </oas-descriptions>
        <div className="order-detail-foot">
          <div className="order-detail-foot-row">
            <oas-button
              ref={actionRef}
              data-testid="order-detail-action"
              id="order-detail-action"
              type="primary"
              hidden={!flow || undefined}
              data-target={flow?.to}
            >
              {flow?.label ?? ''}
            </oas-button>
            <a
              className="link-btn"
              data-testid="order-detail-link"
              href="#/order-detail"
              ref={linkRef}
            >
              {t('orders.fullDetail')}
            </a>
          </div>
          <div className="order-detail-note" id="order-detail-note" hidden={!!flow || undefined}>
            {row ? (row.status === 'done' ? t('orders.noteDone') : t('orders.noteCancelled')) : ''}
          </div>
        </div>
      </div>
    </oas-drawer>
  )
}

// templates/admin-pro/svelte/src/pages/orders-drawer.svelte
<script lang="ts">
  // src/pages/orders-drawer.svelte —— 订单快捷详情抽屉（orders 页行点击弹出）
  // 对齐 react 版 orders-drawer.tsx：
  // 1. visible 受控：oas-close（遮罩/Esc/✕）→ 回写父级 open 状态（属性单一事实来源）
  // 2. 「查看完整详情」链接：sessionStorage('order-detail-id') 与 react 版同键同时机写入 +
  //    preventDefault 走自研 navigate('/order-detail')（hash/history 双模式均正确）
  // 3. 流程按钮：本组件只管 loading 态与取 target，持久化/提示/刷新在父组件（vanilla 同款编排）；
  //    Svelte 的 onclick 直绑元素本身（不走根委托），oas-drawer panel 的 stopPropagation 无影响
  import type { OrderRow, OrderStatus } from '../data/orders'
  import { navigate } from '../router'
  import { useT } from '../lib/use-t.svelte'
  import { formatMoney, statusLabel, tagTypeFor } from './orders-shared'

  interface Props {
    open: boolean
    /** 当前选中订单（父组件由列表数据派生，流程成功后随刷新自动更新，可能为 null） */
    row: OrderRow | null
    onClose: () => void
    /** 流程按钮：父组件执行 updateOrderStatus + 提示 + 刷新（vanilla 同款编排） */
    onApplyFlow: (id: string, target: OrderStatus) => Promise<void>
  }

  let { open, row, onClose, onApplyFlow }: Props = $props()

  const { t, locale } = useT()
  /** 模板文案函数：读 $locale 建立响应式依赖，切语言时重渲 */
  const tt = $derived.by(() => {
    void $locale
    return t
  })

  /** vanilla FLOW_TO：状态流转（pending→paid→shipping→done），终态无可用操作 */
  const FLOW_TO: Partial<Record<OrderStatus, OrderStatus>> = {
    pending: 'paid',
    paid: 'shipping',
    shipping: 'done',
  }

  const flow = $derived(row && FLOW_TO[row.status] ? { to: FLOW_TO[row.status]! } : null)
  let flowing = $state(false)

  function onLinkClick(e: Event): void {
    if (row?.id) sessionStorage.setItem('order-detail-id', row.id)
    e.preventDefault()
    navigate('/order-detail')
  }

  async function onActionClick(): Promise<void> {
    if (!row || !flow || flowing) return
    flowing = true
    try {
      await onApplyFlow(row.id, flow.to)
    } finally {
      flowing = false
    }
  }

  const note = $derived(
    !row ? '' : row.status === 'done' ? tt('orders.noteDone') : tt('orders.noteCancelled'),
  )

  let drawerEl: HTMLElement | null = $state(null)
  // title 命中 HTMLElement.prototype.title，oas-* 元素上的 title 必须走 setAttribute 通道
  $effect(() => {
    drawerEl?.setAttribute('title', tt('orders.detailTitle'))
  })
</script>

<oas-drawer
  bind:this={drawerEl}
  data-testid="order-drawer"
  placement="right"
  size="medium"
  no-footer
  visible={open ? '' : null}
  onoas-close={onClose}
>
  <div class="order-detail">
    <div class="order-detail-head">
      <div>
        <div class="order-detail-no mono" id="order-detail-no">{row?.id ?? ''}</div>
        <div class="order-detail-sub">{tt('orders.detailTitle')}</div>
      </div>
      {#if row}
        <oas-tag
          data-testid="order-detail-tag"
          id="order-detail-tag"
          type={tagTypeFor(row.status) === 'purple' ? undefined : tagTypeFor(row.status)}
          color={tagTypeFor(row.status) === 'purple' ? 'purple' : undefined}
        >
          {statusLabel(row.status, tt)}
        </oas-tag>
      {/if}
    </div>
    <oas-descriptions id="order-detail-desc" column="1">
      <oas-descriptions-item label={tt('orders.th.customer')}>{row?.customer ?? ''}</oas-descriptions-item>
      <oas-descriptions-item label={tt('orders.dl.creator')}>{row?.creator ?? ''}</oas-descriptions-item>
      <oas-descriptions-item label={tt('orders.th.amount')}>
        <span class="mono">{row ? formatMoney(row.amount) : ''}</span>
      </oas-descriptions-item>
      <oas-descriptions-item label={tt('orders.th.created')}>
        <span class="mono">{row?.created ?? ''}</span>
      </oas-descriptions-item>
      <oas-descriptions-item label={tt('orders.dl.items')}>
        {#each row?.items ?? [] as it, i (`${it}-${i}`)}
          <oas-tag>{it}</oas-tag>
        {/each}
      </oas-descriptions-item>
    </oas-descriptions>
    <div class="order-detail-foot">
      <div class="order-detail-foot-row">
        {#if flow}
          <oas-button
            data-testid="order-detail-action"
            id="order-detail-action"
            type="primary"
            loading={flowing}
            data-target={flow.to}
            onclick={onActionClick}
          >
            {tt(`orders.flow.${row?.status ?? ''}`)}
          </oas-button>
        {/if}
        <a class="link-btn" data-testid="order-detail-link" href="#/order-detail" onclick={onLinkClick}>
          {tt('orders.fullDetail')}
        </a>
      </div>
      {#if !flow}
        <div class="order-detail-note" id="order-detail-note">{note}</div>
      {/if}
    </div>
  </div>
</oas-drawer>
